### ISSUE TITLE
Report is not generated in android project with `useJacoco = true`

### ISSUE THREAD

**Issue by Corje** [Kotlin/kotlinx-kover#10]
In android project set kover plugin to use Jacoco agent ([see](https://github.com/Kotlin/kotlinx-kover#customize-settings))
You will get `Error while creating report` when performing test task.

Project for reproduce is attached.
[AndroidCoverage 2.zip](https://github.com/Kotlin/kotlinx-kover/files/7259382/AndroidCoverage.2.zip)

**Comment by shanshin** [comment]
API changed in `0.4.0`, Android tasks configured [differently](https://github.com/Kotlin/kotlinx-kover#configuring-jvm-test-task).
