### ISSUE TITLE
Typo in the README for Android setup

### ISSUE THREAD

**Issue by mezpahlan** [Kotlin/kotlinx-kover#101]
The README contains the following snippet under the section `Example of configuring test task for build type debug in Android`:

```
android {
    // other Android declarations

    testOptions {
        unitTests.all {
            if (it.name == "testDebugUnitTest") {
                extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                    isEnabled = true
                    binaryReportFile.set(file("$buildDir/custom/debug-report.bin"))
                    includes = listOf("com.example.*")
                    excludes = listOf("com.example.subpackage.*")
                }
            }
        }
    }
}
```

When I copied this into my project it wouldn't build with the following error:

```
> Extension of type 'KoverTaskExtension' does not exist.
```

Is this missing an `it`? Perhaps like this (changes in **bold**)?

<pre>
android {
    // other Android declarations

    testOptions {
        unitTests.all {
            if (it.name == "testDebugUnitTest") {
                <strong>it.</strong>extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                    isEnabled = true
                    binaryReportFile.set(file("$buildDir/custom/debug-report.bin"))
                    includes = listOf("com.example.*")
                    excludes = listOf("com.example.subpackage.*")
                }
            }
        }
    }
}
</pre>

This ensures that the `KoverTaskExtension` is configured on the Test task rather than the Android project. If you agree, let me know I can raise a quick PR. Thanks.

**Comment by shanshin** [comment]
Thanks for the issue!
