### ISSUE TITLE
Why does `koverHtmlReport` and `koverXmlReport` `dependOn` instead of `mustRunAfter` the test tasks?

### ISSUE THREAD

**Issue by mezpahlan** [Kotlin/kotlinx-kover#107]
Whilst looking at the source I noticed that `koverHtmlReport` and `koverXmlReport` `dependOn` all test tasks that have the `KoverTaskExtension` enabled - by default all test tasks unless the user has configured a task not to be enabled.

![image](https://user-images.githubusercontent.com/4974178/147095984-ae1181f1-74ea-4ad8-88ad-3454b6db53a7.png)

In comparison `koverCollectReports` is configured to `mustRunAfter` `koverHtmlReport` and `koverXmlReport`.

![image](https://user-images.githubusercontent.com/4974178/147096301-b38d699c-d000-4585-8b08-c9167ef711f6.png)

I was wondering why this is? My usecase is that I would like to run my test tasks on the CI first and then in a later stage of my pipeline collect the report results. Something like:

```
ci-pipeline {
  stage-1 {
    // build
  }  
  stage-2 {
    // test
  } 
  stage-3 {
    // send reports
  } 
} 
```

Currently the testing task will run twice instead of once. Not a massive issue but I was just curious as to the reasons.

**Comment by shanshin** [comment]
Hi,
By this behavior, a minimum guarantee is achieved that, by default, coverage from all tests will definitely get into the reports.
`koverCollectReports` does not generate the report itself, and it should not be used independently, so there are no such requirements for it.

If `dependOn` is replaced with `mustRunAfter`, it will be necessary to list all test tasks every time (which are not always called the same for all projects) and if you forget to specify some task, issue may be unnoticeable (the percentage of coverage may change slightly).

Can you use the build cache in your pipeline? In this case, the tests will not be run again and the previously calculated reports will be used.

**Comment by mezpahlan** [comment]
Thank you. That makes sense.

And of course, caching! Why didn't I think of that?! I had that disabled in my project so I turned it on by adding `org.gradle.caching=true` into my `gradle.properties` for the project. 

I then ran the tests (stage 2 in the my example above).

```
Executing tasks: [testDebugUnitTest] in project


> Task :project:preBuild UP-TO-DATE
> Task :project:preDebugBuild UP-TO-DATE
> Task :project:compileDebugAidl NO-SOURCE
> Task :project:compileDebugRenderscript NO-SOURCE
> Task :project:generateDebugBuildConfig UP-TO-DATE
> Task :project:generateDebugResValues UP-TO-DATE
> Task :project:generateDebugResources UP-TO-DATE
> Task :project:packageDebugResources UP-TO-DATE
> Task :project:parseDebugLocalResources UP-TO-DATE
> Task :project:processDebugManifest UP-TO-DATE
> Task :project:generateDebugRFile UP-TO-DATE
> Task :project:compileDebugKotlin UP-TO-DATE
> Task :project:processDebugJavaRes NO-SOURCE
> Task :project:bundleLibResDebug UP-TO-DATE
> Task :project:javaPreCompileDebug UP-TO-DATE
> Task :project:compileDebugJavaWithJavac UP-TO-DATE
> Task :project:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :project:bundleLibCompileToJarDebug UP-TO-DATE
> Task :project:preDebugUnitTestBuild UP-TO-DATE
> Task :project:generateDebugUnitTestStubRFile UP-TO-DATE
> Task :project:compileDebugUnitTestKotlin UP-TO-DATE
> Task :project:javaPreCompileDebugUnitTest UP-TO-DATE
> Task :project:compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :project:processDebugUnitTestJavaRes NO-SOURCE
> Task :project:testDebugUnitTest

BUILD SUCCESSFUL in 20s
16 actionable tasks: 1 executed, 15 up-to-date
14:39:05: Task execution finished 'testDebugUnitTest'.
```

And after that the report (stage 3)

```
14:39:51: Executing task 'koverXmlReport'...

Executing tasks: [koverXmlReport] in project

> Task :project:preBuild UP-TO-DATE
> Task :project:preDebugBuild UP-TO-DATE
> Task :project:compileDebugAidl NO-SOURCE
> Task :project:compileDebugRenderscript NO-SOURCE
> Task :project:generateDebugBuildConfig UP-TO-DATE
> Task :project:generateDebugResValues UP-TO-DATE
> Task :project:generateDebugResources UP-TO-DATE
> Task :project:packageDebugResources UP-TO-DATE
> Task :koverXmlReport UP-TO-DATE
> Task :project:parseDebugLocalResources UP-TO-DATE
> Task :project:processDebugManifest UP-TO-DATE
> Task :project:generateDebugRFile UP-TO-DATE
> Task :project:compileDebugKotlin UP-TO-DATE
> Task :project:processDebugJavaRes NO-SOURCE
> Task :project:bundleLibResDebug UP-TO-DATE
> Task :project:javaPreCompileDebug UP-TO-DATE
> Task :project:compileDebugJavaWithJavac UP-TO-DATE
> Task :project:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :project:bundleLibCompileToJarDebug UP-TO-DATE
> Task :project:preDebugUnitTestBuild UP-TO-DATE
> Task :project:generateDebugUnitTestStubRFile UP-TO-DATE
> Task :project:compileDebugUnitTestKotlin UP-TO-DATE
> Task :project:javaPreCompileDebugUnitTest UP-TO-DATE
> Task :project:compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :project:processDebugUnitTestJavaRes NO-SOURCE
> Task :project:testDebugUnitTest FROM-CACHE
> Task :project:koverXmlReport UP-TO-DATE

BUILD SUCCESSFUL in 654ms
18 actionable tasks: 1 from cache, 17 up-to-date
14:39:52: Task execution finished 'koverXmlReport'.
```

I can see that `Task :project:testDebugUnitTest FROM-CACHE` indicates that the test run that had just been run was used rather than executing another one.

Thank you again.
