### ISSUE TITLE
how to run only for DebugUnitTest

### ISSUE THREAD

**Issue by DavidFaermanPendo** [Kotlin/kotlinx-kover#110]
Android Studio
i am using 0.4.4 (0.5-rc make config never ends on sync)
The example if testDubeg.... is not working it says there i no enable disable isenable or isdisable 
Thanks

**Comment by GabrielLasso** [comment]
I'm also using 0.4.4 and want to run only for DebugUnitTest. Running for InternalUnitTest and ReleaseUnitTest is redundant in my project

**Comment by nuhkoca** [comment]
Yeah @shanshin I also noticed that the plugin in my project created stuff for debug, internal and release variants for each module and this is definitely time and resource wasting IMO. How do I make it work for only debug variant?

**Comment by shanshin** [comment]
Hi,
@DavidFaermanPendo, you are using `build.gradle.kts` files in the project?

**Comment by phillwiggins** [comment]
Hey, I'm using

`subprojects {
    afterEvaluate {
        tasks.withType(Test::class).configureEach {
            extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                if ("testDebugUnitTest".contentEquals(name)) {
                    isDisabled = false
                    excludes = listOf(".*BuildConfig.*")
                    binaryReportFile.set(file("$buildDir/kover/$name/report.bin"))
                } else {
                    isDisabled = true
                }
            }
        }
    }
}`

This seems to work and only runs for my debug build variant.

**Comment by shanshin** [comment]
If you use kotlin to write build scripts, then there was a typo in the README in the example, you need to write:
```
android {
    // other Android declarations

    testOptions {
        unitTests.all {
            if (it.name == "testDebugUnitTest") {
                it.extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                    isDisabled = false
                    binaryReportFile.set(file("$buildDir/custom/debug-report.bin"))
                    includes = listOf("com.example.*")
                    excludes = listOf("com.example.subpackage.*")
                }
            }
        }
    }
}
```
`it` was missed before `extensions` in the example

**Comment by shanshin** [comment]
> 0.5-rc make config never ends on sync

@DavidFaermanPendo, try to apply the plugin in the root project to avoid this problem

**Comment by GabrielLasso** [comment]
In my case I had to put

```
            } else {
                kover {
                    disabled = true
                }
            }
```

**Comment by tugceaktepe** [comment]
Hello [shanshin](https://github.com/shanshin) ,

I had to put `else` block like Gabriel's solution in app build.gradle. 

Meanwhile I'm not using build.gradle.kts and I want to solve this problem in root gradle file. How can I solve in root build.gradle file ?

Thanks in advance.
