### ISSUE TITLE
Kover and Gradle tests with Gradle Test Kit

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx-kover#111]
I have a multiproject project where there are a lot of Gradle Plugins with tests that are using `gradleTestKit()`. If I add Kover to the project, Gradle tests that use Gradle Test Kit start to fail.

Repro: https://github.com/JavierSegoviaCordoba/gradle-plugins/tree/kover-repro

Comment/uncomment Kover in the root repo plugins block to reproduce the issue.

Looks like Kover is blocking my plugins can be added to the test classpath by Gradle Test Kit.

**Comment by JavierSegoviaCordoba** [comment]
Tried with 0.5.0-RC2 but no luck, it still fails.

**Comment by shanshin** [comment]
Hi,
when applying the plugin, an identical path is used. 
The use of the plugin itself does not affect the functional tests in any way, you can make sure of this if you uncomment the `javiersc-code-coverage` in the root project, and add 
```
tasks.test {
    extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
        isDisabled = true
    }
}
```
 to some project - then functional tests will work in this project.

For some reason, using an javaagent to instrumentation functional tests causes an error. You can check this by applying the `jacoco` plugin to any project - functional tests will fall.

Further study is needed to understand why any code instrumentation breaks functional tests.

**Comment by JavierSegoviaCordoba** [comment]
This should work on 0.7.0, right?
