### ISSUE TITLE
Code coverage is incorrect

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx-kover#113]
[This project](https://github.com/JavierSegoviaCordoba/kotlin-stdlib) should have `Collections.kt` and `Strings.kt` partially/totally covered but Kover is having a few weird behaviors.

Checking the HTML files, not sure if XML ones are correct.

- At the start, in Windows machine, `Strings.kt` had 0% and `Collections.kt` had 100%. I did a `--rerun-tasks` plus `--no-build-cache` and now `Strings.kt` is covered but `Collections.kt` has no percentage.
- In macOS I am having the same behavior as the second one in the Windows machine. The project didn't exist in the machine, it was a new clone.
- In CI (macOS + Ubuntu + Windows) I am getting what I think is the correct behavior, both, `Strings.kt` and `Collections.kt` being covered. All code coverage reports can be downloaded at the end of [this link](https://github.com/JavierSegoviaCordoba/kotlin-stdlib/actions/runs/1647430250).

**Comment by shanshin** [comment]
Fixed in `0.5.0`
