### ISSUE TITLE
Intellij engine report not supported by codecov

### ISSUE THREAD

**Issue by christian-draeger** [Kotlin/kotlinx-kover#117]
Hi,
i am measuring coverage using kover version 0.5.0-RC in a multi-project project.

when generating an aggregated html and xml report on my local machine everything looks correct (~89% coverage overall).
my local html report looks like this:
![image](https://user-images.githubusercontent.com/22223458/148929838-a79e61cb-3672-42e9-bba8-07ef72ff8295.png)

and my local xml report like this:
![image](https://user-images.githubusercontent.com/22223458/148931342-c135d87a-6ea9-453f-a4d4-d241bd3fd1b7.png)

when generating the report from CI (github actions) and uploading it to codecov i get a different (wrong) overall coverage of 70%.

here is my setup:

- kover plugin applied in root prijects gradle file
- [task config](https://github.com/skrapeit/skrape.it/blob/8c6ff2e1f5de8f36e4f5427d2c5fd04695e07025/build.gradle.kts#L183)
- [github action config to upload to codecov](https://github.com/skrapeit/skrape.it/blob/8c6ff2e1f5de8f36e4f5427d2c5fd04695e07025/.github/workflows/gradle.yml#L36)

corresponding codecov report: https://app.codecov.io/gh/skrapeit/skrape.it

only thing that i can imagine is that the report generated by the CI is different for some unknown reason or codecov doesn't understand the report completely.

if second assumtion is the reason i think it would be cool if well-known tools like codecov would be supported

**Comment by shanshin** [comment]
Hi, 
do you have the ability to download a `report.xml` file from the CI?

**Comment by christian-draeger** [comment]
I printed the report to console on CI.
https://github.com/skrapeit/skrape.it/runs/4774645961?check_suite_focus=true#step:6:8543

Looks good, or at least same as on my local machine.

For some odd reason codecov is saying something different. One other thing I noticed is that codecov is not giving a complexity report anymore which it did when I was using jacoco before

![Screenshot_20220111-140218~2.jpg](https://user-images.githubusercontent.com/22223458/148947700-78108963-9955-4643-9ace-7b55be2352ca.jpg)

**Comment by shanshin** [comment]
Probably codecov does not see some  projects and therefore does not take into account their classes in the final percentage of coverage. More precisely, you can understand if you find the classes that are present in `report.xml` file, but are missing in the codecov report.

The IntelliJ reporter does not support complexity counting so the corresponding counter is missing in the `report.xml` file.

**Comment by christian-draeger** [comment]
ok i see.

i switched to jacoco engine now and made a diff to compare intellij engine result vs jacoco engine result.
both have different results (which probably can make sense since its different engines with different logic i guess, but don't know if that is intended).

![image](https://user-images.githubusercontent.com/22223458/148953961-81a7099b-b24c-4377-94a2-52b36cd2fdda.png)

from first quick look i think the report.xml structure looks slightly different when compairing both engines result, maybe the reason why codecov doesnt understand the intellij engine one.

uploading the jacoco engine report to codecov leads to consistent result - codecov saying same numbers as the report.xml and taking all packages into account

**Comment by shanshin** [comment]
What percentage of coverage does codecov show for the JaCoCo report from the last image?

Judging by the values, there should be 90.9% for instructions and 89.3% for complexity.

**Comment by christian-draeger** [comment]
Nearly,
It says 86,22% for covarage (whatever that means, maybe some median of coverage numbers) and 80,37% for complexity 🤔

![Screenshot_20220111-180911.jpg](https://user-images.githubusercontent.com/22223458/148989470-44d6b9c4-22dd-471f-aeab-091d263eae63.jpg)

**Comment by christian-draeger** [comment]
Calculation based on the missed and covered numbers from the jacoco report (I guess this is how codecov calculates the coverage):

90,98% instruction
78,29% branch 
89,33% line 
85,24% method
82,91% class
-------------------
85,35% average - - - > codecov shows 86,22%

81,34 complexity - - - > codecov shows 80,37%

With rounding etc I would say the codecov numbers are ok when uploading the jacoco engine based report

**Comment by shanshin** [comment]
According to the chart, for the IntelliJ report, the percentage of line coverage was 68.61, however, it follows from the report that 89.57 - this definitely cannot be a rounding error.

Perhaps codecov calculates the percentage itself by analyzing classes and for some reason skips some classes. For a detailed analysis, we will try to reproduce the problem on a small project.


> How comes that the branch coverage the Intellij engine calculates is that low compared to jacoco?
perhaps this is a bug when counting branches.

We will definitely analyze the HTML report for the IntelliJ engine.

**Comment by christian-draeger** [comment]
sure. did the name of the task has been changed??
![image](https://user-images.githubusercontent.com/22223458/149777344-ad56e8be-2510-408d-903a-512f49527873.png)

**Comment by christian-draeger** [comment]
looks good 

intellij engine:
![image](https://user-images.githubusercontent.com/22223458/149779173-805fa81a-3b37-453f-9abb-537bbb32e189.png)
counter type="BRANCH" missed="93" covered="288"/>

jacoco engine:
![image](https://user-images.githubusercontent.com/22223458/149779676-b3105298-1b37-4564-8250-ff1512a06497.png)
<counter type="BRANCH" missed="79" covered="285"/>

**Comment by shanshin** [comment]
> sure. did the name of the task has been changed?? ![image](https://user-images.githubusercontent.com/22223458/149777344-ad56e8be-2510-408d-903a-512f49527873.png)
> 
> is `koverMergedReport` the new equivalent task?

`koverCollectProjectsReports` was renamed to `koverCollectReports`. 
`koverMergedReport` generates single XML/HTML report with merged coverage data from all projects.

**Comment by shanshin** [comment]
> looks good

Does codecov show the coverage correctly on the chart?

**Comment by christian-draeger** [comment]
Yes, codecov shows correct numbers now when using version 0.5.0-RC2 and Intellij engine 🙂
