### ISSUE TITLE
Include/Exclude packages in every task

### ISSUE THREAD

**Issue by lars-reimann** [Kotlin/kotlinx-kover#120]
In 0.5.0-RC2 it's possible to include/exclude specific packages during
* instrumentalization
* HTML/XML report generation
* Verification
* Merged HTML/XML report generation
* Merged verification

Is it also possible to include/exclude packages everywhere without configuring individual tasks or all tasks with a specific type separately?

**Comment by Saketh-Karumuri** [comment]
Also curious when RC2 or the next version is scheduled to be released. Eagerly waiting to use the includes/excludes functionality during task verification. Thanks for the great tool!

**Comment by shanshin** [comment]
Hi,
at the moment, filters must be specified for each task separately.

**Comment by shanshin** [comment]
@Saketh-Karumuri `0.5.0-RC2` is released

**Comment by lars-reimann** [comment]
Thanks for the information. This might eventually be a nice feature to have. But inclusion/exclusion already works well, so feel free to close this.

**Comment by shanshin** [comment]
Relates #19
