### ISSUE TITLE
Support for class, method coverage koverVerify

### ISSUE THREAD

**Issue by Saketh-Karumuri** [Kotlin/kotlinx-kover#128]
Are there any plans to add rules for class, method, branch coverage for the koverVerify task? Currently only line coverage is being supported.

**Comment by shanshin** [comment]
Yes, in the near future we have plans to implement a verifier for the IntelliJ Coverage Engine, and after that we will improve the API for adding validation rules.

**Comment by SimonedeGijt** [comment]
I think the additional value of Kover will improve significantly if we can also add verification on branch% ! 

Speaking of which, I did notice that in the report you can not really see how many branches you've missed per line. Only branch% of the entire class. This makes improving your tests a lot harder as you don't really know how many branches you are missing for specific functions (especially when the file is quite big).

Is this something you guys are looking at in the future as well or shall I send in a new request for that? :)

**Comment by husam-e** [comment]
+++ Really need branch coverage support (report + verification) to transition to this from JaCoCo, which has lots of issues dealing with "ghost" kotlin branches in bytecode
