### ISSUE TITLE
Is there a way to improve coverage (or ignore) autogenerated code of kotlinx.serialization?

### ISSUE THREAD

**Issue by mskonovalov** [Kotlin/kotlinx-kover#130]
So currently if you use serialization all the generated classes got reported as not covered :(

<img width="1104" alt="Screen Shot 2022-01-24 at 11 11 54 am" src="https://user-images.githubusercontent.com/4463812/150705376-87ec4bc8-0487-4f99-9c95-9e8f4d1ded15.png">

Is there a way to automatically exclude such autogenerated helper classes from coverage?

(Intellij engine is a bit better than JaCoCo but still not perfect)

**Comment by shanshin** [comment]
Relates #121

**Comment by mskonovalov** [comment]
Thanks for looking into this.
I have a suggestion: if possible don't replicate jacoco feature where they require to add @Generated annotation to the code you want to ignore.
Instead I'd suggest to allow to configure the list of annotations to ignore in build.gradle.
Thanks

**Comment by dar-dawn** [comment]
maybe this?

```
    filters {
        classes {
            // ignore autogenerated classes generated by 'kotlinx.serialization'
            excludes += listOf("**.*\$\$serializer")
        }
    }
```

**Comment by shanshin** [comment]
Since version `0.6.1`, it has become possible to ignore classes marked with the specified annotations. You can add an exclusion of the annotation `kotlin.serialization.Serializable` like [this](https://github.com/Kotlin/kotlinx-kover#configuring-project ) example.
