### ISSUE TITLE
Unreliable Coverage reports

### ISSUE THREAD

**Issue by mustafaozhan** [Kotlin/kotlinx-kover#134]
Hello 👋 

Thought a lot how to fill this issue, that's why please let me know If I can provide any more information.

So the problem is Kover (somehow) not populating the same coverages all the time. Sometimes some methods shown as covered and uncovered. (Meanwhile, I use Codecov to visualize my reports, but I do not think that it can cause this errors)

ie.
<img width="1096" alt="Screenshot 2022-02-07 at 14 51 42" src="https://user-images.githubusercontent.com/30001999/152800722-8b2a66ea-2d79-4a7f-93eb-1d74b20d5fec.png">
This line (172) is bein covored or not covered time to time

<img width="1096" alt="Screenshot 2022-02-07 at 14 52 44" src="https://user-images.githubusercontent.com/30001999/152800890-9e24c808-0cd1-438a-ba25-4510f28aeb37.png">
This is the same line in different ViewModel, Same applies for this line (92) is bein covored or not covered time to time

**Comment by shanshin** [comment]
Hi,
in your first example, are you sure that line 172 is actually being always executed?
If the expression `settingsRepository.adFreeEndDate.isRewardExpired()` is false, then this line may not be executed, and for the second example `isRewardExpired()` is true, therefore line 92 is marked in green.

**Comment by mustafaozhan** [comment]
Ohh I sew your point you might be right 👍 I am closing this issue I will update my tests and if necessary I will open again. Thanks a lot!
