### ISSUE TITLE
Kover plugin in Gradle buildSrc: multiple versions on classpath

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx-kover#135]
If a kover plugin dependency appears in `buildSrc/build.gradle.kts`, the Kotlin compiler warns
> Runtime JAR files in the classpath should have the same version

and
> Consider providing an explicit dependency on kotlin-reflect 1.6 to prevent strange errors

However, providing an explicit dependency on kotlin-reflect 1.6 does not help.

##### Versions
Kover: 0.5.0
Kotlin: 1.6.10, 1.6.20-M1

##### Reproducer
https://github.com/OliverO2/kotlin-multiplatform-arena/tree/issues/kover-buildsrc-classpath

##### Output
```
> Task :compileKotlin
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
/home/oliver/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-1.5.31.jar (version 1.5)
/home/oliver/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-common-1.5.31.jar (version 1.5)
/home/oliver/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-jdk7-1.5.31.jar (version 1.5)
/home/oliver/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-jdk8-1.5.31.jar (version 1.5)
/home/oliver/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-reflect-1.5.31.jar (version 1.5)
/home/oliver/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
/home/oliver/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.5.31/1523fcd842a47da0820cea772b19c51056fec8a9/kotlin-reflect-1.5.31.jar (version 1.5)
/home/oliver/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
/home/oliver/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
/home/oliver/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (version 1.6)
w: Consider providing an explicit dependency on kotlin-reflect 1.6 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

##### Notes

The error no longer occurs after removing the following dependency in `buildSrc/build.gradle.kts`:
```kotlin
    implementation("org.jetbrains.kotlinx:kover:0.5.0")
```

##### Related
* [KT-38010 – Invalid warning "Runtime JAR files in the classpath should have the same version." with `java-gradle-plugin`](https://youtrack.jetbrains.com/issue/KT-38010)
* [KT-41142 – Kotlin version conflict when using Kotlin Gradle plugins in pre\-compiled script plugin](https://youtrack.jetbrains.com/issue/KT-41142)

**Comment by shanshin** [comment]
Hi,
the Kover plugin has a transitive dependency on the stdlib version 1.6.10, if this dependency conflicts with another one from the classpath, you can exclude it, the plugin has been working stably since 1.5. 

```
    implementation("org.jetbrains.kotlinx:kover:0.5.0") {
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-jdk8")
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-jdk7")
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib")
    }
```

**Comment by OliverO2** [comment]
Thanks! Excluding the above dependencies makes `buildSrc` compile without the classpath warning.

It seems that Kotlin embedded in Gradle 7.4 depends on those conflicting 1.5.31 versions. Seems like Gradle is not prepared to handle plugins with dependencies on newer `stdlib` versions, correct?

**Comment by shanshin** [comment]
Yes, Gradle use own embedded standard library in `buildSrc` and for Gradle `7.4` this is `1.5.31`.
When the versions differ significantly (`1.5` and `1.6`), such an error appears due to the fact that the dependency may use some API that is not in the old version, or the behavior is different.
However, Kover does not use features from stdlib `1.6`, so it is compatible with `1.5`.

**Comment by OliverO2** [comment]
Thanks, good to know. As a warning about "strange errors" sounds slightly alarming, maybe you could package the Kover plugin with relaxed dependencies, so that it accepts 1.5 without that warning. Or maybe add some documentation about the special case with `buildSrc`.

**Comment by shanshin** [comment]
Certainly, we are looking for a solution of this problem so that such messages do not appear to users of both old and new versions of Gradle.
