### ISSUE TITLE
Overall Coverage Summary is not correct

### ISSUE THREAD

**Issue by AnjaniJoshi** [Kotlin/kotlinx-kover#141]
Hi , code coverage report is not perfect its included all classes(data binding, adapters). In jacoco report same code showing 92% test coverage. Also Include and exclude is not working properly. I have excluded some number of classes but each time its showing in report. I want to include only viewmodel classes for test report. One more issue i was found, each time it was taking 1hr to generate complete report .I have questions like if we exclude some classes then why these classes showing in coverage report ? 
Thanks In advance !!

<img width="1779" alt="Screenshot 2022-02-15 at 2 16 08 PM" src="https://user-images.githubusercontent.com/14215452/154027327-472c3536-9551-45ca-9401-62623dd28419.png">

**Comment by shanshin** [comment]
Hi,
may you clarify how do you exclude classes?
To exclude classes from the report, you need to add exclusion rules to the report generation tasks, for example, like this
```
// merged report for multi-project builds
tasks.koverMergedHtmlReport {
    excludes = listOf("com.example.subpackage.*")
}
```
*example for `build.gradle.kts` file


`each time it was taking 1hr to generate complete report` - please provide more details: this is a report on one project (koverHtmlReport) or a merged report (koverMergedHtmlReport), how many class-files are in the project, how many of them are synthetic, how many lines are in the source code

**Comment by AnjaniJoshi** [comment]
Hi @shanshin ,
i'm using this code inside app build.gradle file, I was used both./gradlew koverHtmlReport & ./gradlew koverReport. My project having almost 140,565 lines of code and i also tried with demo project . do you have any reference doc for android implementation??.

`how many of them are synthetic` -  i am using view binding .

<img width="400" alt="Screenshot 2022-02-15 at 5 07 59 PM" src="https://user-images.githubusercontent.com/14215452/154054868-4b6b7e36-02c8-4414-80a6-66cd1f94c47f.png">


>         testOptions {  unitTests.all {

                if (name == "testDebugUnitTest") {
                    kover {
                        disabled = false
                        isEnabled = true
                        includes = [${project.projectDir}/src/main/java]
                        exclude = ['**/R.class',
                                   '**/R$*.class',
                                   '**/BuildConfig.*',
                                   '**/Manifest*.*',
                                   '**/*Fragment*.*',
                                   '**/*Activity*.*',
                                   '**/*Listener*.*',
                                   '**/*Adapter*.*',
                                   '**/*ViewPager*.*',
                                   '**/*common/**/*.*',
                                   '**/*AppUtil*.*']
                        binaryReportFile.set(file("${buildDir}/reports/kover"))
                        generateReportOnCheck = true
                    }
                }
            }
        }

**Comment by shanshin** [comment]
`do you have any reference doc for android implementation??.` - configuring report filtering is similar to configuring a JVM application.


by specifying `excludes` here, you are not excluding a class from the report, you are skipping it from instrumentation (coverage for such classes in the report will always be 0).
```
            if (name == "testDebugUnitTest") {
                kover {
                    ...
                    exclude = ['**/R.class', ...
```


To exclude classes from report you need to configure your `app` project. Add 
```
tasks.koverHtmlReport {
    includes = [...] // your inclusion rules
    excludes = [...]  // your exclusion rules
}
```
and run `./gradlew :app:koverHtmlReport` - this will generate a report only for the `app` project

`['${project.projectDir}/src/main/java']` - the exclusion or inclusion rule is class name with wildcards `?` and `*`. The file name cannot be used. There is also no wildcard `**`
Examples of filters: `exclude = ['com.example.app.Main', 'com.example.app.*Test*']`
