### ISSUE TITLE
Add support for Gradle Configuration Cache

### ISSUE THREAD

**Issue by NikolayMetchev** [Kotlin/kotlinx-kover#142]
The gradle plugin for kover seems to break gradle configuration cache. Please consider updating it to work with this feature.

Example problems:

17 problems were found storing the configuration cache, 7 of which seem unique.
- Task `:koverMergedHtmlReport` of type `kotlinx.kover.tasks.KoverMergedHtmlReportTask`: cannot serialize object of type 'org.gradle.api.tasks.testing.Test', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:koverMergedVerify` of type `kotlinx.kover.tasks.KoverMergedVerificationTask`: cannot serialize object of type 'org.gradle.api.tasks.testing.Test', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:koverMergedXmlReport` of type `kotlinx.kover.tasks.KoverMergedXmlReportTask`: cannot serialize object of type 'org.gradle.api.tasks.testing.Test', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:koverVerify` of type `kotlinx.kover.tasks.KoverVerificationTask`: cannot serialize object of type 'org.gradle.api.tasks.testing.Test', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:utils:common:koverVerify` of type `kotlinx.kover.tasks.KoverVerificationTask`: cannot serialize object of type 'org.gradle.api.tasks.testing.Test', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:utils:common:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:utils:common:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

**Comment by shanshin** [comment]
@NikolayMetchev, a release with these changes will be published in the coming days.

**Comment by shanshin** [comment]
@NikolayMetchev, you may check on version `0.5.1`.

**Comment by NikolayMetchev** [comment]
Yep, seems to be working now
