### ISSUE TITLE
Project Isolation support

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx-kover#144]
> To apply the plugin to all Gradle projects, you only need to apply the plugin to the top-level build file as shown [above](https://github.com/Kotlin/kotlinx-kover#apply-plugin-to-a-single-project-build)

With regards to project isolation support ([docs](https://gradle.github.io/configuration-cache/#project_isolation)), this seems to be a bit of a problem. One project should not access another project.

https://github.com/Kotlin/kotlinx-kover/blob/e1f3fbc4232216bf55b3c43ca0ad193e639afd68/src/main/kotlin/kotlinx/kover/KoverPlugin.kt#L48-L50

Above, the root project is accessing other projects. I somewhat solve this problem by having separate plugins:

```kotlin
com.myPlugin.aggregator
com.myPlugin.subproject
```
`com.myPlugin.subproject` is applied to subprojects, and `com.myPlugin.aggregator` is responsible for aggregating the output from subprojects that apply `com.myPlugin.subproject`.

Excerpt from Square's herding elephants [article](https://developer.squareup.com/blog/herding-elephants/) on why this feature is important

> Eliminate cross-project configuration (think: allprojects and subprojects) so that every module (or "project", to use Gradle terminology) could be configured independently from every other. This should improve the configuration phase of the build, since those APIs defeat [configuration on demand](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand); and it also sets us up to be compatible with a new experimental Gradle feature known as [project isolation](https://gradle.github.io/configuration-cache/), which holds the promise of making slow Android Studio syncs a thing of the past.

Even though Project Isolation is experimental (and in most cases, not yet practical) - it's important that Gradle plugins (like Kover) design with Project Isolation in mind. For example, having separate plugins and only using `allprojects/subprojects { }` (if you must) in a dedicated `.aggregator` plugin. That way, when Gradle releases APIs to avoid the `allprojects/subprojects { }` APIs, the migration is trivial.

note: I'd definitely recommend reaching out to the Gradle team to see what they recommend here

**Comment by shanshin** [comment]
Relates #19

**Comment by shanshin** [comment]
Resolved in `0.7.0-Alpha`
