### ISSUE TITLE
Wrong coverage on DefaultImpls branch and instruction

### ISSUE THREAD

**Issue by LeoColman** [Kotlin/kotlinx-kover#149]
Hey guys!
I'm trying to use Kover on [simple-password-generator](https://github.com/LeoColman/simple-password-generator). I have an issue with the coverage (added as an attachment). Some bits of coverage is being reported as missing.

WordGenerator$DefaultImpls | 100%           (3/3) | 87.5%           (7/8) | 100%           (4/4) | 89.4%           (42/47)
-- | -- | -- | -- | --

[report.zip](https://github.com/Kotlin/kotlinx-kover/files/8191156/report.zip)

If you look at the code (and tests), you'll see that every scenario is covered. I tried to dig a bit of the bytecode generated under the hood, but was unsuccessful in finding these branches.

## Reproducing

I froze [this tag](https://github.com/LeoColman/simple-password-generator/releases/tag/kover-bug) in the repository. Cloning it and running `koverReport` should be enough to reproduce this result.

**Comment by shanshin** [comment]
Thanks for the report!

**Comment by LeoColman** [comment]
I'd love to work on this, but I don't have any pointer on where to start.
If you have ideas we can add them here :)

**Comment by shanshin** [comment]
@LeoColman, please check in `0.5.1`

**Comment by shanshin** [comment]
Must be fixed since 0.5.1, feel free to reopen if the problem reproduced again.

**Comment by LeoColman** [comment]
Sorry, I never saw your first message.
It's not fixed in 0.5.1, although the coverage report improved by a small amount.
![image](https://user-images.githubusercontent.com/1577251/186262238-9e6c3dcf-c77f-4f93-a307-c80bbc3e8927.png)

I cloned the same tag I froze in the first comment and upgraded kover to 0.5.1. After running tests again the result is still the same

**Comment by LeoColman** [comment]
Adding to that, I also tried with Kover 0.6.0 and the issue persists.

**Comment by LeoColman** [comment]
Hey @shanshin !
You're right. I reran locally and now it's 100% covered.
![image](https://user-images.githubusercontent.com/1577251/189179841-459c0090-edc7-43ae-805a-671d39676d20.png)


Thanks for all the support!
