### ISSUE TITLE
Incorrect gradle project analysis on multi-module projects when subprojects have the same name

### ISSUE THREAD

**Issue by ologe** [Kotlin/kotlinx-kover#151]
I'm playing with Kover (v0.5.0) these days and I noticed a weird behaviour on multi-module projects with a nested hierarchy. When there are submodules with the same name, Kover often analyses the wrong project.

Given the following project structure:
```
:feature
  :first
  :another-nesting
     :first
     :second
  :nested
     :first
     :second
```

`./gradlew :feature:first:koverHtmlReport` is analyzing `:feature:nested:first`

<img width="1040" alt="Screenshot 2022-03-11 at 11 53 00" src="https://user-images.githubusercontent.com/22067384/157853793-ee2917e4-697b-4f26-85d4-cb425dc3f9e4.png">

`./gradlew :feature:nested:first:koverHtmlReport` is correct

<img width="878" alt="Screenshot 2022-03-11 at 11 53 30" src="https://user-images.githubusercontent.com/22067384/157853818-1ae07935-bed8-4200-9a57-10446db1144f.png">

`./gradlew :feature:another-nesting:first:koverHtmlReport` is analyzing again `:feature:nested:first`

<img width="890" alt="Screenshot 2022-03-11 at 11 53 53" src="https://user-images.githubusercontent.com/22067384/157853935-03bbcf59-0796-4276-a61e-391f1261b793.png">

-----------------------

Zero configuration from my side, just applied the plugin. 

Downgraded to `v0.4.4` and everything works fine. 

Everything should be reproducible in this repo https://github.com/ologe/kover-testing

**Comment by shanshin** [comment]
Hi, 
currently, the plugin uses only a short project name.
We will take this issue into account when designing the new API.

**Comment by shanshin** [comment]
Relates #19

**Comment by charlesng** [comment]
@shanshin Is there any workaround or release plan for this fix? In my project we used multi module arch and it hurts a lot on the coverage report because of this 😢

**Comment by driver733** [comment]
> @shanshin Is there any workaround or release plan for this fix? In my project we used multi module arch and it hurts a lot on the coverage report because of this 😢  

It's probably related to the way Gradle works, that is, it treats different submodules with the same name as the same dependency. 

See https://github.com/gradle/gradle/issues/16885
