### ISSUE TITLE
Display Coverage % in Gitlab

### ISSUE THREAD

**Issue by ybentlili** [Kotlin/kotlinx-kover#155]
Hello 
I want to display the % of coverage in Gitlab. 
I can get it by 
`grep -Eo "[0-9]+([.][0-9]+)%" path/to/report//index.html | head -1`

But I don't know to display it in Gitlab as Coverage must be regular expression. 

Thanks

**Comment by sarn0ld** [comment]
In the script tag block of your job (Inside .gitlab-ci.yml) you can add one line after executing kover:
`- cat path/to/report/index.html`

Then you can add the regex in a coverage tag[coverage tag](https://docs.gitlab.com/ee/ci/yaml/#coverage)  for the same job.

**Comment by CLOVIS-AI** [comment]
Until Kover provides an easy integration, here is particularly fragile way of doing this:

```shell
cover=$(<<<build/reports/kover/project-xml/report.xml | tail -7 | head -5 | grep 'INSTRUCTION' | cut -d ' ' -f 3,4 | sed 's/missed="//;s/" covered="/*100\//;s/"\/>//' | bc)
echo "Coverage: $cover%"
```

A simple way for Kover to make all of this unnecessary would be to provide a Gradle task similar to this:
```shell
$ ./gradlew koverStats
Instruction: 12%
Branch: 32%
Line: 15%
Method: 35%
Class: 80%
```
This command would also be useful for CLI users.

**Comment by zerotacg** [comment]
I liked the idea of [CLOVIS-AI](https://github.com/CLOVIS-AI) and [integrated it as a gradle task](https://gist.github.com/zerotacg/a131d73bf3f85c5e0309762ac8bbdf06)

Still a bit hacky gradle task, maybe someone could improve on that

After that I'm using this gitlab coverage config
`
   coverage: '/Type: INSTRUCTION .*?([\d\.]+)%/'
`

**Comment by stepango** [comment]
In case anyone interested in a Kotlin version of gradle task above(https://github.com/Kotlin/kotlinx-kover/issues/229)

```kotlin
tasks.register("koverPrintMergedXmlCoverage") {
    val koverMergedXmlReport = tasks.named("koverMergedXmlReport")
    dependsOn(koverMergedXmlReport)
    doLast {
        //language=RegExp
        val regexp = """<counter type="INSTRUCTION" missed="(\d+)" covered="(\d+)"/>""".toRegex()
        koverMergedXmlReport.get().outputs.files.forEach { file ->
            // Read file by lines
            file.useLines { lines ->
                // Last line in file that matches regexp is the total coverage
                lines.last(regexp::containsMatchIn).let { line ->
                    // Found the match
                    regexp.find(line)?.let {
                        val missed = it.groupValues[1].toInt()
                        val covered = it.groupValues[2].toInt()
                        println("Total Code Coverage: ${covered * 100 / (missed + covered)}%")
                    }
                }
            }
        }
    }
}
```

**Comment by shanshin** [comment]
Duplicates #229
