### ISSUE TITLE
Kover exclude rules in Sonarqube scan

### ISSUE THREAD

**Issue by johnryM** [Kotlin/kotlinx-kover#156]
I'm using Kover in my Android Project to generate the xml report that's sent to my Sonarqube server.

I would like to exclude all Kotlin classes that are inside a "di" folder but my Kover exclude rules don't seem to work.

My package structure is

<img width="306" alt="Screenshot 2022-03-24 at 18 38 54" src="https://user-images.githubusercontent.com/9742449/159987751-c3bd9d88-8854-4f19-b2cf-eae26584fd20.png">

My merged report gradle config is 

```
// in root build.gradle

tasks.koverMergedXmlReport {
    enabled = true
    xmlReportFile.set(layout.buildDirectory.file("kover/xml/result.xml"))
    excludes = [
        "*.*Module.*",
        "*.di.*Module*",
        "*.di.*"
    ]
}

sonarqube {
    properties {
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.coverage.jacoco.xmlReportPaths", "$buildDir/kcover/xml/result.xml"


    }
}

project.tasks["sonarqube"].dependsOn "koverMergedXmlReport"
```
   When I run my sonarqube scan. The module files in the various DI folders are visible in the coverage report

<img width="853" alt="Screenshot 2022-03-24 at 18 49 46" src="https://user-images.githubusercontent.com/9742449/159989201-c700da35-a92e-4bcb-98da-0eb524b12d21.png">

Defining "sonar.exclusions property" in my build gradle file does solve this issue

```
   property("sonar.exclusions","**/di/*")
```

Is this the correct way of excluding files in the final sonarqube report or is possible to perform the same exclusions by just configuring the Kover merged reports?

**Comment by johnryM** [comment]
Thanks @shanshin for clarifying. Will there be plans to support full integration with analysis tools like Sonarqube?

**Comment by shanshin** [comment]
There are no short-term plans for integration with Sonarqube, but it will be added as soon as the plugin and the IntelliJ Coverage Engine are implemented to a stable state.

**Comment by johnryM** [comment]
@sarn0ld In the end we went with your solution. I didn't know it was the same process with Jacoco as well. Thanks for letting me know!

**Comment by shanshin** [comment]
Duplicates #268
