### ISSUE TITLE
Kover verify fails even though numbers in report are good

### ISSUE THREAD

**Issue by mskonovalov** [Kotlin/kotlinx-kover#157]
My report looks like that 

Package | Class, % | Method, % | Branch, % | Line, % | Instruction, %
-- | -- | -- | -- | -- | --
all classes | 92.6%           (918/991) | 91.2%           (1995/2188) | 65.5%           (4049/6180) | 92.2%           (8364/9071) | 81%           (75129/92794)

But for some reason 
```
tasks.koverMergedVerify {
    rule {
        name = "Minimal line coverage rate in percent"
        bound {
            minValue = 91
        }
    }
}
```
fails with the error
```
Execution failed for task ':koverMergedVerify'.
> Rule 'Minimal line coverage rate in percent' violated for 'katch': covered lines percentage is 66, but expected minimum is 91

```
TBH have no idea where this number 66 comes from 🤷

**Comment by mskonovalov** [comment]
Is there any additional logging I can enable?
Or is there a way to test with coverage.xml to see what values does it get?

**Comment by qwwdfsad** [comment]
@shanshin warning is indeed a good idea, PTAL
