### ISSUE TITLE
why would I need to use instrumentAndroidPackage = true

### ISSUE THREAD

**Issue by humazed** [Kotlin/kotlinx-kover#160]
As the title says, why would I need to use `instrumentAndroidPackage = true`? 

it's not clear from the docs what's the advantage of using this flag.

setting it to true causes #89 to happen.

so could you clarify if there is any use case for setting it to true, or it is expected to be always false?

**Comment by shanshin** [comment]
Hi,
in most cases, this flag should be `false`.
In very rare cases, it may be necessary to instrument classes from packages named `android.*` and `com.android.*`. For example, if the project has a class with the full name `android.my.foo.Bar`.

This flag is temporary and will be removed in upcoming releases when the instrumentation agent is improved.
