### ISSUE TITLE
Merged report doesn't show coverage for classes which were tested

### ISSUE THREAD

**Issue by koha26** [Kotlin/kotlinx-kover#161]
I am working on the Intellij IDEA plugin. I have the following setup for the project:

- Gradle: 6.9.2
- Kotlin: 1.5.32
- Java: 11
- Kotlinx-Kover: 0.5.0

If I run with debug tests directly from the IDEA, I can reach a breakpoint in the tested classes. However, if I run koverMergedHtmlReport either with Intellij agent or with Jacoco, reports will show 0% coverage by any metrics. But as a result, these tests are marked as PASSED. It means that tested classes should be touched in any case.  
![image](https://user-images.githubusercontent.com/15383640/162473103-1e036ca3-39b3-4c39-b95a-19da9ea87bbd.png)
![image](https://user-images.githubusercontent.com/15383640/162473313-7d21aa17-9656-4456-88d8-44528f822db9.png)
![image](https://user-images.githubusercontent.com/15383640/162473942-f58fb4cb-4817-4066-bd4d-961b8d5ae882.png)

Do you have any ideas why it is possible?

**Comment by shanshin** [comment]
Hi,
which git branch are you building?
I'm trying to reproduce issue locally.

**Comment by koha26** [comment]
Hi @shanshin, thank you for the quick response. 
I pushed the latest changes to the branch: https://github.com/aemtools/aemtools/tree/182_feature. 
Let me know if you need more info.

**Comment by shanshin** [comment]
Which command do you run Gradle tasks with?
`./gradlew clean build` crashes with an error locally

**Comment by koha26** [comment]
@shanshin , try to run  `./gradlew clean koverMergedHtmlReport`.

**Comment by shanshin** [comment]
Locally, when I run the command `./gradlew clean :aem-intellij-core:test --tests "com.aemtools.completion.clientlib.ClientlibCssTxtCompletionTest" koverMergedHtmlReport -x :aem-intellij-index:test  -x :aem-intellij-lang:test`, I get full coverage of the class `CdCompletionContributor`.

Also, try to build without using the build cache (by adding the ` --no-build-cache` option).

Write if building without caches doesn't help.

**Comment by koha26** [comment]
Thank you for the suggestion, @shanshin. I tried to run `./gradlew clean clean koverMergedHtmlReport --no-build-cache`, but it didn't help. The coverage for mostly all packages under `com.aemtools.completion` package is zero.
However, if I run your command, I can see 100% coverage for `CdCompletionContributor`. 

Therefore, I suggested that there is an issue with some dependencies between modules. I have `testCompileOnly(project(":aem-intellij-core"))` dependency in 2 modules and I thought that it could impact especially during test step. I moved some classes to avoid this dependency declaration, run build and here we go again - 0.00% for this class and mostly all sub-packages of  `com.aemtools.completion`.

It seems that the agent in runtime does not use the classes that I have in the classpath, but I might be wrong. It is strange because there are similar tests in the same module and they have some coverage. 

By the way, let me provide some of my tries with this project and code coverage. Firstly, I tried to use Jacoco, but it shows less than 50% coverage for the whole project. Then I found Kover and introduced it to the project and coverage was increased to 50-51%. Long days of trying to find the cause, I decided to just play around with the versions of Kotlin and Gradle. I downgraded them: Kotlin `1.6.10 -> 1.5.32`, Gradle `7.3 -> 6.9.2`. As a result, my project coverage was increased to 66%. However, I know that it should be around 80% (+-5%) on old versions on Kotlin and Gradle and with Java 1.8.

**Comment by shanshin** [comment]
Unfortunately, I was unable to execute the ff command `./gradlew clean koverMergedHtmlReport --no-build-cache` due to errors. I excluded problematic tests, but in this case the coverage turned out to be complete (

Errors:
```
HtlPatternsTest > testHtlAttributeMain FAILED
    junit.framework.AssertionFailedError at HtlPatternsTest.kt:368
...
HtlPatternsTest > testDataSlyUseNoElMain FAILED
    junit.framework.AssertionFailedError at HtlPatternsTest.kt:368

HtlPatternsTest > testMainVariableInsideOfDataSlyRepeat STANDARD_ERROR
```

**Comment by koha26** [comment]
Hi @shanshin, I am with good news. I disabled some problematic tests and run `./gradlew clean koverMergedHtmlReport`. As a result, I got 84.5% line coverage. 
![image](https://user-images.githubusercontent.com/15383640/163165429-ab250cb3-7391-46e7-bd38-647bf330298c.png)

Thank you for your help and time. To be honest, I am sorry that I wasted your time, but a collective mind was required to solve this issue.

Please, close this issue. Have a good day!
