### ISSUE TITLE
kotlinx.kover.api.KoverTaskExtension#getExcludes does not exclude classes and functions from the report

### ISSUE THREAD

**Issue by yuriykulikov** [Kotlin/kotlinx-kover#162]
## Summary
Excluding packages, functions or classes using `excludes`, disables instrumentation for these classes, but they are still displayed in the report and therefore still reduce overall code coverage.

### given
In root project:
```
plugins {
  id("org.jetbrains.kotlinx.kover") version "0.5.0"
}
```
in subproject:
```
tasks.test {
  extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
    excludes =
        listOf(
            "**.xml.*",
        )
  }
}
```

### when
`./gradlew koverReport`

### then
Excluded packages are listed in the report with 0 coverage, thereby reducing overall code coverage.

### expected
Excluded packages are completely removed from the report and do not count towards overall code coverage.

**Comment by yuriykulikov** [comment]
May be related to https://github.com/Kotlin/kotlinx-kover/issues/156, https://github.com/Kotlin/kotlinx-kover/issues/153

**Comment by shanshin** [comment]
Hi,
in the current version of the API, the filter for instrumentation and the filter for reports are configuring in different places.
In your example, you excluded a class from instrumentation - in this case, coverage for such a class will always be 0 in the report.

To exclude a class from a report (for example, from an HTML report), you just need to add an exclusion rule to the report generation task:
```
tasks.koverHtmlReport {
    excludes = listOf("**.xml.*")
}
```

In the upcoming releases, the API will be redesigned and it will be enough to specify the filter only in one place.

**Comment by bitspittle** [comment]
Thanks for filing this bug. I had the same confusion and this helped me get on the right path again.

As of right now, it seems like the right way to do this is:

```
kover {
    filters {
        classes {
            excludes += "**.xml.*"
        }
    }
}
```
