### ISSUE TITLE
Gradle 'check' task runs tests from all project, despite no verification rules are added.

### ISSUE THREAD

**Issue by varjasz** [Kotlin/kotlinx-kover#168]
In a gradle multi project running a subproject 'check' task trigger all tests from all projects.
No verification rules are added to 'koverVerify' task.

The documentation said:
_"if verification rules are added, then running tasks koverVerify or check will trigger the execution of all active tests from all projects!"_

If no verification rules are added, then the 'koverVerify' task will be disabled (skipped), but it depends on all tests and 'check' task depends on 'koverVerify', so despite the 'koverVerify' is skipped it forces gradle to run all tests from all projects.

**Comment by shanshin** [comment]
Hi,
by default `koverVerify` task depends only on test tasks of it's project. If the task was started with a command like `:subproject:check` or `:subproject:koverVerify` then only the test tasks of the project `subproject` will be triggered.

This behavior can be changed only if you configure the Kover accordingly: it is enough to set the value for the flag `runAllTestsForProjectTask` to `true`, eg
```
kover {
    // other settings
    runAllTestsForProjectTask = true
}
```

To better understand your issue, could you clarify the version of the plugin, the structure of the project and which command you run the checks with.

**Comment by varjasz** [comment]
I have created a sample project:
[https://github.com/varjasz/kover-issue](https://github.com/varjasz/kover-issue)

The Kover documentation contains the following:

_By default, for the task koverVerify coverage is calculated only for the tests of the one project. If classes or functions are called from tests of another module, then you need to set a flag runAllTestsForProjectTask for KoverExtension to true (see)._

_**In this case, `if verification rules are added`, then running tasks koverVerify or check will trigger the execution of all active tests from all projects!**_

The project configured with:
```
kover {
    runAllTestsForProjectTask = true
}
tasks.koverVerify {
    // No rules added
}
```

The expected behavior would be:
* `gradlew proj1:check` run only that subproject tests: `proj1:test`
* `gradlew proj1:koverReport` run all tests in all projects: `proj1:test, proj2:test`
