### ISSUE TITLE
Kover not showing code coverage for all modules While running it for mult-module kotlin application

### ISSUE THREAD

**Issue by 93shubh** [Kotlin/kotlinx-kover#173]
[](url)Added the plugin to build.gradle.kts

id("org.jetbrains.kotlinx.kover") version "0.5.0"

and no where else.

Build is running fine but kover is not covering all the modules. Some of the services and modules are touchless and nowhere in report.

Also the test report of specific module doesn't show its code coverage.

I ran it for a sample project with 2 modules

Attaching screenshot of test report of a module and combined code coverage report

<img width="1439" alt="Screenshot 2022-05-02 at 4 35 50 PM" src="https://user-images.githubusercontent.com/102577594/166224541-b5f174f0-f4f2-4814-bf62-7b0f0fd04ea1.png">
<img width="897" alt="Screenshot 2022-05-02 at 4 35 55 PM" src="https://user-images.githubusercontent.com/102577594/166224550-e877ca39-5ebd-4f35-8b4c-2b4c122a5e3c.png">

**Comment by swissonid** [comment]
I have the same issue with our Android project with 70 modules. What is strange is that I saw that only the pure kotlin modules got ignored.

**Comment by shanshin** [comment]
Hi,
@93shubh, if you are looking at a report for a specific project (generated by the `koverHtmlReport` task), then only the coverage from the tests of this project gets into such reports. 
To reduce the build speed, cross-project tests are not taken into account by default in the `koverHtmlReport` and `koverXmlReport` tasks.
You can try to enable coverage measurement between all modules by adding such a configuration to the `build.gradle.kts` file
```
kover {
    runAllTestsForProjectTask = true
}
```

**Comment by shanshin** [comment]
Duplicates #96
