### ISSUE TITLE
Null-safe calls marked as partially uncovered

### ISSUE THREAD

**Issue by markslater** [Kotlin/kotlinx-kover#182]
Expressions using the null-safe call operator, `?.` are marked as having an uncovered branch.

For example, given a class:
```kotlin
class Example {
    fun nullableToString(value: Any?) = value?.toString() ?: "null"
}
```
and a test:
```kotlin
internal class ExampleTest {
    @Test
    fun `Handles non-null value`() {
        assertEquals(Example().nullableToString("Foo"), "Foo")
    }

    @Test
    fun `Handles null value`() {
        assertEquals(Example().nullableToString(null), "null")
    }
}
```
Kover marks the `nullableToString` function as having 75% branch coverage.

I suspect that the uncovered branch is the case that `value` is not null, but its `toString` method returns null.  However, the compiler guarantees that this scenario will not occur because the return type of `Any.toString()` is (non-nullable) `String`.

The function can be rewritten to achieve full coverage as follows:
```kotlin
fun nullableToString(value: Any?) = if (value != null) value.toString() else "null"
```
However, this is non-idiomatic, harder to read, and also Intellij IDEA keeps wanting to change it back to the original form :-P

Reproducer [here](https://github.com/markslater/kover-examples/tree/81a718217cc04151f77610f9b6caabb5788bd595)

**Comment by qwwdfsad** [comment]
This is an interesting issue!

While it may look like these two methods are identical, semantically they are not -- **if** `toString` returns `null`, `"null"` is expected in the first method.

>However, the compiler guarantees that this scenario will not occur because the return type of Any.toString() is (non-nullable) String

I'll look into that, but I suppose that `null` may slip in via Java interop in case of improper implementation

**Comment by shanshin** [comment]
Hi,
unfortunately, at the moment, when generating reports, this is practically an unsolvable issue, because the coverage agent sees the byte code, but it cannot fully analyze the source code, because the Kotlin compiler always generates a third branch for case of incorrect implementation `toString()`

**Comment by markslater** [comment]
Thanks for the rapid response!

> I suppose that null may slip in via Java interop in case of improper implementation

FWIW, this also affects pure Kotlin, e.g.
```kotlin
class Example {
    class Foo {
        fun bar() = "Foo"
    }

    fun nullableBar(value: Foo?) = value?.bar() ?: "null"
}
```
I suppose the compiler produces the same bytecode for null-safe calls to pure Kotlin operations and null-safe calls to operations that might have a Java implementation (perhaps it can't even distinguish between these).

**Comment by qwwdfsad** [comment]
Thanks!

We've discussed it internally and it's actually an opportunity for compiler to get better: https://youtrack.jetbrains.com/issue/KT-52472/

Closing as "Won't fix", will be fixed in Kotlin itself
