### ISSUE TITLE
Kover not working with Micronaut Grpc

### ISSUE THREAD

**Issue by gb-vinicius-cunha** [Kotlin/kotlinx-kover#185]
I have a Micronaut GRPC service working fine with Jacoco plugin, but jacoco doesn't work well with suspend functions. 

To get a better coverage we try to change to Kover, but when we did this, build stop working.

I don't know why, but when we add Kover plugin, the build process use native Compile task and fails. This not happen without Kover plugin.

To reproduce this 
1. create a projeto with laucher https://micronaut.io/launch
2. choose grpc Application, Java 11, Kotlin, Gradle Kotlin and Junit
3. Add Kover plugin
4. Run build task

With Kover plugin the build ran 3 tasks more than without plugin

- generateResourcesConfigFile
- nativeCompile
- testNativeImage

I create this repo to reproduce
https://github.com/gb-vinicius-cunha/micronaut-kover-error

This doesn't happen on project without micronaut, so i understand that Kover plugin doesn't depends of nativeCompile task

**Comment by shanshin** [comment]
Hi,
Kover automatically adds instrumentation to all tasks with the type `org.gradle.api.tasks.testing.Test` (JVM tests) and runs these tests while verification.
It seems that in Micronaut native tests are run by a task with the type `Test`.
Therefore, to disable the instrumentation of the `testNativeImage` task, you can add the following code (example for `build.gradle.kts` file)
```
tasks.withType<Test> {
    if (name == "testNativeImage") {
        extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
            isDisabled = true
        }
    }
}
```

**Comment by gb-vinicius-cunha** [comment]
Hi, that's works perfectly! 

I'll add the fix to repo and leave there if anyone needed

Tks! ;)
