### ISSUE TITLE
excludes still doesn't work

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx-kover#186]
**build.gradle** (project)
```
plugins {
  id 'org.jetbrains.kotlinx.kover' version "0.5.0"
}
```

**build.gradle** (android module)
```
android {
      testOptions {
        unitTests.all {
            if (it.name == "testDebugUnitTest") {
                kover {
                    disabled = false
                    excludes = [
                            "*_*Factory.*",
                            "*_Factory.*",
                            "Hilt_*",
                            "*_Hilt*",
                    ]
                }
            } else if (it.name == "testReleaseUnitTest") {
                kover {
                    disabled = true
                }
            }
        }
    }
}
```

In the report (generated by `./gradlew clean koverHtmlReport`), no file is excluded: 
![image](https://user-images.githubusercontent.com/11870220/170934813-470ffa71-fead-4f9e-9632-778d5479f7a3.png)

**Comment by shanshin** [comment]
Hi,
in the current version of the API, the filter for instrumentation and the filter for reports are configuring in different places.
In your example, you excluded a class from instrumentation - in this case, coverage for such a class will always be 0 in the report.

To exclude a class from a report, you just need to add an exclusion rule to the report generation task:

```
tasks.koverHtmlReport {
    excludes = [
        "*_*Factory.*",
        "*_Factory.*",
        "Hilt_*",
        "*_Hilt*",
        ]
}
```
In the upcoming releases, the API will be redesigned and it will be enough to specify the filter only in one place.

Duplicate #162

**Comment by NinoDLC** [comment]
You can check my gradle files (and / or generate the report) here : https://github.com/NinoDLC/Pokedexino

**Comment by NinoDLC** [comment]
I was trying to use the `**` notation from JaCoCo to tell Kover to ignore intermediates packages, is it implemented in Kover too ?

**Comment by NinoDLC** [comment]
You mention fully-qualified class names, but is the type also somewhat considered ? I've got a weird behavior about that. 

If I use the rule ` "*_Impl"`, my `fr.delcey.pokedexino.data.AppDatabase_Impl` is *not* excluded. 
If I use the rule ` "*_Impl*"`, my `fr.delcey.pokedexino.data.AppDatabase_Impl` is excluded. 
If I use the rule ` "*_Impl.java"`, my `fr.delcey.pokedexino.data.AppDatabase_Impl` is *not* excluded. 
If I use the rule ` "*_Impl.*"`, my `fr.delcey.pokedexino.data.AppDatabase_Impl` is *not* excluded. 

Note that `AppDatabase_Impl` is a generated `.java` file. 
![image](https://user-images.githubusercontent.com/11870220/171405192-254d7c59-40ed-4b90-9eca-5c1106b52520.png)

**Comment by shanshin** [comment]
No, file name extensions are never part of a class name in Java or in Kotlin.

Most likely, you were confused by the fact that the rule `*_Impl` did not work.
Here the situation was complicated by the peculiarity of the JVM and the reporter. 

If a class contains a nested class or a lambda expression, then a class with the same name is created in the JVM, but `$smth` is added at the end.
If you open the `AppDatabase_Impl` class in the report, you will see that the coverage is shown inside only for the `AppDatabase_Impl$1` class (it looks like the class contained a lambda expression).

To completely eliminate such situations , you can add two rules
```
    "*_Impl",
    "*_Impl\$*"
```

**Comment by NinoDLC** [comment]
Very interesting! Thanks a lot for your time and explainations :)

Out of thoughts, shouldn't nested classes or lambda expressions be automatically excluded if their englobing classes are excluded ?

**Comment by shanshin** [comment]
This is an ambiguous issue.
Nested classes definitely cannot be excluded, but lambdas are very often difficult to distinguish from custom classes.
Therefore, at the moment, the exception via `"*name$*"` remains the most versatile and flexible way.

**Comment by NinoDLC** [comment]
For any future Googler (if any), here's my implementation. 

`build.gradle` (module) : 
```

def excludedFromCoverage = [
        "dagger.hilt.*",
        "hilt_aggregated_deps.*",
        "*_Factory",
        "*_Factory\$*",
        "*_*Factory",
        "*_*Factory\$*",
        "*.Hilt_*",
        "*_HiltModules",
        "*_HiltModules\$*",
        "*_Impl",
        "*_Impl\$*",
        "*.AppModule", // Your Hilt modules should be there if you don't want to test them
        "*.DataModule",
        "*.DomainModule",
]

...

android {
    testOptions {
        unitTests.all {
            if (it.name == "testReleaseUnitTest") {
                kover {
                    disabled = false
                    excludes = excludedFromCoverage
                }
            } else if (it.name == "testDebugUnitTest") {
                kover {
                    disabled = true // won't run unit tests twice (once in debug mode, another in release mode)
                }
            }
        }
    }
}

...

tasks.koverHtmlReport {
    excludes = excludedFromCoverage
}
```

PS: Current version is 0.5, it is likely that future versions will simplify the excluding of files.

**Comment by irgaly** [comment]
In my case, `excludes = listOf("*")` setting in unitTests and koverHtmlReport does not effect. (Kover 0.5.1)

I'll wait next release... 😢

**Comment by NinoDLC** [comment]
> In my case, `excludes = listOf("*")` setting in unitTests and koverHtmlReport does not effect. (Kover 0.5.1)
> 
> I'll wait next release... 😢

What are you trying to achieve ? With `*` you'd just exclude every single file from coverage, so why use Kover at all ?

**Comment by irgaly** [comment]
Sorry not enough explanation. I'd like to know whether Kover recognize the exclude options or not by setting `excludes = listOf("*")`. But the result has all classes, so I think the eclude options are not recognized.

---

Today, I try again, then the excludes option works correctly 👍 

I already discarded commit log of https://github.com/Kotlin/kotlinx-kover/issues/186#issuecomment-1157688405, so I can't discover what my mistake was. sorry...

This is working configuration in my project:

`build.gradle.kts`

```
plugins {
...
    id("org.jetbrains.kotlinx.kover") version "0.5.1"
}
...
android {
    ...
    testOptions {
        unitTests.all {
            it.configure<KoverTaskExtension> {
                isDisabled = !it.name.contains("Debug")  // only executes test for debug build type
                excludes = listOf("*") // "*" ignores all classes, so it results empty report.
            }
        }
    }
}

tasks.koverHtmlReport {
    excludes = listOf("*") // "*" ignores all classes, so it results empty report.
}
```

**Comment by tugceaktepe** [comment]
> Hi, in the current version of the API, the filter for instrumentation and the filter for reports are configuring in different places. In your example, you excluded a class from instrumentation - in this case, coverage for such a class will always be 0 in the report.
> 
> To exclude a class from a report, you just need to add an exclusion rule to the report generation task:
> 
> ```
> tasks.koverHtmlReport {
>     excludes = [
>         "*_*Factory.*",
>         "*_Factory.*",
>         "Hilt_*",
>         "*_Hilt*",
>         ]
> }
> ```
> 
> In the upcoming releases, the API will be redesigned and it will be enough to specify the filter only in one place.
> 
> Duplicates #162

Hi @shanshin ,
As you said that I understood, when we add an exclusion for a class or package, we exclude only from instrumentation, The classes that we excluded, they continues to stay on the coverage report but they have zero coverage rate.
Did I understand correctly ? 

Thank you.

**Comment by shanshin** [comment]
@tugceaktepe, hi,
the API has been redesigned in the latest version. For which version is your question relevant?

**Comment by tugceaktepe** [comment]
Hi @shanshin 
I mean version 0.6.0.
