### ISSUE TITLE
Kover doesn't follow the configured "testBuildType" for an android project.

### ISSUE THREAD

**Issue by gerardoepitacio** [Kotlin/kotlinx-kover#187]
Having the example project in the branch `multiple_android_flavor`

https://github.com/gerardoepitacio/KoverTest/tree/feature/multiple_android_flavor

when I try to execute the task:

```
./gradlew :app:koverHtmlReport
```

throws the following error

```
> Task :app:compileAppQaUnitTestKotlin FAILED
e: /Users/ge/dev-test/KoverTest/app/src/test/java/com/example/koverfail04/RemoteDataProviderImplTest.kt: (8, 50): Unresolved reference: RemoteDataProviderBuilder
```

This is because, Kover tries to build the build type "qa", which can't reach the resource of the build type "development"

even though  "testBuildType" was correctly configured in `android {... } ` to explicitly run my test for the development build type.

Additional information about changing the test build type 

Change the test build type
https://developer.android.com/studio/build/gradle-tips#change-the-test-build-type

Expected behavior, one of the following scenarios might be good to follow.
- Kover should be able to follow the configured testBuildType, and compile only the required resources to run the tests in the configured build type.
- Kover should generate different tasks for every build type and product flavor, to be able to generate reports for specific build type and product flavor (more recommended.).

**Comment by shanshin** [comment]
Relates #78

**Comment by Gerardoeg** [comment]
There is a way to help to support the expected behavior for this Issue?.

@shanshin

**Comment by gerardoeg** [comment]
@shanshin  hi!, really thanks to support multiple flavors and build types, it might be a way to specify the preferred build type and flavor?, currently I'm having more than 6 flavors, and i'm end up having a lot of tasks for Kover.

Not having so much issues with the tasks, I'm just concerned if this tasks makes my sync on project a little bit slow.
![image](https://github.com/user-attachments/assets/444f9d49-0b7f-4f91-9487-2348955b141e)
