### ISSUE TITLE
Is it possible to use JaCoCo and Kover on the same Android project ?

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx-kover#188]
At the moment, Kover is better for code coverage about Kotlin.   
At the moment, JaCoCo is better for code coverage about Android. (source : https://github.com/Kotlin/kotlinx-kover/issues/96)

So, why not use both until Kover can handle Android Instrumented tests well ?

This [article](https://medium.com/android-news/unified-code-coverage-reports-for-both-unit-and-ui-tests-e7c954a4e8ac) makes it clear JaCoCo can handle both `exec` and `ec` files, so I'd imagine kover generating the code coverage for unit tests and JaCoCo generating the code coverage for Android instrumented tests and merging them ?

Sadly, my Gradle skills are abysmal (and I'm not interested at all tbh) so I don't know if that's even possible, in the interim.

**Comment by shanshin** [comment]
Hi,
unfortunately, apart from the format of the binary report files themselves (`exec` for JaCoCo and `ic` for IntelliJ), the files differ in their contents.
`ic` contains more information about Kotlin classes, so it is possible to generate a coverage report more correctly.

Therefore, reading the exec file will not give the IntelliJ reporter all the necessary information, and the development time can be comparable to the time of adding support for instrumentation of Android devices.
