### ISSUE TITLE
Design stable API

### ISSUE THREAD

**Issue by shanshin** [Kotlin/kotlinx-kover#19]
In version `0.2.2` all configuration takes place in the Kover extension of the test task.
It is necessary to discuss the design and make a decision to leave this method of configuration or to take the generation of the report and verification into separate tasks.

If the tasks will be separated, it should consider the option of creating your own tasks of report generation or verification and connecting them to arbitrary tasks.

Another feature when dividing tasks is the creation of one report (or verification) for several test tasks that are run simultaneously.

**Comment by sschuberth** [comment]
Some things to consider IMO include:
- Just applying the plugin should not already make all tests tasks generate coverage data. Users might still want to run their tests without coverage, for performance or other reasons. Instead, the plugin should automatically create "*WithCoverage" (or so) tasks for all tasks of type [Test](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html).
- As a result of the above, it should be possible to independently run different types of tests (source sets) with coverage. For example, if besides the standard `test` source set a custom `integTest` source set is defined for integration tests, then it should be possible to only run integration tests with coverage, but not the standard / unit tests (also see #54).

**Comment by OliverO2** [comment]
As far as I am aware, discussions cover the use case of excluding test classes beyond what is excluded by default (the `test` source set).

I'd like to see the opposite configuration option: Make it possible to _include_ the `test` source set in the coverage analysis. I would use test code coverage to check if there is any kind of obsolete or questionable test code around.
