### ISSUE TITLE
Differing report information when run on different environments

### ISSUE THREAD

**Issue by mformetal** [Kotlin/kotlinx-kover#191]
I'm using `kover` to generate a merged-report for a project. To alleviate the issues around Android and its many flavors, I have a Task that'll run all the tests we want and I configure it like:

```
tasks.withType<KoverMergedTask> {
    // We want this task to depend on our custom testAll task
    this.dependsOn.clear()
    dependsOn(tasks.withType<TestAll>())
}
```

This of course runs the configured tests and generates a report file.

I expect this report file to look the same no matter where it's run but that seems like that's not the case - if I run it locally versus on my CI server (gitlab), it generates different report information. Note that this is on the same git SHA, so there are no code differences as far as I can tell.

Full plugin configuration is as follows:

```
apply<KoverPlugin>() // version is 0.5.1

extensions.configure<KoverExtension> {
    jacocoEngineVersion.set(rootProject.versionFromCatalog("jacoco")) // version is 0.8.7
}

tasks.register<TestAll>(TestAll.NAME)

tasks.withType<KoverMergedTask> {
    // We want this task to depend on our custom testAll task
    this.dependsOn.clear()
    dependsOn(tasks.withType<TestAll>())
}

tasks.register<CommitCodeCoverage>(CommitCodeCoverage.NAME)

tasks.register<CompareCodeCoverage>(CompareCodeCoverage.NAME)

tasks.register<Exec>("getCoverage") {
    dependsOn(tasks.withType<KoverMergedTask>())

    group = "Reporting"
    commandLine(listOf("open", "${project.buildDir.path}/reports/kover/html/index.html"))
}

rootProject.subprojects {
    tasks.withType<Test> {
        extensions.configure<KoverTaskExtension> {
            excludes = listOf(
                "**/databinding/**/*.*",
                "**/android/databinding/*Binding.*",
                "**/R.*",
                "**/R$*.*",
                "**/BuildConfig.*",
                "**/Manifest*.*",
                "**/*Fragment*.*",
                "**/*Module*.*"
            )
        }

        reports {
            useJUnit()
            junitXml.required.set(true)
        }

        testLogging {
            exceptionFormat = TestExceptionFormat.FULL
            events.addAll(setOf(TestLogEvent.SKIPPED, TestLogEvent.PASSED, TestLogEvent.FAILED))
            showStandardStreams = true
            showStandardStreams = true
            showCauses = true
        }
    }
}
```

More than happy to provide any additional information you may need!

**Comment by shanshin** [comment]
Hi,
without an example of a specific project, it is difficult to answer unequivocally, but you should understand that manual dependency management for `KoverMergedTask` is unacceptable and can lead to unstable results.
In addition to dependencies on test tasks `KoverMergedTask`, output of this tasks are also used. List of this tasks is determined at the configuration stage and saved in special property. 

This list does not change when the `dependsOn` is changed, as a result, which binary reports will be used to get XML/HTML reports will be decided randomly.

**Comment by mformetal** [comment]
Understood - I'll change up my implementation then. Thanks!
