### ISSUE TITLE
Is there a way to make kover to create a coverage report based only on existing coverage data?

### ISSUE THREAD

**Issue by raghav-deepsource** [Kotlin/kotlinx-kover#192]
When I iterate on my code, I find myself making some changes, running specific tests, then checkign coverage by generating a jacoco html report with the data from the executed tests alone. 

When I installed kover, I added the following to my build script:

```kotlin
tasks.test {
    extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
        isDisabled = false
        binaryReportFile.set(file("$buildDir/coverage.bin"))
    }
}
```

If I understand correctly, this code is what makes the test task implicitly run when a task such as koverHtmlReport is run. 

I would like to disable this behavior, and instead allow kover to use only what coverage it finds. If there is no coverage binary created, I expect there to be no coverage reported. If coverage was generated only for a few methods of a few classes, I expect there to be correct coverage data for those methods/classes alone, anything else can be garbage data as far as I am concerned.

This is possible in JaCoCo, as I can simply run the jacocoTestReport task independently. Is this also possible with Kover, and if so, is there some documentation on it? if not, please consider supporting this use case, as it is helpful when one does not want to waste time waiting for many time consuming tests to run when they only want to test a portion of functionality.

**Comment by shanshin** [comment]
Hi,

> If I understand correctly, this code is what makes the test task implicitly run when a task such as koverHtmlReport is run.

not really. If you have used the plugin, then all tasks with the `org.gradle.api.tasks.testing.Test` type will be executed when running `koverHtmlReport`.

> I would like to disable this behavior, and instead allow kover to use only what coverage it finds.  

For your example you may write
```
tasks.test {
    extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
        isDisabled = true
        binaryReportFile.set(file("$buildDir/coverage.bin"))
    }
}
```
in this case, when running `koverHtmlReport`, the `test` task will not be triggered.

>  it is helpful when one does not want to waste time waiting for many time consuming tests to run when they only want to test a portion of functionality

You may also disable unnecessary tests when running Gradle (if there are not very many of them).
 e.g. `./gradlew koverHtmlReport -x :test`

**Comment by raghav-deepsource** [comment]
ok, so excluding the test task with the `-x` option will prevent automatically running tests?

**Comment by shanshin** [comment]
`-x` [disables](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line) the task execution in Gradle.
The Kover ignores disabled tasks in its turn and does not expect binary report files from them.

**Comment by raghav-deepsource** [comment]
Consider if I first ran  the test task, which would run all tests and (i think) will also generate a coverage data file.
If I then, separately, ran `./gradlew koverHtmlReport -x test`, would the coverage data for all the tests be ignored?

**Comment by shanshin** [comment]
> If I then, separately, ran ./gradlew koverHtmlReport -x test, would the coverage data for all the tests be ignored?

No, coverage data for all ignored tests won't be used in the report.

**Comment by shanshin** [comment]
You can use the build cache to avoid re-running tests that haven't changed. In this case, the binary reports will be taken from the cache, and only the modified tests will be run. 

See [Gradle docs](https://docs.gradle.org/current/userguide/build_cache.html)

**Comment by raghav-deepsource** [comment]
Good to know, I'll try that
