### ISSUE TITLE
JaCoCo Report Title

### ISSUE THREAD

**Issue by wakawaka54** [Kotlin/kotlinx-kover#194]
Great job so far on this! Working around JaCoCo + Kotlin has been a huge pain point for my team.

This is a relatively minor issue but it might be nice to be able to set the report title shown below. Right now its hardcoded to `project.path`, https://github.com/Kotlin/kotlinx-kover/blob/main/src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoReports.kt#L45

<img width="575" alt="image" src="https://user-images.githubusercontent.com/11714169/177478113-b163c89a-5430-4328-8b46-815622b5226d.png">

**Comment by shanshin** [comment]
Before adding custom report header to the API, we will need to implement it in the IntelliJ Coverage Engine.

**Comment by shanshin** [comment]
Relates [task](https://youtrack.jetbrains.com/issue/IDEA-301520)

**Comment by shanshin** [comment]
Resolved in `0.7.0-Alpha`
