### ISSUE TITLE
Kover not excluding 

### ISSUE THREAD

**Issue by adrianwitaszak** [Kotlin/kotlinx-kover#206]
Hi. In our KMM project for example in the shared module, I've got: 

```
// shared module

kover {
    htmlReport {
        filters {
            classes {
                excludes + listOf(
                    "**/BuildConfig.*",
                    "**/Greeting*.*",
                    "**/Platform*.*",
                    "**/*Test*.*",
                )
            }
        }
    }
}
```

And coverage report is:
![Screenshot 2022-08-16 at 14 48 14](https://user-images.githubusercontent.com/20965327/184895805-c4716aef-bbcc-4450-b191-e4131d40f90a.png)

Shouldn't be everything excluded except `CognICA`?

Actually right now it shows coverage of 0%, but I want it to be not included in the report

**Comment by shanshin** [comment]
Hi,
according to the [documentation](https://github.com/Kotlin/kotlinx-kover#configuring-jvm-test-task) 
```
Instrumentation inclusion/exclusion rules are represented as a fully-qualified name of the class (several classes if wildcards are used). File or directory names are not allowed. It is possible to use * (zero or several of any chars) and ? (one any char) wildcards. Wildcard ** is similar to the *.

Examples my.package.ClassName or my.*.*Name are allowed, while my/package/ClassName.kt or src/my.**.ClassName are not.
``` 

I think it's worth putting this in a separate section of the documentation.

**Comment by adrianwitaszak** [comment]
All work now. Thank you
