### ISSUE TITLE
KMM project merge reports

### ISSUE THREAD

**Issue by adrianwitaszak** [Kotlin/kotlinx-kover#207]
Kover generates the report for androidApp and shared modules. 

Is there a way for Kover to merge those two reports into one and locate it in the top-level build folder?

**Comment by shanshin** [comment]
Hi, 
if you are using version `0.5.1`, please read about [merged reports in the Kover](https://github.com/Kotlin/kotlinx-kover/tree/v0.5.1#configuring-merged-reports).

**Comment by shanshin** [comment]
For version `0.6.0-Beta` see [this section](https://github.com/Kotlin/kotlinx-kover/tree/main#cross-project-coverage).

**Comment by adrianwitaszak** [comment]
All works. Thanks
