### ISSUE TITLE
koverXmlReport task is not launched with check task when both verify and koverXmlReport are `onCheck.set(true)`

### ISSUE THREAD

**Issue by AleksDanil** [Kotlin/kotlinx-kover#209]
Simple project is configured like this:
```kotlin
plugins {
    kotlin("jvm") version "1.7.10"
    id("org.jetbrains.kotlinx.kover") version "0.6.0-Beta"
}

kover {
    xmlReport {
        onCheck.set(true)
    }

        verify {
            onCheck.set(true)
            rule { 
                isEnabled = true 
                name = null 
                target =
                    kotlinx.kover.api.VerificationTarget.ALL

                bound {
                    minValue = 10
                    maxValue = 20
                    counter =
                        kotlinx.kover.api.CounterType.LINE
                    valueType =
                        kotlinx.kover.api.VerificationValueType.COVERED_PERCENTAGE 
                }
            }
        }
    }
}
```

Run `check` task. koverXmlReport task is not launched, xml report is not generated.
With `onCheck.set(false)` for verify task is launched and report is generated.

No such issue for `htmlReport`. Also could not reproduce on 0.5.1 with similar setup.

**Comment by shanshin** [comment]
Hi,
I was unable to reproduce the problem locally, do you have a full reproducer project?
It was also useful to find out exactly what commands and in what sequence you run.

**Comment by AleksDanil** [comment]
It seems that it happens only when `verify` task fails, if it succeeds then xml report is created.
Also attaching the project
[beta-try.zip](https://github.com/Kotlin/kotlinx-kover/files/9358868/beta-try.zip)
