### ISSUE TITLE
Instructions count in verify task is different from the one displayed in report

### ISSUE THREAD

**Issue by AleksDanil** [Kotlin/kotlinx-kover#212]
0.6.0-Beta

You can check the attached simple project for reproduce.
Basically when I select instruction as counter in `verify` task numbers which I see in error differs from the html report.
For example in attached project report states branches coverage as `65.2% (30/46)` and from the verification errors I see that covered branches count is 20, and missed count is 12. Which also gives different percentage.
[CounterTypeIssue.zip](https://github.com/Kotlin/kotlinx-kover/files/9365578/CounterTypeIssue.zip)

**Comment by shanshin** [comment]
https://youtrack.jetbrains.com/issue/IDEA-300309/Incorrect-values-of-instruction-counter-in-the-verifier

**Comment by zuevmaxim** [comment]
Fixed in agent 1.0.680

**Comment by shanshin** [comment]
Fixed via f7f0d1c6ef8f8bc4b0096fd8a4275749d4e76f03
