### ISSUE TITLE
0.6.0 stable decreases coverage compared to beta

### ISSUE THREAD

**Issue by alvr** [Kotlin/kotlinx-kover#218]
The latest stable version decreases the coverage compared to beta. I have two PR with Codecov report:

- [Coverage in beta](https://github.com/alvr/katana/pull/147#issuecomment-1223062400)
- [Coverage in stable](https://github.com/alvr/katana/pull/150#issuecomment-1224788110)

In both PRs, the app is using v1.0.680 of IntelliJ Engine.

**Comment by shanshin** [comment]
Hi, thanks for the reproducer!
It looks like it's an issue in the IntelliJ reporter.
You exclude all nested classes (rule `"*$$*"`), but the reporter does not exclude code from lambda expressions from the report and considers them uncovered

![image](https://user-images.githubusercontent.com/7123498/186458172-9a526ec2-283c-4d7e-93c9-d9a546e1f665.png)
...
![image](https://user-images.githubusercontent.com/7123498/186457923-0eca3a77-ee42-44aa-adb4-03c70356cb6f.png)

**Comment by shanshin** [comment]
Please try latest `0.7.0-Beta' version.

Feel free to open new bug issue if the problem reproduced again.
