### ISSUE TITLE
Exclusion works with IntellijEngine but not with JacocoEngine

### ISSUE THREAD

**Issue by dprio** [Kotlin/kotlinx-kover#234]
Hello !

i've been trying to use Kover with JacocoEngine but for some reason the exclusions does not work when using JacocoEngine.

![image](https://user-images.githubusercontent.com/40172276/188631756-50a407cf-0554-4852-82ca-aa7f4079628f.png)

But, when I change for IntelliJEngine it works perfectly. Am I missing something ?

**Comment by shanshin** [comment]
Hi,
this issue will be fixed in the next release.

Duplicates #220
