### ISSUE TITLE
CLI for kover

### ISSUE THREAD

**Issue by Vacxe** [Kotlin/kotlinx-kover#238]
Does Kover have a CLI [similar with JaCoCo ](https://www.jacoco.org/jacoco/trunk/doc/cli.html) ?

I using JaCoCo to visualise coverage for UI tests. On `assemble` stage I preparing all `.class` files and then UI tests sharded with Marathon on two agents. As an aggregation I have `.class`s files and `.ec`s from devices. And then I can generate total coverage from those artifacts with CLI.

Is it possible to have the same functionality with this library?

**Comment by shanshin** [comment]
Hi,
at the moment there are no CLI tools in Kover

**Comment by shanshin** [comment]
Closed as a duplicate of #322
