### ISSUE TITLE
Could not find method koverHtmlReport() in 0.6.0

### ISSUE THREAD

**Issue by KarimFikani** [Kotlin/kotlinx-kover#239]
Hey, 

I started seeing this error when I tried to update to 0.6.0 from 0.5.0

`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method koverHtmlReport() for arguments [coverage_44w6hba0osvimoxq1ogzexdx2$_run_closure1$_closure2@22150f5d] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.`

It was working fine and I was able to generate html reports just fine. Not sure what I need to change to fix this error.

```
apply plugin: 'kover'

ext.generateCodeCoverageReport = { Project project ->
    // ignore appending module name for app
    def moduleName = ""
    if (project.name != "app") moduleName = ".${project.name}"

    // toString() forces org.codehaus.groovy.runtime.GStringImpl to be cast to java.lang.String
    def includeMainPackage = "${basePackageName}${moduleName}.*".toString()
    def includeList = [ includeMainPackage ]
    def excludeList = [
            "**.di.*", // exclude all classes under di folder
            "**.*_AssistedFactory_Impl", // auto-generated classes by hilt
            "**.*_Factory", // auto-generated classes by hilt
            "**.*_HiltModules*", // auto-generated classes by hilt
            "**.Hilt_*", // auto-generated classes by hilt
            "**.*_MembersInjector*", // auto-generated classes by hilt
            "**.*_Impl*", // auto-generated classes by hilt
            "**.*JsonAdapter", // auto-generated classes by moshi
            "**.BuildConfig",
            "**.*Constants", // exclude constants classes
    ]

    project.tasks.koverHtmlReport {
        kover {
            disabled = false
            includes = includeList
            excludes = excludeList
        }
    }

    project.tasks.koverXmlReport {
        kover {
            disabled = true
            includes = includeList
            excludes = excludeList
        }
    }
}

```

in the top gradle file I call generateCodeCoverageReport as such so I can set kover settings for every module. Not sure if this is the right way but it works...

```
task generateCodeCoverageReport {
    subprojects.forEach {
        generateCodeCoverageReport(it)
    }
}
```

**Comment by CLOVIS-AI** [comment]
Have you read through the [migration guide](https://github.com/Kotlin/kotlinx-kover/blob/main/docs/migration-to-0.6.0.md)? It helped me with a similar problem, but I'm not using the Groovy DSL so I'm not sure it's the same problem.

**Comment by shanshin** [comment]
Hi,
have you applied a plugin in a project where an error occurs?
One of the differences of the `0.6.0` version is that it is necessary to apply the Kover plugin in all projects that are used in single or merged reports.

If the plugin is exactly applied, but the error repeats, could you send a small reproducer project?

**Comment by shanshin** [comment]
Feel free to open new bug issue if the problem reproduced again.
