### ISSUE TITLE
Ability to measure coverage for another local project

### ISSUE THREAD

**Issue by CLOVIS-AI** [Kotlin/kotlinx-kover#241]
Let's image this structure a multi-project Gradle build with a `root` project, a project `a` and a project `b`. `b` has a `testImplementation(projects.a)` dependency.

I'd like to measure how much the tests of `b` cover the codebase of `a` (e.g. `:b:koverReport` should also include all classes from `a`). I thought this would be as simple as a rule inclusion:

```kotlin
// b/build.gradle.kts

plugins {
	kotlin("multiplatform")
	id("org.jetbrains.kotlinx.kover")
}

kotlin {
	jvm()

	sourceSets {
		val commonTest by getting {
			implementation(projects.a)
		}
	}
}

val jvmTest by tasks.getting {
	extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
		includes.add("myproject.a.*")
	}
}
```

However, when running `./gradlew b:koverReport`, the output only mentions the classes from project `b`.

How can I instrument the codebase from `a` from `b`'s tests?

> Use case: `a` and `b` implement an API with Ktor. `a` is the client, `b` is the server. All tests are ran using Ktor's test host, which allows to test both the server and the client from the same source set (`b`'s `jvmTest`). The client, `a`, doesn't have any tests since everything is already tested by the server's test. However I'd still like to know how much the client is covered.

**Comment by CLOVIS-AI** [comment]
Is it possible to have the regular global merged report + a different merged report with only two projects? I'd like the keep the global one.

**Comment by CLOVIS-AI** [comment]
Can a merged report include a sibling project?

Using the project organization
```
root/
  a/
  b/
  c/
```
I'd like to keep `root` as a merged report of everything (`root` + `a` + `b` + `c`) and also have a merged report that only has `a` and `b` (it it possible to set it up in `b`)?

**Comment by shanshin** [comment]
> I'd like to keep root as a merged report of everything (root + a + b + c) and also have a merged report that only has a and b (it it possible to set it up in b)?

Unfortunately, this will not be possible in the current implementation.

But you can create an intermediate project without the source code, which will contain `a` and `b`, and create merged reports there, e.g.
```
root/
    mid/
        a/
        b/
    c/
```


*This limitation will be removed in future releases, when adding projects isolation support.

**Comment by CLOVIS-AI** [comment]
Thanks, I'll do that then.
