### ISSUE TITLE
Submodules are missing in Merged reports

### ISSUE THREAD

**Issue by mustafaozhan** [Kotlin/kotlinx-kover#247]
Hello 👋 

Currently, coverage of the submodules are missing in the merged reports. I.e. in this project: https://github.com/Oztechan/CCC
the reports from below modules are missing:
- scopemob
- parsermob
- logmob
- basemob

They are all individual projects but added as git submodule into the project, so they are actually part of the project their reports should be also included in the merged report.

I checked the README.md but couldn't find any configuration about it, there is configuration for projects but only to exclude them, not for including.

**Comment by shanshin** [comment]
Hi,
when I try to build locally with this command `./gradlew koverMergedHtmlReport`, I get an error `No matching client found for package name 'mustafaozhan.github.com.mycurrencies'`.
Could you tell me how to build the project correctly?

**Comment by mustafaozhan** [comment]
@shanshin you shouldn't have this error any more can you re-clone the repo and try ?

**Comment by shanshin** [comment]
Thanks, now it builds successfully!
