### ISSUE TITLE
Add integration tests to the Kover project

### ISSUE THREAD

**Issue by shanshin** [Kotlin/kotlinx-kover#25]

**Comment by mirokolodii** [comment]
Definitely support this. IMO it's complicated to make jacoco to combine both unit and integration/UI tests coverage, I've never managed to make it to work. We should have simple way of enabling this.
As example, database related unit tests - these should be created as integration tests, as they should run on Android device (as recommended by Google).

**Comment by shanshin** [comment]
@mirokolodii, this task is for integration testing the code of the Kover plugin itself.

**Comment by mkolodii-pie** [comment]
@shanshin got it. Are you planning guys to enable support for integration tests coverage in Kover?
