### ISSUE TITLE
Multiline assertFailsWith marks as uncovered

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx-kover#251]
In 0.6.1 with `./gradlew koverMergedXmlReport` uploaded to codecov:

https://app.codecov.io/github/korlibs/korge/blob/31ceb8d90c8adf02931e410d385f704e513d56b4/kds/src/commonTest/kotlin/com/soywiz/kds/QueueTest.kt

![Screenshot 2022-10-04 at 18 24 25](https://user-images.githubusercontent.com/570848/193873343-8b4162b7-e18d-41ce-a62e-1460c203ee32.png)

Also I'm getting some strange partial here in the same file:

![Screenshot 2022-10-04 at 18 24 58](https://user-images.githubusercontent.com/570848/193873511-50e0f213-b672-480e-b07e-de3b8ee8819b.png)

**Comment by shanshin** [comment]
Hi,
at the moment, correct integration with codecov is not guaranteed.

Could you please show the HTML report? How different is it from codecov.

**Comment by soywiz** [comment]
@shanshin 

![Screenshot 2022-10-04 at 19 39 28](https://user-images.githubusercontent.com/570848/193888572-f29c5b30-3d2a-4054-9695-19a7f1a2eb3a.png)

**Comment by zuevmaxim** [comment]
`List.isNotEmpty` partial coverage is fixed in agent version `1.0.688`

As for `assertFailesWith`, this issue is caused by insufficient support of `@InlineOnly` functions in the coverage agent

**Comment by soywiz** [comment]
Nice! Confirmed that List.isNotEmpty thing is fixed:

![Screenshot 2022-11-22 at 12 00 48](https://user-images.githubusercontent.com/570848/203297744-bc4f6827-27a1-4ac9-a5d4-78ec3c0f9689.png)

**Comment by zuevmaxim** [comment]
Related issue about `InlineOnly` functions https://youtrack.jetbrains.com/issue/KT-55381

**Comment by shanshin** [comment]
Fixed since `0.8.0`
