### ISSUE TITLE
Unable to eclude subproject from merged report (Kotlin KMM)

### ISSUE THREAD

**Issue by nicolasfara** [Kotlin/kotlinx-kover#257]
Hi,
I'm trying to use Kover for a Kotlin KMM project. The project structure (currently) is the following:
```
':core'
':examples:example-01'
```
I want to exclude all the `:examples` subprojects from the merged report and I have configured the `build.gradle.kts` as follow:
```kotlin
plugins {
    // Other plugins
    id("org.jetbrains.kotlinx.kover") version "0.6.1"
}

kotlin {
    // Other configs
    koverMerged {
      enable()
      htmlReport {
          onCheck.set(true)
      }
      xmlReport {
          onCheck.set(true)
      }
      filters {
          projects {
              excludes += listOf(":examples:example-01") // Exclude from coverage the examples
          }
      }
   }
}
```
Running the task `./gradlew koverMergedReport` the following exception is raised:
```
Could not determine the dependencies of task ':core:koverMergedHtmlReport'.
> Kover configuring error: not found project ':examples:example-01' for merged tasks
```
I have also tried different strings like: `":examples"`, `"examples:example-01"`, etc. but any of these strings works.

**Comment by shanshin** [comment]
Hi,
may you clarify in which project you configured the merged report?

**Comment by nicolasfara** [comment]
Hi @shanshin,
the `build.gradle.kts` is belonging to the root project. Moreover, I've noticed that the `koverMerged` is inside the scope of `allprojects`. Moving out (at top level) `koverMerge` all the subprojects are correctly recognized by kover! Sorry for the noise. I close this issue :)
