### ISSUE TITLE
Explicit HTML report task

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx-kover#26]
It would be nice to have a separate HTML report task that can be invoked locally even if `generateHtml` is set to true.

Use-cases is quite simple -- when developing locally and observing verification failures, it's convenient to run `./gradlew:subproj:generateHtmlBlahBlahBlah` and see why exactly the build fails on CI _without_ changes in the buildscript itself.

The task should depend on the tests -- so `generateHtml` won't re-run all tests after local build failure due to verification rules, but will run them when running it from scratch

**Comment by shanshin** [comment]
Implemented in `0.4.0`
