### ISSUE TITLE
Some classes are not excluded when using an annotation filter

### ISSUE THREAD

**Issue by jfontsaballs** [Kotlin/kotlinx-kover#261]
**Describe the bug**
Some classes are not excluded when using an annotation filter.

**Expected behavior**
Class [`es.test.util.Event`](https://github.com/jfontsaballs/KoverAnnotationBugReproduction/blob/master/_llibreries/util/src/commonMain/kotlin/Event.kt) is not present in [HTML report](https://github.com/jfontsaballs/KoverAnnotationBugReproduction/blob/master/build/reports/kover/merged/html/ns-1/index.html).

**Reproducer**
https://github.com/jfontsaballs/KoverAnnotationBugReproduction

**Reports**
https://github.com/jfontsaballs/KoverAnnotationBugReproduction/blob/master/build/reports/kover/merged/html/ns-1/index.html 

**Environment**
Kover: 0.6.1
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3.1 (Oracle Corporation 17.0.3.1+2-LTS-6)
OS:           Windows 10 10.0 amd64
```
Please see reproducer for more info.

**Comment by shanshin** [comment]
Please try the new `0.7.0-Beta' version.

Feel free to open new bug issue if the problem reproduced again.
