### ISSUE TITLE
Kover doesn't create seperate task for different build type

### ISSUE THREAD

**Issue by syamantak-basu** [Kotlin/kotlinx-kover#264]
Currently Kover doesn't create different task for different build types. As a result unit test execution takes way longer than other tools like Jacoco. 
In one of the posts we saw this feature is expected in release 0.7 or 0.8.
Just wanted to confirm if this plan still holds good. If so, what is the expected release date for them ?

**Comment by shanshin** [comment]
Hi,
this feature is currently in development and is expected to be included in the next major release.
Unfortunately, it is difficult to name the exact date, it will depend on the complexity of the implementation.

**Comment by shanshin** [comment]
To track progress on this issue, please watch task #18
