### ISSUE TITLE
Code coverage at the package level w/ sub-packages merged

### ISSUE THREAD

**Issue by sakethram18** [Kotlin/kotlinx-kover#265]
Hello Kover team, I was wondering if there is a way to get the code coverage of a package at the root level meaning the classes included in that package and all the sub-packages included in it. Currently it gives a single list of all packages with parent packages and child packages as siblings. For eg:

Current state:
A.B
A.B.C
A.B.D
A.E

Required state:
A.B (this should contain coverage for direct classes and for packages A.B.C and A.B.D)
A.E

**Comment by shanshin** [comment]
Hi,
may you clarify, do you describe a situation when packages are displayed in a single list in an HTML report?

eg
![image](https://user-images.githubusercontent.com/7123498/198042864-e3bd092e-a167-43fb-8696-4bc328a3ea07.png)

**Comment by sakethram18** [comment]
@shanshin Yes that is correct. I'm looking to see if there is a way to publish the report such that org.jetbrains line item includes all the subpackages (org.jetbrains.bar).

**Comment by shanshin** [comment]
Unfortunately, at the moment this feature is not implemented.
We will add it when improving the report generator.

**Comment by shanshin** [comment]
Duplicates #272
