### ISSUE TITLE
Unable to resolve kover plugin

### ISSUE THREAD

**Issue by ashish12** [Kotlin/kotlinx-kover#269]
**Describe the bug**
Unable to resolve kover plugin during gradle build

**Errors**
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlinx:kover:0.6.1.
     Required by:
         project : > org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin:0.6.1
      > Could not resolve org.jetbrains.kotlinx:kover:0.6.1.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlinx/kover/0.6.1/kover-0.6.1.module'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kover/0.6.1/kover-0.6.1.module'.
 

**Expected behavior**
This seems to be related to bintray shutdown, and receiving 403 while trying to resolve kover plugin.

Even the curl request fails:
```
curl 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kover/0.6.1/kover-0.6.1.module' \
  -H 'authority: jcenter.bintray.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'cache-control: max-age=0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  --compressed

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: [e.g. 0.6.1]
 - Gradle version: [e.g. 7.5.1]
 - Kotlin project type: [e.g. Kotlin/JVM, Kotlin/Multiplatform, Kotlin/Android]
 - Coverage Engine version (if customized in build script): [e.g. DefaultJacocoEngine, KoverEngine("1.0.656")]
 - Other context important for this bug: [e.g. OS version]

**Comment by MGaetan89** [comment]
Kover is available on Maven Central, as shown [here](https://github.com/Kotlin/kotlinx-kover#apply-plugin).
Can you check that you have `mavenCentral()` is your list of repositories?

**Comment by ashish12** [comment]
Is there a plan to make it work with the plugins DSL, or we should be using the buildscript block only?

**Comment by hanqyu** [comment]
It seems that jcenter has been downed. 

https://statusgator.com/services/bintray

**Comment by MGaetan89** [comment]
It should work with the plugin DSL too

**Comment by shanshin** [comment]
Hi,
unfortunately, without a project, it's hard to say exactly what the problem is. May you show the project or at least the contents of the `settings.gradle` file?

However, the Kover plugin supports plugin DSL and it is placed in the `mavenCentral` repository. Perhaps your project uses plugins only from the Gradle portal and from the bintray.

**Comment by ashish12** [comment]
Looks to be working now with no change.
