### ISSUE TITLE
Jetpack Compose Preview annotation does not get excluded

### ISSUE THREAD

**Issue by johnryM** [Kotlin/kotlinx-kover#270]
**Describe the bug**
Adding the Jetpack Compose `@Preview` annotation to the Kover exclusion list does not work and Composable functions with this annotation show as not tested in the merged HTML reports.

A work-around is to define a custom annotation, add it to Kover exclusion list and add that to the Preview Composable function. E.g.
```
annotation class Exclude()
```
```
@Exclude
@Preview
@Composable
fun MyPreview(){
    // composable
}
```

**Expected behavior**
Functions with `@Preview` annotation should be ignored in the report tasks if defined in the Kover  annotation exclusion list

**Reproducer**
I have cloned the Kover Android Sample project here: https://github.com/johnryM/kover-annotation-issue-sample and have added an annotation exclude list in the android app root[ build.gradle.kts ](https://github.com/johnryM/kover-annotation-issue-sample/blob/530186c49c9e6d10ca309c2678ac153394fef685/examples/android_kts/build.gradle.kts#L48)file. 
**Note**: I am using Paparazzi to [snapshot test](https://github.com/johnryM/kover-annotation-issue-sample/blob/main/examples/android_kts/my-library/src/test/java/org/jetbrains/my_library/ExampleUnitTest.kt) my Composable which adds code coverage to Composable.

**Reports**
<img width="477" alt="Screenshot 2022-10-31 at 19 01 00" src="https://user-images.githubusercontent.com/9742449/199093188-8d831022-5aa2-472d-bde2-f35d9ca675bd.png">

**Environment**
 - Kover Gradle Plugin version:  0.6.1
 - Gradle version: 7.3.3
 - Kotlin project type: Kotlin/Android
 - Coverage Engine version: default
 - Other context important for this bug: Jetpack Compose, Annotations, exclusions

**Comment by shanshin** [comment]
Kover filters only by annotations for which `AnnotationRetention ` is `BINARY` or `RUNTIME`.
In the Compose `1.2.1` used in the example, the annotation `Preview` was `Retention(SOURCE)`, therefore, filtering did not work.

Starting with the `1.3.0` library version, the annotation has become `BINARY` and filtering should start working.

**Comment by nuhkoca** [comment]
Doesn't work for me

> TaxSnapShot_Generated > [path.to.TaxInformationScreenViewPreview] > GIVEN preview THEN snapshot[path.to.presentation.information.TaxInformationScreenViewPreview] FAILED
>    java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
