### ISSUE TITLE
Kover causing all flavors/build-type combinations to run

### ISSUE THREAD

**Issue by samuelneff** [Kotlin/kotlinx-kover#273]
**Describe the bug**

Builds with Kover and multiple flavors/build-types cause all tasks for all flavor/build-types to be run even when the test task specifies a specific combination.

Here's a sample project with `debug`/`release` build types and `sweet`/`salty` flavors. Otherwise it's exactly as it comes out of Android Studio's New Project command, with Kover added to the build.

https://github.com/samuelneff/kover-build-explosion

### Without Kover

Output when run without cover (grep just limits output for easier comparison, full info logs w/o filtering available at that repo)

```bash
./gradlew clean testSweetDebugUnitTest | grep -E "> Task :app:(compile.+Kotlin|test)|actionable"
> Task :app:compileSweetDebugKotlin
> Task :app:compileSweetDebugUnitTestKotlin
> Task :app:testSweetDebugUnitTest
23 actionable tasks: 23 executed
```

## With Kover

```bash
./gradlew clean testSweetDebugUnitTest koverXmlReport | grep -E "> Task :app:(compile.+Kotlin|test)|actionable"
> Task :app:compileSaltyDebugKotlin
> Task :app:compileSaltyDebugUnitTestKotlin
> Task :app:compileSweetDebugKotlin
> Task :app:testSaltyDebugUnitTest
> Task :app:compileSweetDebugUnitTestKotlin
> Task :app:testSweetDebugUnitTest
> Task :app:compileSweetReleaseKotlin
> Task :app:compileSweetReleaseUnitTestKotlin
> Task :app:compileSaltyReleaseKotlin
> Task :app:testSweetReleaseUnitTest
> Task :app:compileSaltyReleaseUnitTestKotlin
> Task :app:testSaltyReleaseUnitTest
91 actionable tasks: 91 executed
```

**Errors**
n.a.

**Expected behavior**
Running a build with `koverXmlReport` should not cause any other flavors or build-types to run. 

The tasks executed should be the same with or without Kover, other than the Kover task itself.

**Reproducer**

Sample project (with `--info` build logs).

https://github.com/samuelneff/kover-build-explosion

**Reports**

n.a.

**Environment**

Desc | Version
--- | ---
Kover | 0.6.1
Project Type | Kotlin/Android
Coverage Engine | Default 
Gradle | 7.3.3
Gradle Revision: | 6f556c80f945dc54b50e0be633da6c62dbe8dc71
Kotlin | 1.5.31
Groovy | 3.0.9
Ant | Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM | 11.0.13 (Eclipse Adoptium 11.0.13+8)
OS | Mac OS X 12.6 x86_64

**Comment by Gerardoeg** [comment]
Already reported in #187, and it's related to feature #18.

**Comment by samuelneff** [comment]
Thanks, I saw those afterwards unfortunately. Sorry about that; I'm usually very good about searching first.

Maybe the details are helpful at least? Regardless, I'll look forward to a built-in fix. 👍
