### ISSUE TITLE
Allow for classes to be Included by annotation

### ISSUE THREAD

**Issue by KennyGoers** [Kotlin/kotlinx-kover#274]
Currently Kover only supports exclusion by annotation.

As a development team we have added and filtered classes that are marked with an annotation (@Testable for example) that require a minimum of 95% coverage because they are business logic only, would be very nice to be able to include by annotation to minimum the external code we write to do this currently with JaCoCo.

**Comment by zuevmaxim** [comment]
https://youtrack.jetbrains.com/issue/IDEA-338719

**Comment by shanshin** [comment]
Implemented in `0.8.0`
