### ISSUE TITLE
Excluding `*FragmentDirections` and `*FragmentArgs` doesn't actually exclude them

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [Kotlin/kotlinx-kover#297]
My kover config:
```
koverMerged {
    enable()

    filters {
        classes {
            excludes.addAll(
                listOf(
                    "*Fragment",
                    "*Fragment\$*",
                    "*FragmentDirections",
                    "*FragmentArgs",
                    "*Activity",
                    "*Activity\$*",
                    "*BuildConfig",
                )
            )
        }

        projects {
            excludes.addAll(
                listOf(
                    "testFixtures"
                )
            )
        }
    }
}
```

When running `koverMergedHtmlReport`, the `*Fragment` and `*Activity` classes are correctly excluded from coverage report. However the `*FragmentDirections` and `*FragmentArgs` are still in the report:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/70261110/214886904-2bfbbd7d-8058-40d7-a0d0-8c1dea690add.png">

Kover version: 0.6.1
Gradle version: 7.5.1
Android Gradle Plugin version: 7.4.0
JUnit version: 5.9.2

**Comment by shanshin** [comment]
Hi,
to exclude class `AirConnectorStateFragmentArgs` from the report, you need to use the rule `*Fragment*`.

The `*Fragment` rule would be suitable for excluding classes like `FooClassFragment` or `BarClassFragment` (the name should not have any letters after `Fragment`)

**Comment by shanshin** [comment]
Hi,
if use the `*Fragment*` rule, does the problem still reproduce?

**Comment by lukasz-kalnik-gcx** [comment]
Hey @shanshin, thanks for replying so quickly!
the `*Fragment*` rule actually excludes the `*FragmentArgs` and `*FragmentDirections` classes:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/70261110/215043374-76d6fd0e-745b-4b29-b2f7-5916d03c2eaa.png">

However this seems counter-intuitive.
Why does `*Fragment` (without trailing asterisk) correctly exclude all classes ending with `Fragment`, but `*FragmentArgs` doesn't exclude all classes ending with `FragmentArgs`?

Is there some special matching logic used by kover?
Thanks for your help!

**Comment by lukasz-kalnik-gcx** [comment]
Another issue:
I now tried to exclude all classes ending with `View` by adding the `*View` rule.
They were also not excluded (the report is exactly the same as in the screenshot from my previous answer).

**Comment by lukasz-kalnik-gcx** [comment]
I think it would be very useful to be able to exclude interfaces. Usually they don't contain any implementation code (unless they have some default methods, then you could include them specifically).

**Comment by shanshin** [comment]
The current HTML report does not display all the useful information.

It is most likely that the `...FragmentArgs` and `...ViewModel` classes contain nested classes (lambdas, anonymous classes, nested named classes).

If the class has nested classes, it will still be displayed in the report at this level, however, if you open this class, it will be indicated for it which nested classes are present.

You can exclude nested classes through the `*FragmentArgs*` or `*FragmentArgs*$*` rule.

**Comment by lukasz-kalnik-gcx** [comment]
Actually I wanted to exclude the `*View` interfaces, not `*ViewModel` classes. But this doesn't work.

**Comment by shanshin** [comment]
For the general case, use `*View*` or `*View*$*`.

Also, please show what the report displays if you go to `RenameSystemViewModel` or `RenameSystemViewModelFactory`.

**Comment by shanshin** [comment]
Please show what the report displays for `...View` interfaces.

**Comment by lukasz-kalnik-gcx** [comment]
> The current HTML report does not display all the useful information.
> 
> It is most likely that the `...FragmentArgs` and `...ViewModel` classes contain nested classes (lambdas, anonymous classes, nested named classes).
> 
> If the class has nested classes, it will still be displayed in the report at this level, however, if you open this class, it will be indicated for it which nested classes are present.
> 
> You can exclude nested classes through the `*FragmentArgs*` or `*FragmentArgs*$*` rule.

You are right, e.g. the `*Directions` classes were still in the report because of the nested `...Directions$Companion` class. This helped, thank you!

**Comment by lukasz-kalnik-gcx** [comment]
> Please show what the report displays for `...View` interfaces.

Here you were also obviously right, the `...View` interface contains `...View$DefaultImpls`.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/70261110/215055010-db96ef7e-f901-4400-887e-0535b9ac19ee.png">

Thanks so much for your help.

**Comment by shanshin** [comment]
> Here you were also obviously right, the ...View interface contains ...View$DefaultImpls

You may write rule like `*View$DefaultImpls` or `*View$*`

**Comment by lukasz-kalnik-gcx** [comment]
Yes! I wish it was mentioned in the documentation that failing to exclude *all* nested classes will still keep the main class in the report, even though it is on the exclude list.
Thank you.
