### ISSUE TITLE
Support for Gradle JVM Test Suite Plugin

### ISSUE THREAD

**Issue by a-glapinski** [Kotlin/kotlinx-kover#298]
It would be nice to be able to aggregate the results of multiple code coverage reports for each test suite from the [JVM Test Suite Plugin](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html). The [JaCoCo Report Aggregation Plugin
](https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html) does exactly that - when the JVM Test Suite plugin is applied, `[testSuite]CodeCoverageReport` tasks are added for each test suite. 

Also, not sure if it is related to https://github.com/Kotlin/kotlinx-kover/issues/284, but IMO it would be nicer that instead of creating merged report for all subprojects of the given project, the Kover plugin would work in the similar fashion as the [Test Report Aggregation Plugin](https://docs.gradle.org/current/userguide/test_report_aggregation_plugin.html) and the JaCoCo Report Aggregation Plugin - only the direct and transitive [project dependencies](https://docs.gradle.org/current/samples/declaring_dependencies.html#sub:project_dependencies) of the current project’s runtime classpath are selected for potential aggregation ([sample from Gradle docs](https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_distribution.html)).

**Comment by shanshin** [comment]
Hi,
since the Kover plugin is a universal plugin used for both Kotlin/JVM, Kotlin/MP and Kotlin/Android projects, integration with a plugin specialized for Java projects is difficult and may not be convenient.

Based on this, there are no plans to integrate Kover with the JVM Test Suite Plugin.
