### ISSUE TITLE
Kover report not using SNAPSHOT dependencies

### ISSUE THREAD

**Issue by JohnSnowTheRealOne** [Kotlin/kotlinx-kover#299]
**Describe the bug**
Kover not using SNAPSHOT dependencies at all, even when it should use the build.gradle.kts dependencies

**Errors**
If present, stacktraces or files from `build/kover/errors` directory
Won't find new function that was added in the SNAPSHOT version of the dependency. Even though build + tests work.

**Expected behavior**
Should use the build.gradle.kts declared dependencies even if they ends with -SNAPSHOT

**Environment**
Intelij: 2022.1.3
Gradle version: 7.5.1
Kover: 0.6.1
Kotlin: 1.7.21

**Comment by shanshin** [comment]
Hi, 
may you clarify, what dependencies do you mean? 

> Won't find new function that was added in the SNAPSHOT version of the dependency. 

And where exactly was the function added?

**Comment by JohnSnowTheRealOne** [comment]
Dependencies as in gradle, for example this specific library is pulled from maven with version "SNAPSHOT" using "implementation" function on build.gradle.kts

The library itself doesn't matter - I made it and it works - successfully build module that uses it and runs several test on intelij.
It's just that in kover it doesn't recognizes SNAPSHOT version libraries so that when you kover report it, it will mark new functions that was added in SNAPSHOT and pushed to maven, as missing.

**Comment by shanshin** [comment]
What tool do you use to create reports? 
The Kover report generator adds to XML/HTML reports only those classes that are declared directly in the Gradle project itself. Any external dependencies (e.g. from maven repositories) are not included in its report.

**Comment by shanshin** [comment]
Feel free to open new bug issue if the problem reproduced again
