### ISSUE TITLE
How can we exclude generated files?

### ISSUE THREAD

**Issue by vivart** [Kotlin/kotlinx-kover#30]
```
tasks.withType<Test> {
    extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
        generateXml = false
        generateHtml = true
        coverageEngine = kotlinx.kover.api.CoverageEngine.INTELLIJ
        includes = listOf("com\\.example\\..*")
        excludes = listOf("dagger\\.hilt\\..*", "com\\.example\\.settings\\.*FragmentDirections\\.*")
    }
}
```
I am able to exclude hilt package but FragmentDirections files are still showing in the report.

**Comment by Tihon-Ustinov** [comment]
> Hi! At the moment, the API of the plugin does not imply the exclusion of specific classes from the report. See #17 `includes` and `excludes` controls the instrumentation of the specified classes but not the report.

Why exclude don't work? 

I am have next exclude template
 
![image](https://user-images.githubusercontent.com/15249713/140874840-2a016449-36ce-4c1a-94c0-186df4a5a782.png)

but in output I am have 

![image](https://user-images.githubusercontent.com/15249713/140874936-0a467982-9c4c-43b6-a99c-306211b2f5b1.png)

**Comment by Tihon-Ustinov** [comment]
@shanshin Can you see what I'm doing wrong?

**Comment by vivart** [comment]
This works for me
```
tasks.withType<Test> {
    extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
        isEnabled = true
        binaryReportFile.set(file("$buildDir/custom/result.bin"))
        includes = listOf("com\\.example\\..*")
        excludes = listOf(
            "dagger\\.hilt\\..*",
            "com\\.example\\.todo\\.databinding\\..*",
            "com\\.example\\.todo\\.di\\..*",
            "com\\.example\\.todo\\.ui\\.display\\..*",
            "com\\.example\\.todo\\.ui\\.edit\\..*",
            "com\\.example\\.settings\\..*",
        )
    }
}
```

**Comment by shanshin** [comment]
> > Hi! At the moment, the API of the plugin does not imply the exclusion of specific classes from the report. See #17 `includes` and `excludes` controls the instrumentation of the specified classes but not the report.
> 
> Why exclude don't work?
> 
> I am have next exclude template
> 
> ![image](https://user-images.githubusercontent.com/15249713/140874840-2a016449-36ce-4c1a-94c0-186df4a5a782.png)
> 
> but in output I am have
> 
> ![image](https://user-images.githubusercontent.com/15249713/140874936-0a467982-9c4c-43b6-a99c-306211b2f5b1.png)

Perhaps you have another test task in your project in which these classes are not excluded?
What is the content of the file `build/tmp/koverHtmlReport/intellijreport.args` after the build ?
The first few lines will list reports for completed test tasks

**Comment by SimonedeGijt** [comment]
Hey guys, I have a similar issue. When I exclude some packages from kover it is indeed not taken into account in the percentages Class%, Block% and Line%, but because it is still part of the report, the overall coverage drops. This leads to an even more negative result than when I would exclude it. My configuration:
`tasks.test {
  extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
    isEnabled = true
    binaryReportFile.set(file("$buildDir/reports/kover/result.bin"))
    includes = listOf("org\\.example\\.something\\.blabla\\..*")
    excludes = listOf(
      "org\\.example\\.something\\.blabla\\.controller\\..*"
    )
  }
}`

**Comment by shanshin** [comment]
@SimonedeGijt, please check in version `0.4.3`.

**Comment by shanshin** [comment]
@Tihon-Ustinov, please, if the problem is reproduced in version `0.4.3`, create a new one issue with a detailed description.

**Comment by purposebakery** [comment]
Just for that random soul coming across the same issue above version 0.4.4: I'm currently on version 0.6.0 and this doesn't work for me when I set the exclusions on module level. If I enable koverMerged and run the merged task and **set the exclusions on project level** this works.
