### ISSUE TITLE
Is Kover under active development?.

### ISSUE THREAD

**Issue by vb-hp** [Kotlin/kotlinx-kover#300]
I would love to use it in an enterprise application to replace the jacoco plugin mainly for Koltin.

However, would like to know whether this plugin is under active development like other Kotlin plugins.
Appreciate any quick response!.

**Comment by qwwdfsad** [comment]
It indeed is, right now we are experimenting with and aiming to ship the new concise DSL that will reduce configuration complexity, will be Gradle 8 friendly and support Android Gradle plugin: https://github.com/Kotlin/kotlinx-kover/pull/295

**Comment by vb-hp** [comment]
Thanks for the quick response @qwwdfsad . closing the question.
