### ISSUE TITLE
Injection of fields like `branchHits` can break certain packages (e.g. Velocity)

### ISSUE THREAD

**Issue by alyssa-glean** [Kotlin/kotlinx-kover#301]
**Describe the bug**
We use Velocity in our project (`org.apache.velocity:velocity-engine-core:2.3`), and enabling Kover with the default settings caused tests to fail with an exception. This same issue was reported with the IntelliJ tool [here](https://youtrack.jetbrains.com/issue/IDEA-274803/Velocity-field-names-check-fails-with-new-coverage).

**Errors**
The specific stack trace in this instance was:

```
org.apache.velocity.exception.VelocityException: Could not initialize property keys deprecation map because DeprecatedRuntimeConstants.__$branchHits$__ field isn't properly named
                at app//org.apache.velocity.util.DeprecationAwareExtProperties.<clinit>(DeprecationAwareExtProperties.java:150)
                ... 54 more
```

**Expected behavior**
Ideally, enabling test coverage should have no impact on test results. However, obviously injecting these fields is fairly fundamental to what Kover is doing, so perhaps documenting it somewhere would be a good start? You could also consider maintaining a list of default files to exclude if there are commonly used dependencies with these sorts of issues. In my case, I was able to work around the problem with this config:

```
kover {
    filters {
        classes {
            excludes.addAll("org.apache.velocity.runtime.DeprecatedRuntimeConstants")
        }
    }
}
```

**Environment**
 - Kover Gradle Plugin version: 0.6.1
 - Gradle version: 7.5.1
 - Kotlin project type: Kotlin/JVM

**Comment by shanshin** [comment]
Unfortunately, since the list of incompatible libraries is unknown in advance, they are added as incompatibilities are detected.

Also, example of an incompatible dependency #89.

**Comment by shanshin** [comment]
Duplicates of #418
