### ISSUE TITLE
kover tasks fail if android plugins aren't specified in project level build.gradle

### ISSUE THREAD

**Issue by nicholaslythall** [Kotlin/kotlinx-kover#304]
**Describe the bug**
When using kover in an android project, if the android and kotlin plugins are only specified in the module-level build.gradle, kover tasks will fail after running the tests but before creating any reports.
```groovy
// project-level build.gradle
plugins {
    // Without these lines kover will fail 
    id 'com.android.application' version '7.2.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.10' apply false

    id 'org.jetbrains.kotlinx.kover' version "0.6.1"
}
```

**Errors**
```
> Task :koverMergedHtmlReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to query the value of task ':koverMergedHtmlReport' property 'files$kover'.
> Type com.android.build.gradle.BaseExtension not present
```

**Expected behavior**
I'm not sure if there's anything that can be done. In hindsight, the error "Type com.android.build.gradle.BaseExtension not present" is an accurate description of the problem, but it would be better if a more informative error message could be displayed.

It could be a good idea to update the [current documentation](https://kotlin.github.io/kotlinx-kover/) to mention the requirement.

Mostly I am creating this issue to help anyone else who runs into the same problem as me. 

**Reproducer**
I've updated the android_groovy example from the current release branch to replicate the problem.
[android_groovy.zip](https://github.com/Kotlin/kotlinx-kover/files/10761571/android_groovy.zip)

Steps to reproduce:
1. run any of the kover tasks
  - `./gradlew koverMergedHtmlReport`
  - `./gradlew koverMergedVerify`
  - `./gradlew koverMergedHtmlReport`
  - etc

**Environment**
 - Kover Gradle Plugin version: 0.6.1
 - Gradle version: 7.3.3
 - Kotlin project type: Kotlin/Android

**Comment by shanshin** [comment]
Hello, could you please try the `0.7.0-Alpha` version? 
There is support for `"com.android.library"`

**Comment by shanshin** [comment]
@nicholaslythall, please try the new `0.7.0-Beta` version.

**Comment by shanshin** [comment]
Feel free to open new bug issue if the problem reproduces in `0.7.2`.
