### ISSUE TITLE
Source file not viewable with Jacoco and Kotlin Directory Structure

### ISSUE THREAD

**Issue by SimonedeGijt** [Kotlin/kotlinx-kover#31]
Hey guys, 

We tried to implement the Kover solution, as we hoped that it would solve our problem regarding the Jacoco report in combination with the Kotlin Directory Structure. Unfortunately it seems we still have the same issue as with using the normal Jacoco plugin. 

When opening the report in html you are "normally" able to view the source file and within that file the coverage per line of code. This works when you are using Jacoco with the Java directory structure, but with kotlin you get the following message: "Source file "xxx" was not found during generation of report".

Did anyone of you come across this and has a solution for this? If not; can we maybe look into a future solution? :) 

Kind regards,
Simone

**Comment by shanshin** [comment]
@SimonedeGijt, fixed in `0.4.2`

**Comment by SimonedeGijt** [comment]
Awesome! It works with the IntelliJ engine!
