### ISSUE TITLE
BR class not excluded

### ISSUE THREAD

**Issue by pvegh** [Kotlin/kotlinx-kover#310]
BR classes should be excluded by `*.databinding.*`,
Probably also should be default, no config needed?

Using config:
```
koverAndroid {
    // filters for all report types of all build variants
    common {
        filters {
            excludes {
                classes(
                    "*Fragment",
                    "*Fragment\$*",
                    "*Activity",
                    "*Activity\$*",
                    "*.databinding.*",
                    "*.BuildConfig",
                )
            }
        }
    }
}
```

**Expected behavior**
BR classes shouldn't show up in the report

**Environment**
 - Kover Gradle Plugin version: [e.g. 0.7.0-Alpha]
 - Gradle version: [e.g. 7.6]
 - Kotlin project type: Kotlin/Android
 - Coverage Engine version (if customized in build script):
 - Other context important for this bug: [e.g. OS version]

**Comment by shanshin** [comment]
Hi,
the exclusion rules use fully-qualified class names.
If you want to exclude a class, you need to write either the full name of the class (e.g. `"my.package.Fragment"`) or use wildcards (`"*.Fragment", "*.Fragment$*", "*.databinding.*"` etc).
Also see filters [examples](https://github.com/Kotlin/kotlinx-kover/blob/7aadd75bdff90c2fe9f7a074ca043363a410ff84/examples/android/minimal_groovy/app/build.gradle#L52)

**Comment by pvegh** [comment]
Looks exactly like what I havem but the code block was missing, asterisk disappearing. Sorry, fixed.

**Comment by shanshin** [comment]
If you specify this filter, then classes are excluded from the report? What task are you running to build a report?

**Comment by pvegh** [comment]
No, I see many BR classes in the report in app/build/reports/kover/htmlLocalDebug/index.html
I run the html task for the localDebug variant

**Comment by shanshin** [comment]
Your project is open source, is it possible to get acquainted with it?

**Comment by pvegh** [comment]
Sorry but it isn't. I'm not sure when I'll find time to create a reproducer for this. Hoping someone else also has the problem with more time on hand.

**Comment by shanshin** [comment]
Can you show the entire `koverAndroid` configuration?

If you have specified a filters for a specific variant, then they completely override all exclusions.

**Comment by pvegh** [comment]
That's the full config above actually, wanted to start with the official setup

**Comment by pvegh** [comment]
is one asterisk really correct, instead of double to define whatever subpackage it might be?

**Comment by shanshin** [comment]
If you specify a class from your application in the filters, will it disappear from the report?

**Comment by pvegh** [comment]
Yes the following does hide the 2 classes (from 2 different modules) in the report:
(The others BR classes are still there, it's not realistic to exclude them one by one)
...
            excludes {
                classes(
                    "foo.bar.BR",
                    "foo.bar2.BR",
                    "*Fragment",
                    "*Fragment\$*",
                    "*Activity",
                    "*Activity\$*",
                    "*.databinding.*",
                    "*.BuildConfig",
                )
            }
...

**Comment by shanshin** [comment]
I will try to reproduce this locally

**Comment by shanshin** [comment]
Please try the new DSL in version `0.7.0-Beta`.
Feel free to open new bug issue if the problem reproduced again.

**Comment by pvegh** [comment]
I tried again with the Beta, not sure anything changed. See comments in my config

koverReport {
        androidReports("debug") {
            filters {
                excludes {
                    classes(
                        "*BR", // TODO doesn't exclude them in either app module nor in submodule
                        "*Fragment",
                        "*Fragment\$*",
                        "*Activity",
                        "*Activity\$*",
                        "*.databinding.*",
                        "*.BuildConfig", // doesn't exclude them in either app module nor in submodule
                        // excludes debug classes
                        "*.DebugUtil",
                    )
                }
            }
        }
    }

**Comment by shanshin** [comment]
Could you show a screenshot of the report for any BR class?

**Comment by pvegh** [comment]
<img width="1728" alt="kover beta BR" src="https://user-images.githubusercontent.com/3873889/234224628-657dbd0b-fc0d-4226-a3cc-488f627393e6.png">

**Comment by pvegh** [comment]
Not using androidReports at all solves the problem. I though without it nothing would be generated. I'll have to use this a little more but seem like this exact issue is indeed solved when using the right config. Thanks!

**Comment by shanshin** [comment]
>  I though without it nothing would be generated

Calling the corresponding task always starts the report generation. Configuration is optional, it only allows you to change the contents of the report.


Unfortunately, in this version, the code missed checking for the existence of a build variant, so there was no error even when trying to configure a report for a variant that is not in the project.
