### ISSUE TITLE
Android Multi-Module | No coverage for Kotlin modules

### ISSUE THREAD

**Issue by af-hku** [Kotlin/kotlinx-kover#312]
### Description
Kover does not create a report for all modules if there are plain Kotlin modules within an Android project.
-> task `koverHtmlReport` only creates coverage report for Kotlin modules
-> task `koverHtmlReportDebug` only creates coverage report for Android modules

### Expected behavior
Merged coverage report for all specified modules can be created using one _kover_ Gradle task  (e.g. build variant independent gradle kover task)

**Example:** [detekt](https://github.com/detekt/detekt) 
* Android modules: Gradle tasks `detekt`, `detektDebug`, `detektRelease`
* Kotlin modules: Gradle task `detekt`
* -> run `detekt` to get results for all modules

### Reproducer
Use kover's [multiproject example](https://github.com/Kotlin/kotlinx-kover/tree/main/examples/android/multiproject) and make the `lib` module a plain Kotlin module (which it actually is)

_lib/build.gradle_
```
plugins {
    id ("org.jetbrains.kotlin.jvm")
    id ("org.jetbrains.kotlinx.kover")
}

dependencies {
    testImplementation("junit:junit:4.13.2")
}
```

-> `koverHtmlReport` creates report for lib module only
-> `koverHtmlReportDebug` creates report for app module only
-> no merged report possible with the existing _kover_ gradle tasks

### Environment
 - **Kover Gradle Plugin version:** 0.7.0-Alpha
 - **Gradle version:** 8.0
 - **Kotlin project type:** Kotlin/Android - Multi Module
 - **Coverage Engine version:** KoverTool / JacocoTool (same behavior for both tools)
 - **Other context important for this bug:** -

**Comment by shanshin** [comment]
Hi,
unfortunately, DSL for integration of multiplatform and Android projects is not implemented at the moment.
The main problem here is that the build variants are known only in Android projects, there is no such information in a plain project and it is impossible to create appropriate tasks for each build variant.

As a solution, we may add a special task for which user can specify in the build script which Android build variant (only one or several?) will be used.

However, the design of such a feature was postponed until receiving feedback on the current implementation of fully Android projects.

**Comment by shanshin** [comment]
Duplicates #316
