### ISSUE TITLE
will be skipped because no tests were executed

### ISSUE THREAD

**Issue by taymiyyah** [Kotlin/kotlinx-kover#313]
**Describe the bug**

**Errors**
Task 'koverHtmlReport' will be skipped because no tests were executed

**Expected behavior**
I only have tested in one module in multi module android-project
my testing will be generated at
$rootDir/kmm/build/reports/tests/testDebugUnitTest/index.html

How can I tell kover my testing report is on that path?

**Comment by shanshin** [comment]
Hi,
can you please provide a reproducer?

Such a message will be if not a single test has worked. Perhaps you don't have any tests in your project, they are all ignored, or a dependency on another project that has tests is not specified.

It is also important that now Kover supports only tests on the local machine (not on an Android device) - for example, JUnit tests.

**Comment by shanshin** [comment]
Could you clarify which Kover task you are calling?

For Android projects, you should use the `koverHtmlReportDebug` task to generate HTML report for `debug` build variant. Task `taskHtmlReport` not used in android projects.

**Comment by shanshin** [comment]
Please, see #312

It's current limitation for combined Android+multiplatform builds

**Comment by taymiyyah** [comment]
thank you , I do only have multiplatform
my thought that `gradle test" will create a HTML report that will be consume by kover please correct me

**Comment by shanshin** [comment]
> my thought that `gradle test" will create a HTML report that will be consume by kover please correct me

Not really. The coverage measurement results (`testName.ic` or `testName.exec`) are used only by the relevant report tasks. It depends on the Kover settings, the availability of build options, filters, etc.

To link a report call to a measurement result for a specific test, additional information is needed. And if there is an android project in the multi platform build, now Kover does not determine the results of which test to use, and  does not use it

**Comment by taymiyyah** [comment]
I think because unit test are in common test director , kover cannot find that ,
kotlin multiplatform is really not working , 

reproducer
1.create kmm project android studio 
2. add kover

just give me an example for kover sample that used kmm 

thank you for your time , really appreciated

**Comment by taymiyyah** [comment]
[KoverKMM.zip](https://github.com/Kotlin/kotlinx-kover/files/10880130/KoverKMM.zip)
here you are

**Comment by taymiyyah** [comment]
is there any thing similar to jacoco classDirectories in kover 

tasks.jacocoTestReport {
    val coverageSourceDirs = arrayOf(
            "src/commonMain",
            "src/jvmMain"
    )

    val classFiles = File("${buildDir}/classes/kotlin/jvm/")
            .walkBottomUp()
            .toSet()

    classDirectories.setFrom(classFiles)
    sourceDirectories.setFrom(files(coverageSourceDirs))

    executionData
            .setFrom(files("${buildDir}/jacoco/jvmTest.exec"))

    reports {
        xml.isEnabled = true
        html.isEnabled = true
    }
}
