### ISSUE TITLE
[0.7.0-Alpha] Excluding package hilt_aggregated_deps doesn't seem to work

### ISSUE THREAD

**Issue by wezley98** [Kotlin/kotlinx-kover#315]
**Describe the bug**
Exclude `hilt_aggregated_deps` as a package to remove it from the report. It still appears in the report.

```
koverReport {
    filters {
        excludes {
            // excludes class by fully-qualified JVM class name, wildcards '*' and '?' are available
            classes(
                "*.BuildConfig",
                "*.*_Factory*",
                "*.*Factory*",
                "*.di.*",
                "*.*MembersInjector*",
                "*.*_HiltModules*",
                "hilt_aggregated_deps.*",
                "dagger.hilt.internal.aggregatedroot.codegen.*",
                "*.*previewProviders.*",
                "*.*previews.*",
                "*.*IdlingResource*",
                "*.*ExtensionsKt*",
                "*.extensions.*"
            )
            // excludes all classes located in specified package and it subpackages, wildcards '*' and '?' are available
            packages("hilt_aggregated_deps")
            // excludes all classes and functions, annotated by specified annotations, wildcards '*' and '?' are available
            annotatedBy("*Generated*")
        }
    }
    xml {
        onCheck = false
    }
    html {
        onCheck = false
    }
}
```

**Errors**
No errors, see screenshot

**Expected behavior**
Package is excluded from report

**Reproducer**
Build an Android/Kotlin project using `hilt` https://dagger.dev/hilt/

**Reports**
<img width="1055" alt="Screenshot 2023-03-03 at 10 57 45" src="https://user-images.githubusercontent.com/1488209/222703194-6bdccacf-8ddd-4293-b9ba-c346870128e2.png">

**Environment**
 - Kover Gradle Plugin version: 0.7.0-Alpha
 - Gradle version: 8.0.1
 - Kotlin project type: Kotlin/Android
 - Coverage Engine: KoverTool

**Comment by shanshin** [comment]
Hi, could you provide a small reproducer project?
That would be very helpful.

**Comment by shanshin** [comment]
Relates #310

**Comment by NinoDLC** [comment]
I didn't reproduce your issue on my project. 

* Migrating from 0.6.0 to 0.7.0-Alpha (with the same `exclude` `class` patterns) didn't produce any issue. I had almost 100% coverage before, I still have almost 100% after. [Source](https://github.com/NinoDLC/OpenClassrooms_P5_TodoK_Example/commit/fd9e59329f33fc21cd754782cdc23c59ce8b1448)
* Updating the `excludes` configuration didn't produce any issue either. I removed the `"hilt_aggregated_deps.*"` from `classes` and added `packages("hilt_aggregated_deps")`. [Source](https://github.com/NinoDLC/OpenClassrooms_P5_TodoK_Example/commit/21c107ac0a562e35287b0ba822eca1f8ae406819)

**Comment by shanshin** [comment]
@wezley98 , in your example, exclusions are specified in the `koverReport` block - these exceptions will only work for JVM projects.

Please try the new version `0.7.0-Beta` - the DSL has been redesigned in it and now instead of two blocks `koverReport` and `koverAndroidReport` there is only `koverReport', and the filters specified in it are used for both JVM and Android projects.
