### ISSUE TITLE
[0.7.0-Alpha] How to generate all reports (html, xml) together ?

### ISSUE THREAD

**Issue by tamalsamui** [Kotlin/kotlinx-kover#318]
**Describe what you would like to clarify about Kover**
Not able to see "koverMerged" option anymore. How to generate all reports (html, xml) together ?

and where to mention xml {} , html{} properties ?

**Comment by shanshin** [comment]
Hi,
to generate HTML and XML reports, call Gradle tasks `koverXmlReport koverHtmlReport` together.

To configure reports of JVM or multiplatform project, use the extension 
```
koverReport {
    xml {  }
    html {  }
}
```


Please also refer to [migration guide](https://github.com/Kotlin/kotlinx-kover/blob/main/docs/migration-to-0.7.0.md) or [example projects](https://github.com/Kotlin/kotlinx-kover/tree/main/examples)
