### ISSUE TITLE
Automatically Execute koverMergedReport when running tests

### ISSUE THREAD

**Issue by jblacker** [Kotlin/kotlinx-kover#321]
**What is your use-case and why do you need this feature?**
I would like to be able to execute my tests using the standard `test` command (or specific module's test command e.g. `:module:test`) and have Kover automatically instrument the tests & generate the reports that are configured.

Most devs are familiar with more common gradle tasks, but not necessarily specific tasks provided by libraries. By automatically running a merged report when multiple test modules are run or a single report if only a single module's tests were run this would simplify many dev's workflows and allow things to work "automagically" 

**Describe the solution you'd like**

Happy to discuss various options on how this might work, but ideally it would run a merged report whenever multiple tests are run if the `koverMerged { enabled() }` is in the root gradle config. If that is not set then each project's single report would be executed.

**Comment by shanshin** [comment]
Hi,
Since Gradle does not involve changing the behavior of the task when performing an independent task, it was incorrect to generate a merged report for those tasks that were started - in this case, the build cache becomes unstable.

Unfortunately, specified approach is poorly implemented in Gradle and in any case, additional configuration will be needed - either through the transfer of special parameters, or through the creation of custom tasks.

**Comment by jblacker** [comment]
@shanshin Just to make sure I understand the issue you're describing here:

>Since Gradle does not involve changing the behavior of the task when performing an independent task, it was incorrect to generate a merged report for those tasks that were started - in this case, the build cache becomes unstable.

The issue is that in the situation where a merged report is requested, but not all module's tests have been run then the merged report task won't know what data to include and what to exclude, correct? This is why we'd need to transfer some sort of parameters between the tasks to modify its behavior?

I'm trying to compare to how the JaCoCo gradle plugin worked where you could attach it to a test task to always generate the report when running `test` (or another testing command). Whereas for Kover it appears I must run the Kover specific task to generate coverage metrics. So it may just be me not understanding how these two plugins work "under the hood."
