### ISSUE TITLE
How to generate coverage report even when tests fail?

### ISSUE THREAD

**Issue by dkarv** [Kotlin/kotlinx-kover#326]
We are using the latest alpha in our Android project, works great. The kover report is finalizing the unit test task:
```
afterEvaluate {
    tasks {
        getByName("testDebugUnitTest") { finalizedBy("koverXmlReportDebug", "otherTask") }
        getByName("testStagingUnitTest") { finalizedBy("koverXmlReportStaging", "otherTask") }
        getByName("testReleaseUnitTest") { finalizedBy("koverXmlReportRelease", "otherTask") }
    }
}
```

But `koverXmlReport` is not running when a test fails, only if the test stage is successful. For `otherTask` it works fine, it is executed no matter how the previous task finished.

I can only find these relevant log lines:

> [org.gradle.execution.plan.DefaultExecutionPlan] Node :app:koverGenerateSetupArtifactDebug completed, executed: false
> [org.gradle.execution.plan.DefaultExecutionPlan] Node Resolve mutations for :app:koverGenerateSetupArtifactDebug completed, executed: false
> [org.gradle.execution.plan.DefaultExecutionPlan] Node :app:koverXmlReportDebug completed, executed: false

Is there something I miss? The raw execution data is there in the build folder.
Is it possible to generate the report from it afterwards by executing some gradle task? When doing `koverXmlReportDebug` it runs all tests again and still does not execute.

**Comment by shanshin** [comment]
Closing as answered. 
Feel free to open new issue if you have any additional questions.
