### ISSUE TITLE
[Kove 0.7.0-Alpha] useJacocoTool

### ISSUE THREAD

**Issue by Atternatt** [Kotlin/kotlinx-kover#330]
**Describe the bug**

**Errors**
If present, stacktraces or files from `build/kover/errors` directory

**Expected behavior**

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: [e.g. 0.7.0-Alpha]
 - Gradle version: [e.g. 7.5.1]
 - Kotlin project type: [e.g. Kotlin/JVM, Kotlin/Multiplatform, Kotlin/Android]
 - Coverage Engine version (if customized in build script): [e.g. DefaultJacocoEngine, KoverEngine("1.0.656")]
 - Other context important for this bug: [e.g. OS version]

**Comment by shanshin** [comment]
Closing this issue.
Please try the new version `0.7.0-Beta` and if your problem recurs, create a new issue with entering a detailed description of the bug.
