### ISSUE TITLE
Multi project setup doesn't work

### ISSUE THREAD

**Issue by pvegh** [Kotlin/kotlinx-kover#333]
I want to see reports from all modules in the project. This doesn't seem to be default (why not?), so I looked in the docs.
Adding
`kover(project(":foo"))`
as stated in the documentation leads to an error.

**Errors**
```
If present, stacktraces or files from `build/kover/errors` directory
* What went wrong:
Could not determine the dependencies of task ':app:koverHtmlReportLocalDebug'.
> Could not resolve all task dependencies for configuration ':app:koverAggregatedSetupLocalDebug'.
   > Could not resolve project :foo.
     Required by:
         project :app
```
while also having
`implementation(project(":foo"))`
in there which works as it should

**Expected behavior**
I expected the submodules to be in the report. Why wouldn't I want to scan the whole project only the app module in case of an android app? Confusing default behavior.

**Reproducer**
Sorry, currently can't.

**Environment**
 - Kover Gradle Plugin version: [0.7.0-Alpha]
 - Gradle version: [7.6]
 - Kotlin project type: [Kotlin/Android]
 - Coverage Engine version (if customized in build script): [not customized]
 - Other context important for this bug: [macOS 13.3]

**Comment by pvegh** [comment]
Yes we use matchingFallbacks in our project.

Having possibly many dozens of modules in a bigger project, it would make it much harder to introduce kover as you need to add kover exactly n times in n files. At least in a default gradle environment.
Custom plugins and buildSrc would help, which probably makes sense at that complexity, but also might not be a given everywhere.

Thanks for the pointers.

**Comment by shanshin** [comment]
Duplicates #314
