### ISSUE TITLE
Can't have both jacoco and kover plugins on the classpath

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx-kover#337]
**Describe the bug**
Can't seem to have both jacoco and kover on the classpath.

```
Caused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.System$2.defineClass(System.java:2131)
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
        ... 13 more
```

**Reproducer**
```
plugins {
    jacoco
    id("org.jetbrains.kotlinx.kover")
}

kover {
  useJacocoTool("0.8.8")
}
```
**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: `0.7.0-Alpha`
 - Gradle version: `8.0.2`
 - Kotlin project type: `Kotlin/Android`

**Comment by shanshin** [comment]
Hi,
if you use the JaCoCo tool (by specifying `useJacocoTool("0.8.8")`), then you don't need to apply `jacoco` plugin.

JaCoCo and Kover Gradle Plugins cannot be applied to the project at the same time, because in this case double instrumentation will occur and the stability of the measurement is not guaranteed.

**Comment by shanshin** [comment]
If necessary, you may disable the instrumentation by Kover in this way
 ```
kover {
    disabledForProject = false
}
```

in this case, only the instrumentation by the `jacoco` plugin will work

**Comment by shanshin** [comment]
> In theory, we might solve it with classpath isolation,

Unfortunately, classpath isolation will not help because the problem is not in the Gradle plugin, but in the JVM instrumentation agent
