### ISSUE TITLE
Add ability to convert DefaultIntelliJReport to Jacoco Report

### ISSUE THREAD

**Issue by kmbisset89** [Kotlin/kotlinx-kover#341]
I cannot get jacoco to run but I can get the DefaultIntelliJ engine to run. However, my CI pipeline only would like JaCoCo.

 If there was a gradle function that would translate the Default engine results to a JaCoCo result so I could have both it would be much appreciated.

**Comment by shanshin** [comment]
With a few exceptions, the Kover and JaCoCo XML reports are identical.

**Comment by kmbisset89** [comment]
You are correct that Azure does accept the xml file as is.
