### ISSUE TITLE
Unclear documentation on dependencies for subprojects ion 0.7.0-Alpha

### ISSUE THREAD

**Issue by kmbisset89** [Kotlin/kotlinx-kover#343]
I am trying to re-setup kover with 0.7.0-Alpha. I want to run kover on my subprojects. Original I had done it through the plugin section of the module like :
`plugins {
    id("org.jetbrains.compose")
    kotlin("multiplatform")
    id("kover")
    `maven-publish`
}`

I now see in the documentation it is more appropriate to do 
`dependencies {
    kover(project(":core"))
    kover(project(":utils"))
}`

I am unsure where to put this dependencies block 
`koverReport{
    xml{
        this.setReportFile(file("build/reports/kover/test/jacocoTestReport.xml"))

        filters{
            includes{
                packages("mil.jtaps.vehicles")
            }
        }
    }

    dependencies{
        kover(project(":vehicles"))
    }
}`

My question is how can I get the koverXmlReport task to trigger the test that need to run in my sub modules.

**Comment by shanshin** [comment]
If Kover plugin applied in `:vehicles` subproject then `:koverXmlReport` will trigger the execution of subproject's tests (e.g. `:vehicles:test` for Kotlin/JVM).

> I am unsure where to put this dependencies block

It is better to specify dependencies at the root level of the build script.
However, the options 
```
koverReport {
    xml {
        // ..
    }
}

dependencies {
    kover(project(":vehicles"))
}
```
and
```
koverReport {
    xml {
        // ..
    }

    dependencies {
        kover(project(":vehicles"))
    }
}
```
are equivalent

**Comment by kmbisset89** [comment]
Okay I am getting an error but I will take a look at why. 

 The consumer was configured to find attribute 'kotlinx.kover.setup.name' with value ''. However we cannot choose between the following variants of project :vehicles:
          - debugApiElements
          - debugRuntimeElements
          - desktopApiElements
          - desktopRuntimeElements
          - jvmApiElements
          - jvmRuntimeElements
          - metadataApiElements
          - releaseApiElements
          - releaseRuntimeElements

**Comment by shanshin** [comment]
Please check that the Kover plugin is applied in the `:vehicles` subproject

**Comment by kmbisset89** [comment]
![image](https://user-images.githubusercontent.com/42785343/233169712-f45a3ffe-54ff-4a77-bccb-a2b4359bfae1.png)
I am getting an error applying it to subproject

**Comment by shanshin** [comment]
The DSL uses the plugin id - this is
```
plugins {
    id("org.jetbrains.kotlinx.kover")
}
```

I also recommend reading examples of using the plugin in multi-projects builds
https://github.com/Kotlin/kotlinx-kover/tree/main/examples/jvm/merged

or other examples

**Comment by shanshin** [comment]
@kmbisset89, 
did changing `id("kover")` to `id("org.jetbrains.kotlinx.kover")` solve your problem?

**Comment by kmbisset89** [comment]
Yes it did thank you so much for your speedy replies.
