### ISSUE TITLE
Different releases with same name (only case differs) cause problems for win users

### ISSUE THREAD

**Issue by amal** [Kotlin/kotlinx-kover#344]
In the maven repo, there are two different versions of Kover: [0.7.0-Alpha](https://mvnrepository.com/artifact/org.jetbrains.kotlinx.kover/org.jetbrains.kotlinx.kover.gradle.plugin/0.7.0-Alpha) and [0.7.0-ALPHA](https://mvnrepository.com/artifact/org.jetbrains.kotlinx.kover/org.jetbrains.kotlinx.kover.gradle.plugin/0.7.0-ALPHA).

These versions are totally different but have the same version name.
As their names differ only in case, in some situations, Gradle can download both of them and on Win OS the second one can easily override the first as Win is basically case-insensitive for files and folders. I'm experiencing these problems locally and in GitHub workflows.

Please, don't publish releases like these.
And please, publish an update with a different version name to overcome the current situation.

**Comment by shanshin** [comment]
Hi,
thanks for the detailed explanation, sorry for the inconvenience.

You may try the new `0.7.0-Beta` version.
