### ISSUE TITLE
0.7.0 feedback: The new DSL is too difficult to configure at a global/convention level

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/kotlinx-kover#345]
**Describe the bug**
The new DSL in 0.7.0 is a lot of welcome and important changes!

However, it's sort of a nightmare to try to configure from a common entry point, such as a Gradle convention plugin due to the asymmetric Android and non-Android API entry points.

The closest we can get currently is something like below

```kotlin
val config = ...

if (plugins.hasPlugin("org.jetbrains.kotlin.multiplatform")) {
  // Multiplatform projects. Must be checked before android projects because the android
  // plugin can be enabled in KMP projects too.
  extensions.configure(KoverReportExtension::class, config)
} else if (plugins.hasPlugin("com.android.base")) {
  // Android projects
  extensions.configure<KoverAndroidExtension> {
    // Use the same variant as our unit tests
    report(buildVariantName = "release", config = config)
  }
} else {
  // JVM projects
  extensions.configure(KoverReportExtension::class, config)
}
```

This is, however, racy at best because it depends on plugin application order.

We could try to make it lazier and do something like this, where we conditionally configure extensions based on their presence.

```kotlin
// Android projects
extensions.findByType<KoverAndroidExtension>()?.apply {
  // Use the same variant as our unit tests
  report("release", config)
}
// JVM/Multiplatform projects
extensions.findByType<KoverReportExtension>()?.let(config::execute)
```

However, this fails in a different way. The plugin always appears to add _both_ extensions to _all_ projects, but then fails at runtime if you accidentally configure the wrong one! So this approach doesn't work either. In the case of multiplatform and android (where both can be applied), it's not even clear which to use as you have to wait for all plugins to be applied to be sure which one should be used.

What we'd like to do is something that makes it easy to share out configuration, because we don't want to manually configure kover for each subproject (we have over 600).

I think a better option would be to have a single top-level entry-point to the API in some way, or at least make it easier to configure them from a common location.

**Environment**
 - Kover Gradle Plugin version: `0.7.0-Alpha`
 - Gradle version: `8.1`
 - Kotlin project type: Kotlin/JVM, Kotlin/Multiplatform, Kotlin/Android
 - Coverage Engine version (if customized in build script): default

**Comment by shanshin** [comment]
Hi, 
thanks for the feedback!

Could you clarify a few details about your project:
1. what is configured with `config` action, only filters or something else?
2. do you need reports only for the `release` build variant?
3. do you have any projects for which android and JVM targets are created at the same time?

**Comment by shanshin** [comment]
@ZacSweers,  
please try the new DSL in version `0.7.0-Beta`.

If you configure only filters for all reports, then in the new version it will be easier to configure.

However, if you need to build a merge report on all subprojects, then it will still be a little difficult, because if you call `mergeWith` for the missing build variant, an error will also be thrown during the build execution.

**Comment by ZacSweers** [comment]
Much cleaner, thanks!
