### ISSUE TITLE
How to verify only a new code and ignore already exists not covered code? 

### ISSUE THREAD

**Issue by Evleaps** [Kotlin/kotlinx-kover#347]
Hi! 

Would u kindly explain, how can I verify only new code changes? 

I wanna check on the CI that all my new code is covered by tests. But I didn't understand from the documentation how can I do it. 
Also, I didn't see the documentation with the difference between AggregationType and MetricType. 

I would happy to see the documentation update like: 
- AggregationType. COVERED_PERCENTAGE - { logic description }
- AggregationType. MISSED_COUNT - { logic description }

But my main question:

**Comment by shanshin** [comment]
Hi,

> Would u kindly explain, how can I verify only new code changes?

Kover collects information related only to the current build, it has no information about past builds and what to consider as new code.
Kover HTML and XML reports will always display the current coverage of the entire project.

However, if you are viewing the coverage in any CI, then the display of the coverage of the new code may be its features (if there is one), and it will be configured only in it.


> Also, I didn't see the documentation with the difference between AggregationType and MetricType.

`MetricType` - this is some part of the application (small unit of application) for which it determines whether it was covered (executed) or skipped (not executed).
For example, an entire line from source code or a specific JVM instruction from compiled byte-code can be executed or not.

The entire set of information about the coverage of each line/instruction/branch must be aggregated into one understandable number, which will be compared with the conditions of the minimum or maximum value.
`AggregationType` is responsible for this.

For example, `Aggregation Type. MISSED_COUNT` is the total number of all units (lines/instructions/branches - of what was specified in `MetricType`) that were not executed when the tests were running.
And `AggregationType. 'COVERED_PERCENTAGE` is the number of units covered divided by the number of all units and multiplied by 100

**Comment by shanshin** [comment]
Please specify which CI do you use? If it supports XML reports for JaCoCo, then Kover XML reports will support the same CI features.

**Comment by Evleaps** [comment]
> Could you please specify which CI do you use? If it supports XML reports for JaCoCo, then Kover XML reports will support the same CI features.

@shanshin thank u for the explanation. 
I use GitHub actions on my project. 
I wanna set up the kover to our project. Personally, the most important feature is highlighting that a team member forgot to cover his code and CI shouldn't accept his PR for merge. 

As I understand, I should make my own script that keeps the current coverage percentage and increases this value every new PR. Something like Detekt's baseline.

**Comment by shanshin** [comment]
> As I understand, I should make my own script that keeps the current coverage percentage and increases this value every new PR. Something like Detekt's baseline.

Yes, if no such code has been written yet.
The Kover XML report is compatible with the JaCoCo XML report, so you can search for already written examples for it.

You may also wait for the implementation of #229 to easily get the percentage of coverage from the build log.
This task is in short-term planning, so it can be implemented in future releases.

**Comment by Evleaps** [comment]
Thank u for your answers.
