### ISSUE TITLE
Documentation page gives 404

### ISSUE THREAD

**Issue by jonapoul** [Kotlin/kotlinx-kover#350]
**Describe the bug**
Trying to access the Github Pages site for this repo (as linked in the README) gives a 404: https://kotlin.github.io/kotlinx-kover/

**Errors**
N/A

**Expected behavior**
N/A

**Reproducer**
N/A

**Reports**
![firefox_2023-04-22_23-49-46](https://user-images.githubusercontent.com/20978454/233810790-fa01973e-356a-4ae6-b4c1-a5191acec20f.png)

**Environment**
N/A

**Comment by shanshin** [comment]
Fixed
