### ISSUE TITLE
Multiplatform breakage

### ISSUE THREAD

**Issue by kmbisset89** [Kotlin/kotlinx-kover#352]
In a Kotlin Multiplatform project, when I apply id("org.jetbrains.kotlinx.kover"). The project no longer builds. 0.6.1 is fine and not having the plugin is fine.

**Comment by shanshin** [comment]
Hi,
could you please provide an error message along with a stack trace, if any, as well as a sample build script configuration?

**Comment by kmbisset89** [comment]
![image](https://user-images.githubusercontent.com/42785343/234076220-0ba36f88-a1e0-4424-8681-f69f553b3d1a.png)

I am using project modules in a Multiplatform application. As soon as I add the dependency the other modules cannot find the one that has Kover. 


Could not determine the dependencies of task ':firemissions:compileKotlinDesktop'.
> Could not resolve all task dependencies for configuration ':firemissions:desktopCompileClasspath'.
   > Could not resolve project :contacts.
     Required by:
         project :firemissions
      > The consumer was configured to find an API of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm', attribute 'fireMissionDesktop' with value 'DESKTOP'. However we cannot choose between the following variants of project :contacts:
          - desktopApiElements
          - desktopRuntimeElements
          - jvmApiElements
          - jvmRuntimeElements
          - koverArtifact
          - koverArtifactDebug
          - koverArtifactRelease
        All of them match the consumer attributes:
          - Variant 'desktopApiElements' capability mil.jtaps.contacts:contacts:1 declares an API of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Unmatched attributes:
                  - Provides attribute 'contactsDesktop' with value 'DESKTOP' but the consumer didn't ask for it
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Variant 'desktopRuntimeElements' capability mil.jtaps.contacts:contacts:1 declares a runtime of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Unmatched attributes:
                  - Provides attribute 'contactsDesktop' with value 'DESKTOP' but the consumer didn't ask for it
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Variant 'jvmApiElements' capability mil.jtaps.contacts:contacts:1 declares an API of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Unmatched attributes:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements' capability mil.jtaps.contacts:contacts:1 declares a runtime of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Unmatched attributes:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Variant 'koverArtifact' capability mil.jtaps.contacts:contacts:1:
              - Unmatched attributes:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides attribute 'kotlinx.kover.artifact.name' with value '' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.kotlin.plugin' with value 'MULTIPLATFORM' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.project.path' with value ':contacts' but the consumer didn't ask for it
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'koverArtifactDebug' capability mil.jtaps.contacts:contacts:1:
              - Unmatched attributes:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides attribute 'kotlinx.kover.android.build-type' with value 'debug' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.artifact.name' with value 'debug' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.kotlin.plugin' with value 'MULTIPLATFORM' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.project.path' with value ':contacts' but the consumer didn't ask for it
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'koverArtifactRelease' capability mil.jtaps.contacts:contacts:1:
              - Unmatched attributes:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
                  - Provides attribute 'kotlinx.kover.android.build-type' with value 'release' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.artifact.name' with value 'release' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.kotlin.plugin' with value 'MULTIPLATFORM' but the consumer didn't ask for it
                  - Provides attribute 'kotlinx.kover.project.path' with value ':contacts' but the consumer didn't ask for it
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'debugApiElements' capability mil.jtaps.contacts:contacts:1 declares an API of a library, preferably optimized for Android:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
              - Other compatible attribute:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
          - Variant 'debugRuntimeElements' capability mil.jtaps.contacts:contacts:1 declares a runtime of a library, preferably optimized for Android:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
              - Other compatible attribute:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
          - Variant 'metadataApiElements' capability mil.jtaps.contacts:contacts:1 declares a library, preferably optimized for non-jvm:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
              - Other compatible attribute:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
          - Variant 'releaseApiElements' capability mil.jtaps.contacts:contacts:1 declares an API of a library, preferably optimized for Android:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
              - Other compatible attribute:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')
          - Variant 'releaseRuntimeElements' capability mil.jtaps.contacts:contacts:1 declares a runtime of a library, preferably optimized for Android:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
              - Other compatible attribute:
                  - Doesn't say anything about fireMissionDesktop (required 'DESKTOP')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

**Comment by shanshin** [comment]
Is your project open source? Could you provide a reproducer or a link to the project?

**Comment by kmbisset89** [comment]
Unfortunately not opened source, but I will try to recreate smaller.

**Comment by shanshin** [comment]
@kmbisset89, please try version `0.7.0`

**Comment by shanshin** [comment]
Closing the issue.
Feel free to reopen this issue if the problem repeats in `0.7.2`.
