### ISSUE TITLE
Any breaking change between 0.7.0-Alpha and 0.7.0-Beta?

### ISSUE THREAD

**Issue by ashish12** [Kotlin/kotlinx-kover#356]
**Describe what you would like to clarify about Kover**

While trying to bump up `org.jetbrains.kotlinx:kover-gradle-plugin:0.7.0-Alpha` to use 0.7.0-Beta in a project with gradle convention plugin, the build fails with
```
Unresolved reference: disabledForProject
...
Unresolved reference: xml
...
Unresolved reference: onCheck
...
Unresolved reference: html
```

It is almost as if the plugin is not getting applied.

With 0.7.0-Alpha, there is no issue.

**Comment by ashish12** [comment]
Sample repository: https://github.com/ashish12/kover-sample, with the latest commit on 0.7.0-Beta, and the one before on 0.7.0-Alpha.

**Comment by shanshin** [comment]
Hi,
for Kotlin/JVM, Kotlin/Multiplatform projects you need to move `xml`, `html` or `verify` to `defaults` block, e.g.

was
```
koverReport {
    xml {
        // ...
    }
}
```
now
```
koverReport {
    defaults {
        xml {
            // ...
        }
    }
}
```

Property `disabledForProject` was renamed to `disable()` function

**Comment by ashish12** [comment]
Thanks. After making the above changes, it is working fine.

https://github.com/ashish12/kover-sample/actions/runs/4860032861/jobs/8663382630
