### ISSUE TITLE
applicationVariants/libraryVariants are eagerly evaluated and result in missed test data

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/kotlinx-kover#362]
**Describe the bug**
This code eagerly evaluates `applicationVariants`/`libraryVariants` in Android projects, and the result is that they have empty variants if the plugin is applied before the android variants are set up and the kover report task will be skipped due to no inputs.

https://github.com/Kotlin/kotlinx-kover/blob/9c36932dcc4e57dd1dc37463ffd1aa88242bb4e3/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/Android.kt#L28-L32

**Errors**
If present, stacktraces or files from `build/kover/errors` directory

**Expected behavior**
This API is old and the wrong API to use. Instead, the new `androidComponents.onVariants` API should be used, as this is a push system that will callback with each variant. This API is present in AGP 7.0 and later.

**Reproducer**
Easy to reproduce in a project that applies the kover plugin before configuring android variants.

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 0.7.0-Beta
 - Gradle version: 8.0.2/8.1.1
 - Kotlin project type: Kotlin/Android
 - Coverage Engine version (if customized in build script): N/A
 - Other context important for this bug: [e.g. OS version]

**Comment by ZacSweers** [comment]
I should mention I've verified the racy behavior by delaying applying the kover plugin behind an `afterEvaluate` block

**Comment by shanshin** [comment]
Great, thanks!

We will create improved locator for AGP >= 7.0

**Comment by shanshin** [comment]
Fixed in `0.7.2`.
