### ISSUE TITLE
Task 'koverXmlReport' will be skipped because no tests were executed in Android project on 0.7.0

### ISSUE THREAD

**Issue by Evleaps** [Kotlin/kotlinx-kover#364]
**Describe the bug**
A report is not generated for Android modules on version 0.7.0-Beta. But successfully generates on 0.6.1 
Note: a report generates for non-android modules successfully. 

// given 
- android module on non-multiplatform, but multimodule Android project. 
- unit tests exist in the Android module 

// when
- `:my_module:koverHtmlReport`

// then
- I see the error `Task 'koverXmlReport' will be skipped because no tests were executed`

if I run ./gradlew my_module:tasks I'll see 
<img width="661" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/26012758/2650ccf2-c8a6-48b6-b687-7b169142de92">

**Expected behavior**
Report generated

**Reproducer**

**build.gradle of my_module** 
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'org.jetbrains.kotlinx.kover'
}

android {
    compileSdkVersion COMPILE_SDK_VERSION

    defaultConfig {
        minSdkVersion MIN_SDK_VERSION
        targetSdkVersion COMPILE_SDK_VERSION

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
       
    }

    buildTypes {
        debug {
            testCoverageEnabled true
        }
        release {
            ...
        }
    }

    composeOptions {
        ...
    }
    buildFeatures {
        compose true
    }
    packagingOptions {
        ...
    }
}

dependencies {
    ...
}
```

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: [e.g. 0.7.0-Beta]
 - Gradle version: gradle-7.6-all
 - Kotlin project type: [Kotlin/Android]
 - Coverage Engine version: default
 - Other context important for this bug: [e.g. OS version] works fine on 0.6.1

**Comment by Evleaps** [comment]
@shanshin 
Unfortunately, I don't see commands with build variants. 

<img width="682" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/26012758/e7befbe1-a4d1-49ac-83a0-0a9bc7f0d780">


I don't want to merge my reports. I wanna see the report of each module separately. 
But if I run `my_module:koverHtmlReportDebug` I see  the error message: `... as task 'koverHtmlReportDebug' not found in project ':my_module'`

**Comment by shanshin** [comment]
> I don't want to merge my reports. I wanna see the report of each module separately.

in `0.7.0-Beta` block `mergeWith` does not result in merging with a report from another project (module), it only allows you to combine default reports  with a report for the Android build variant within the same project (module).

However, for some reason, the plugin did not "see" the build variants (possibly related to #362). 

Could you provide a small reproducer project?

**Comment by Evleaps** [comment]
I figured out why tasks weren't created. 

I additionally applied the plugin via `apply plugin: "org.jetbrains.kotlinx.kover"` in the build.gradle of the app level in the`allprojects { ... }` function. When I deleted it tasks were created. 
So, I should use only `plugins` for applying kover plugin. 


I think we can close this issue. It was due to my wrong configuration.

**Comment by shanshin** [comment]
> So, I should use only plugins for applying kover plugin.

`allprojects { ... }` should also work. I think it's related to #362.
I'm closing this task as a duplicate, but after fixing #362, it would be useful to recheck your project
