### ISSUE TITLE
Report is not regenerated when already existing

### ISSUE THREAD

**Issue by bakjoul** [Kotlin/kotlinx-kover#371]
Hello,

Noob question.
With JaCoCo when i update test classes, if i run its verification task, it will automatically generate and overwrite the previous report if there is any change. With Kover, i have to manually delete the previous report before generating a new one or it just won't generate.
Is there a configuration line i am missing to force the generation of a report when something has changed ?

**Comment by shanshin** [comment]
Hi,
could you clarify the version of Kover you are using, which Gradle task you are running, and which Kover report you want to generate?

**Comment by bakjoul** [comment]
Hi,
I'm using version 0.7.0-Beta and running koverHtmlReportDebug to get the debug report.

**Comment by shanshin** [comment]
What classes are you changing?
If you call `koverHtmlReportDebug`, the report will be regenerated only when the source code included in the `debug` build variant is changed.

If a class that is not related to `debug` changes, then the report generation task will be in the `UP-TO-DATE` state.

Gradle is engaged in tracking changes, the Kover task is only executed when any of the tasks on which it depends is executed (compilation of `debug` sources, local unit tests for `debug`)

**Comment by bakjoul** [comment]
I'm adding test classes in the unit test package. It's strange it seems to not detect the changes.

**Comment by armatys** [comment]
It seems like I have the same issue — I've written a more detailed description here: https://github.com/Kotlin/kotlinx-kover/issues/329#issuecomment-1553331242 (with a sample project).

**Comment by shanshin** [comment]
Fixed in `0.7.1`
