### ISSUE TITLE
Task with name koverXmlReport is unavailable to be appended to another task

### ISSUE THREAD

**Issue by gustavodaquino** [Kotlin/kotlinx-kover#375]
Hi, @shanshin. I have a question about the tasks created with the new version of Kover, `0.7.0`.

I usually create a named task called `jacocoTestReport` to execute the `koverXmlReport` task in the previous version due to a restriction I encountered in my CI environment.

However, after the upgrade, an error occurs because Gradle is unable to find the desired task.

```gradle
task("jacocoTestReport") {
    dependsOn(tasks.named("koverXmlReport"))
}
```

> Could not create task ':jacocoTestReport'.
> Task with name 'koverXmlReport' not found in root project com.xpto.test

Can you please help me with this issue?

**Comment by schowave** [comment]
I have the same problem regarding SonarQube. With 0.6.1, I was able to set the following:

tasks["sonar"].dependsOn(tasks.koverReport)

But the equivalent setting in 0.7.0 gives the same error as described above.

**Comment by shanshin** [comment]
Hi,
unfortunately, in version `0.7.0`, default Kover tasks are created in `afterEvaluate`.
This will be fixed in future versions, for now, as a workaround, you can move your code to this stage:
```
afterEvaluate {
    task("jacocoTestReport") {
        dependsOn(tasks.named("koverXmlReport"))
    }
}
```

or use a string task name:
```
task("jacocoTestReport") {
    dependsOn("koverXmlReport")
}
```
