### ISSUE TITLE
Unresolved references after upgrading to 0.7.0 from 0.7.0-Alpha

### ISSUE THREAD

**Issue by mjovanc** [Kotlin/kotlinx-kover#377]
**Describe the bug**
After updating dependency of Kover from `0.7.0-Alpha` to `0.7.0` into my Gradle Kotlin DSL project using Kotlin JVM with multiple modules I get unresolved references. 

**Errors**
<img width="760" alt="Skärmavbild 2023-05-21 kl  12 07 19" src="https://github.com/Kotlin/kotlinx-kover/assets/33717111/63ae018c-7f16-434b-9d54-7393e8b76a89">

<img width="376" alt="Skärmavbild 2023-05-21 kl  12 07 24" src="https://github.com/Kotlin/kotlinx-kover/assets/33717111/9055864d-50b2-4d72-bf33-d1e4d5f98fce">

<img width="532" alt="Skärmavbild 2023-05-21 kl  12 07 33" src="https://github.com/Kotlin/kotlinx-kover/assets/33717111/2f5ff326-f405-4ca1-a76e-4986831633a9">

**Expected behavior**
To be able to use Kover as I previously used except using the newer version.

**Reproducer**
Link to repo: https://github.com/kryptokrona/kryptokrona-kotlin-sdk

**Environment**
 - Kover Gradle Plugin version: 0.7.0
 - Gradle version: 8.1.1
 - Kotlin project type: Kotlin/JVM
 - Coverage Engine version (if customized in build script): KoverEngine("1.0.656")
 - Other context important for this bug: macOS Ventura 13.4
 - OpenJDK version: 17.0.6
 - Kotlin version: 1.8.21

**Comment by mjovanc** [comment]
I added back "0.7.0-Alpha" and it works perfectly.

**Comment by shanshin** [comment]
Hi,
when switching to 0.7.0, the default reports settings should be moved to the `defaults` block, e.g.
```
koverReport {
    defaults {
        verify {
            // verifications
        }
    }
}
```



also see [docs](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-jvm-project) and [example](https://github.com/Kotlin/kotlinx-kover/blob/main/examples/jvm/defaults/build.gradle.kts)

**Comment by mjovanc** [comment]
@shanshin Works great. Thanks (little late answer)!
