### ISSUE TITLE
How to exclude single/multiple test class file

### ISSUE THREAD

**Issue by mslalith** [Kotlin/kotlinx-kover#378]
I created `IgnoreInKoverReport` annotation and was excluding files which are not required in Kover report. Files are being ignored when they are in main sourceSet
```kotlin
koverReport {
    androidReports("debug") {
        filters {
            excludes {
                annotatedBy(
                    "*IgnoreInKoverReport"
                )
            }
        }
    }
}
```
Now I want to exclude below file which is under test sourceSet. `IgnoreInKoverReport` is not being picked up by Kover anymore. Any thoughts on how to exclude this?
```kotlin
@RunWith(RobolectricTestRunner::class)
@IgnoreInKoverReport
class MigrationTest {
    ...
}
```

**Comment by shanshin** [comment]
Hi,
could you clarify if the `MigrationTest` class gets into the HTML report? 
Is this class in a source set named `test'?

**Comment by mslalith** [comment]
yes, [MigrationTest](https://github.com/mslalith/focus_launcher/blob/develop/core/data/src/test/kotlin/dev/mslalith/focuslauncher/core/data/database/MigrationTest.kt) is under test sourceSet

I don't think test files are included in HTML report

**Comment by shanshin** [comment]
Please specify which classes do you want to exclude from HTML/XML reports?

Since the `MigrationTest` class is in the `test` source set, putting the `IgnoreInKoverReport` annotation on it will have no effect.

**Comment by mslalith** [comment]
Got it. Could there be any other way to exclude, AFAI understand Kover runs all the tests to generate Coverage report

**Comment by shanshin** [comment]
Unfortunately, Kover does not have the ability to control which tests are run, as well as to find out from which test a particular code was called (analyzing the call stack would take a very long time and greatly increase the class bytecode).

However, you can disable the tests yourself in build script when running with Kover, for example, if you pass a custom parameter when running the build.

**Comment by shanshin** [comment]
Closing as answered.
Feel free to open new issue if you have any additional questions.
