### ISSUE TITLE
Add a sample for android project with multi modules.

### ISSUE THREAD

**Issue by CoenQian** [Kotlin/kotlinx-kover#381]
**Describe what you would like to clarify about Kover**
I wonder if you can add a sample for android project with multi modules.

For example:
```
root
- app
- module1
- module2
```

1. module `app` includes `module1` and `module2`.
2. how to generate one kover report for the whole project? currently each module has a report in theirs 'build/reports/kover/' dir.
3. how to exclude specified module? `koverMerged.filters.projects` is usefuf in 0.6.1, but now it has been removed.

**Comment by CoenQian** [comment]
i have resolved question 2 by only configure once in module app and remove other kover configs from module1 and module2.

**Comment by shanshin** [comment]
Hi,
please refer [multiproject example](https://github.com/Kotlin/kotlinx-kover/tree/main/examples/android/multiproject) and [documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#multiproject-build).

To generate a report on several Gradle projects, you need:
- apply Kover plugin in each of these projects (modules)
- add a special dependency to the merging project (module) that will generate merged report (e.g. `dependency { kover(project(":module1")) }`)
- call the report generation task in the merging project (e.g. `:app:koverHtmlReport`)

**Comment by CoenQian** [comment]
thanks for reply
