### ISSUE TITLE
Exclude nested functions

### ISSUE THREAD

**Issue by mslalith** [Kotlin/kotlinx-kover#385]
**Describe the bug**
When we have a function which has nested functions and if parent function is excluded, the inner functions should also be excluded

**Expected behavior**
Nested functions should be excluded when parent function is excluded

**Reproducer**
Repo: [Focus Launcher](https://github.com/mslalith/focus_launcher/blob/develop/screens/currentplace/src/main/kotlin/dev/mslalith/focuslauncher/screens/currentplace/CurrentPlaceScreen.kt)

**Reports**
<img width="773" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/15076234/f981e777-20e3-4477-b0ee-3bdd4b4be21f">

**Environment**
 - Kover Gradle Plugin version: 0.7.0
 - Gradle version: 8.0.2
 - Kotlin project type: Kotlin/Android

**Comment by shanshin** [comment]
Please, try version `0.7.1`

**Comment by mslalith** [comment]
I still see it

<img width="769" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/15076234/d9f3b751-70fc-4305-ae75-81d2172863af">
