### ISSUE TITLE
`addWithDependencies` configuration not working in groovy gradle files

### ISSUE THREAD

**Issue by lachudra87** [Kotlin/kotlinx-kover#387]
**Describe the bug**
Cannot use kover `addWithDependencies` config for in groovy  gradle files.

`default` is keyword in groovy lang and below code is not compiling in `buid.gradle` groovy files
```
kover {
    default {
        addWithDependencies("debug")
    }
}
```
Feature was developed in this commit -> https://github.com/Kotlin/kotlinx-kover/commit/8e3298c68ca852f4e88b2d1929da1e116c9aecba

**Errors**
Not applicable

**Expected behavior**
API should be usable on both groovy and kotlin gradle files

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
Not applicable

**Environment**
 - Kover Gradle Plugin version: 0.7.0
 - Gradle version: 7.6
 - Kotlin project type: Kotlin/Android
 - Coverage Toolset (if customized in build script): Kover
 - Other context important for this bug: [e.g. OS version]

**Comment by shanshin** [comment]
Hi,
in `0.7.0` this function is called `mergeWith`, please refer [actual DSL description](https://kotlin.github.io/kotlinx-kover/gradle-plugin/dokka/-kover%20-gradle%20-plugin/kotlinx.kover.gradle.plugin.dsl/-kover-report-extension/defaults.html).

**Comment by shanshin** [comment]
Name `addWithDependencies ` turned out to be too long and not the most obvious

**Comment by lachudra87** [comment]
ok `mergeWith` works fine :)

But there is a bug in documentation as example for merge with is used with `kover` extension
```
kover {
     defaults {
         mergeWith("buildVariant")
     }
```

but it is actually part of `KoverReportExtension`

**Comment by shanshin** [comment]
Thanks, fixed )
