### ISSUE TITLE
koverVerify and koverXmlReport usage with 0.7.0-Alpha plugin version

### ISSUE THREAD

**Issue by alessandro-violante** [Kotlin/kotlinx-kover#389]
Hi, today in my project I've updated the version of the plugin from 0.5.0 version to 0.7.0-Alpha version because in my project I use several variants and I would have liked to generate the report only for one of them.

The command `gradle tasks` returns me the tasks "koverXmlReport" and "koverVerify" for all the single variants and environments as expected, but I'm encountering problems with the compilation of my old code and I can't find how to fix them.

I've already tried the code shown [here](https://github.com/Kotlin/kotlinx-kover/blob/main/examples/jvm/defaults/build.gradle.kts), but in my project my build.gradle files are not .kts files. They're just build.gradle (.gradle files), so this code doesn't work for me and it seems that the new tasks (koverVerifyDevVariantNameDebug and koverXmlReportDevVariantNameDebug) can't be used anymore as shown there).

That's the code:

`tasks.koverVerifyDevVariantNameDebug { rule { name = "Minimal line coverage rate in percents" bound { minValue = 33 } } excludes = ['*.json', '**/*test*/**'] }`

`tasks.koverXmlReportDevVariantNameDebug { excludes = ['*.json', '**/*test*/**'] }`

The tasks "koverVerifyDevVariantNameDebug" and "koverXmlReportDevVariantNameDebug" exist, but it seems they don't have to be implemented in this way anymore. 

Could you please write me an example of how should they be written now?

Thanks a lot in advance.

**Comment by alessandro-violante** [comment]
In the meanwhile, I've done some attempts on my own.

I've cloned the repository contained within this url: https://github.com/Kotlin/kotlinx-kover/tree/main
I've found an example of Kover (build.gradle not in Kotlin but in Groovy) for my application inside examples/android/minimal_groovy
In this folder there wasn't the gradle wrapper necessary to build "gradlew" with command line, so I've taken it from the root folder ("gradle" folder) and I put it inside the minimal_groovy folder
I've changed the Kover version from 0.7.0 to 0.7.0-Alpha
I've commented the Kover exclusions configuration code because otherwise I couldn't been able to execute the "gradlew tasks" command in order to get the list of Kover tasks available (Picture 1)
I've edited the exclusions configuration code changing "koverReport" with "koverXmlReportDebug", as "koverReport" doesn't exist anymore in the tasks list
I've tried to execute the task "gradlew" on the command line and an error has been returned (Picture2)
 
![Picture1](https://github.com/Kotlin/kotlinx-kover/assets/25792930/4fee3f51-9
![Picture2](https://github.com/Kotlin/kotlinx-kover/assets/25792930/253adb6d-4a8c-4193-9c42-ce4304a3d10e)
b3b-47b4-bb28-7ff8ea08720b)

**Comment by shanshin** [comment]
Hi, 
could you clarify why you are using the `0.7.0-Alpha` version instead of `0.7.0`?

> but in my project my build.gradle files are not .kts files. They're just build.gradle (.gradle files), so this code doesn't work for me

Examples of `kover` and `koverReport` block settings work unchanged for both `build.gradle` and `build.gradle.kts` files.

In version `0.7.x`, all Kover plugin settings occur only in extensions `kover` and `koverReport`, so there is no need to configure Kover Gradle tasks.

> I've edited the exclusions configuration code changing "koverReport" with "koverXmlReportDebug", as "koverReport" doesn't exist anymore in the tasks list

`koverReport` - is not the name of the task, it is an extension of the project that is used to configure all Kover reports. 

Please also refer to the [documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-android-project) for using the plugin.

**Comment by alessandro-violante** [comment]
Hi,

Thanks for the explanation. 

The reason why I'm trying to use the 0.7.0-Alpha version is that in my project I have a lot of flavors and it takes me a lot of time to generate the Kover report for all of them (about 1 hour). 

I've seen that in 0.7.0-Alpha version there are specific Gradle tasks available for each flavor (for example: "koverReportDevVariantNameDebug"). I've tried to generate the report with that Kover version and that specific Gradle task and without any additional configuration (i.e. build.gradle koverReport exclusions and so on) and I've generated the report in about 15 seconds.

It's great for me, but I necessarily have to filter the report so that some files are excluded, so I necessarily have to configure "koverReport" in my build.gradle file to exclude some folders and files.

The problem is that, if as you say I use "koverReport" as described in the example file and I execute the "gradlew" task, I get the error I attach you in Picture 1:

![Picture_1-0 7 0-Alpha](https://github.com/Kotlin/kotlinx-kover/assets/25792930/46887ebe-1bdd-44d6-84c9-cff64d4edd56)

It seems like in 0.7.0-Alpha version the configuration should be different, as the error reports that the method androidReports() can't be found. 

How should I configure "koverReport" using 0.7.0-Alpha version?

Best regards

**Comment by shanshin** [comment]
> It seems like in 0.7.0-Alpha version the configuration should be different, as the error reports that the method androidReports() can't be found.

Yes, because the documentation is for the latest version - `0.7.0`

> I've seen that in 0.7.0-Alpha version there are specific Gradle tasks available for each flavor

Version `0.7.0` works the same way.

> It's great for me, but I necessarily have to filter the report so that some files are excluded

The easiest way is to add filters for all build variants:
```
koverReport {
    filters {
        excludes {
            classes("some.packg.FqClassN*",  "*.Class2")
        }
    }
}
```

However, please note, due to technical limitations, Kover can filter only by class names,  but not by file names, directories, as well as directory separators - it is not allowed. Also [see](https://kotlin.github.io/kotlinx-kover/gradle-plugin/configuring#reports-filtering)

**Comment by alessandro-violante** [comment]
Hi, 

Thanks for the explanation.

Now I'm using 0.7.0 version of the plugin, but when building my project I'm encountering the error I attach you in Picture 1:

![Picture1](https://github.com/Kotlin/kotlinx-kover/assets/25792930/f8448c5c-3bbc-42c9-bd8a-0605b8af081a)

I also attach you my build.gradle and app/build.gradle files. 

build.gradle
[build.gradle.txt](https://github.com/Kotlin/kotlinx-kover/files/11624391/build.gradle.txt)

app/build.gradle
[app-build.gradle.txt](https://github.com/Kotlin/kotlinx-kover/files/11624397/app-build.gradle.txt)

They seem quite similar to those contained in the example project, and I can't understand what the problem could be.

Let me know if you also need settings.gradle and gradle.properties. They're very similar to those used in the example.

Thanks a lot in advance:

**Comment by shanshin** [comment]
Please, try version `0.7.1` - it should solve the problem with `org/gradle/configurationcache/extensions/CharSequenceExtensionsKt`

**Comment by alessandro-violante** [comment]
Hi!

Yes, thank you, 0.7.1 has fixed the problem, but as you can see in the attachment, I don't see the tasks differentiated by flavor.

Version 0.7.1
![kover-0 7 1](https://github.com/Kotlin/kotlinx-kover/assets/25792930/dbfcabd5-67da-47d7-a920-90f250ce3f63)

In the tasks list I don't see the feature "Added support of Android build variants". Am I doing something wrong?

Could you please check?

Best regards

**Comment by shanshin** [comment]
The tasks shown in the screenshot are missing in version `0.7.1`. Please recheck the correctness of the version, you may have specified `0.6.1`
