### ISSUE TITLE
Does not show up in SonarQube

### ISSUE THREAD

**Issue by AshStefanOltmann** [Kotlin/kotlinx-kover#39]
I configured my SonarQube plugin to use the report.xml Kover produces as JaCoCo coverage file, but results do not show up.

Do I have to configure something special to make the report.xml compatible where JaCoCo is expected?

```
    sonarqube {
        properties {

            // Include Kover Coverage
            val koverPath = "${project.buildDir}/reports/kover/report.xml"
            println("Kover report: $koverPath")
            property("sonar.coverage.jacoco.xmlReportPaths", koverPath)
        }
    }
```

**Comment by AshStefanOltmann** [comment]
Ok, I got it working.

**Comment by ethauvin** [comment]
> Ok, I got it working.

What did you do to make it work?

**Comment by AshStefanOltmann** [comment]
> > Ok, I got it working.
> 
> What did you do to make it work?

I just updated to the current verisons of the SonarQube and Kover gradle plugins.

**Comment by JavierSegoviaCordoba** [comment]
I am unable to get it working, I add a repro.

https://github.com/Reproducers/kover-repro

**Comment by JavierSegoviaCordoba** [comment]
Caused by https://github.com/Kotlin/kotlinx-kover/issues/99
