### ISSUE TITLE
How to exclude classes with kotlinx.serialization.Serializable?

### ISSUE THREAD

**Issue by pavel163** [Kotlin/kotlinx-kover#390]
**Hi. I have a class with kotlinx.serialization.Serializable in jvm module. I would like to exclude it from kover report. I added  kotlinx.serialization.Serializable into annotatedBy function**

<img width="619" alt="Снимок экрана 2023-05-30 в 18 47 36" src="https://github.com/Kotlin/kotlinx-kover/assets/9054609/12dd1857-779b-4575-bf54-54f30ed7775d">

**but I got this one**

<img width="336" alt="Снимок экрана 2023-05-30 в 18 45 06" src="https://github.com/Kotlin/kotlinx-kover/assets/9054609/73371d9d-4bb1-4de1-9926-1b3631b0442f">
<img width="820" alt="Снимок экрана 2023-05-30 в 18 45 25" src="https://github.com/Kotlin/kotlinx-kover/assets/9054609/21ea10de-3e18-4667-993d-34299d4fb581">

What did I wrong? 

kover: 0.7.0

**Comment by shanshin** [comment]
Duplicates #331
