### ISSUE TITLE
Tests are not executed

### ISSUE THREAD

**Issue by vassilisimon** [Kotlin/kotlinx-kover#391]
Hello,

When I run :app:koverXmlReport I always get: 

> Task :app:koverXmlReport SKIPPED
Task 'koverXmlReport' will be skipped because no tests were executed

So also sonarqube complains: 
> No coverage report can be found with sonar.coverage.jacoco.xmlReportPaths='/builds/os/now/abc-android//build/reports/kover/report.xml'. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml

My minimal setup: 

**build.gradle.kts (:app)**

```
plugins {
... 
id("org.jetbrains.kotlinx.kover")
}
```

```
dependencies {
    kover(project(":ui:mobile:xy"))
}

koverReport {
    // filters for all report types of all build variants
    filters {
        excludes {
            classes(
                "*Fragment",
                "*Fragment\$*",
                "*Activity",
                "*Activity\$*",
                "*.databinding.*",
                "*.BuildConfig"
            )
        }
    }
    defaults {
        xml {
            setReportFile(layout.buildDirectory.file("reports/kover/report.xml"))
        }
    }
}
```

**build.gradle.kts (root)** 
```
plugins {
id("org.jetbrains.kotlinx.kover") version 0.7.0
}

subprojects {
apply(plugin = "org.jetbrains.kotlinx.kover")
...
}

sonarqube {
    properties {
        property("sonar.coverage.jacoco.xmlReportPaths", "$buildDir/reports/kover/report.xml")
    }
}

tasks.findByName("sonarqube")?.dependsOn("koverXmlReport")
```

Do you have an idea how to trigger the tests?

**Comment by realdadfish** [comment]
I think there is a workaround mentioned in #362

**Comment by shanshin** [comment]
Hi,
@vassilisimon , is using `tasks.findByName("sonarqube")?.dependsOn("koverXmlReportDebug")` and either calling `:app:koverXmlReportDebug` applicable to you?

**Comment by shanshin** [comment]
`afterEvaluate {` It may not solve similar problems, because it will be executed in the same order in which the plugins were applied.

**Comment by shanshin** [comment]
> How can I apply the kover plugin after AGP? It's currently applied in the subprojects block.

At the moment, the most effective workflow is to apply the plugin explicitly in each project, instead of specifying `subprojects`.

So you can explicitly specify the order of applying of plugins, e.g.
```
plugins {
    id ("com.android.application")
    id ("org.jetbrains.kotlin.android")
    id ("org.jetbrains.kotlinx.kover")
}
```

**Comment by mluscherdd** [comment]
I was able to work around this issue by using the legacy way of applying the plugin, although not ideal:
(tested on Android projects only)
```kotlin
dependencies {
    classpath("org.jetbrains.kotlinx:kover-gradle-plugin:0.7.1")
}
subprojects {
    plugins.withType<AndroidBasePlugin> {
        apply(plugin = "org.jetbrains.kotlinx.kover")
        // Full disclosure: I wasn't able to get this work given the time I had, 
        // but if someone noodles on it, it would be really nice.
        extensions.configure(KoverReportExtension::class.java) {
            androidReports("debug") {
                filters {
                    excludes {
                        packages("androidx.*")
                    }
                }
            }
        }
    }
}
```

**Comment by shanshin** [comment]
@vassilisimon, could you please check version `0.7.2`?

**Comment by shanshin** [comment]
> Kover doesn't execute all unit tests we have, only ~500 out of ~3200).

It looks like this is because the tests were run only for JVM targets.
In order to run tests for any build variant when executing `koverXmlReport`, it is worth adding `mergeWith("...")`

>  Failed to create MD5 hash for file '/usr/bin/sudo' as it does not exist.
Have you added `kover(project("..."))` dependencies for the`:app` project?

**Comment by shanshin** [comment]
```
* What went wrong:
Execution failed for task ':app:koverXmlReport'.
> Cannot access input property 'localSources$kover_gradle_plugin' of task ':app:koverXmlReport'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). See https://docs.gradle.org/8.1.1/userguide/incremental_build.html#disable-state-tracking for more details.
   > Failed to create MD5 hash for file '/usr/bin/sudo' as it does not exist.
```

Could you show the contents of the `app/build/kover/default.artifact` file for this case? 
I wonder if there is a mention of `/usr/bin/sudo` there

**Comment by shanshin** [comment]
@vassilisimon 

> this.doNotTrackState("Dont support state tracking")

With this setting, the tests run successfully and a correct report is generated?

**Comment by shanshin** [comment]
In this case, I think the current task should be closed.

if the specified workaround will cause any inconvenience, then it is worth create a separate issue for this.
But since this is a very rare problem, in this case we need more information about the environment to understand the reasons why Gradle processes the `/usr/bin/sudo` file.

**Comment by raamcosta** [comment]
What I got today:

FAILURE: Build failed with an exception.

> * What went wrong:
Execution failed for task ':app:koverVerify'.
> Cannot access input property 'localSources$kover_gradle_plugin' of task ':app:koverVerify'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). See https://docs.gradle.org/8.1/userguide/incremental_build.html#disable-state-tracking for more details.
   > java.nio.file.FileSystemException: /System/Volumes/Data/home: Operation not permitted

I'm sorry I will add here as I go, I hope it can be somehow a bit helpful 🙏

**Comment by raamcosta** [comment]
New update:

I did what the above error said to do and I managed to do everything except html report which fails with this error:
```
[2023.07.21 14:00:26] (Coverage): Failed to check raw report file: java.io.FileNotFoundException: /home/runner/.gradle/daemon/8.1 (Is a directory)
> Task :app:koverHtmlReport
Kover: HTML report for ':app' file:///home/runner/work/my-projectn/my-project/app/build/reports/kover/html/index.html
[2023.07.21 14:00:28] (Coverage): Failed to load coverage data from file: /home/runner/.gradle/daemon/8.1: java.io.FileNotFoundException: /home/runner/.gradle/daemon/8.1 (Is a directory)
```
