### ISSUE TITLE
Migration from 0.6 to 0.7

### ISSUE THREAD

**Issue by emartynov** [Kotlin/kotlinx-kover#393]
**Describe what you would like to clarify about Kover**
We used `isDisabled.set(true)` before. I read the migration guide but I can not make it passed gradle evaluation:
```
android {
 testOptions {
  unitTests.all {
                        def ignoredTestTasks = ["testReleaseUnitTest", "testStagingUnitTest"]
                        if (ignoredTestTasks.contains(name)) {
                            kover {
                                disable() <- here is the problem
                            }
                        }
                    }
  }
}
```

**Comment by shanshin** [comment]
Hi,
could you clarify what kind of result you would like to get?

```
kover {
  disable()
}
```
disables instrumentation for all tests in the project. 

If you need to generate a report for only one build variant, it is enough to call the Gradle command e.g. `koverHtmlReportDebug`.

In order not to take into account the test coverage from the specified task, it is necessary to configure the measurement
```
kover {
    excludeTests {
        tasks("excludedTestTaskName")
    }
}
```

**Comment by emartynov** [comment]
Let me close it since we decided to pause migration and return to this functionality's roots. Thank you for the quick replay, and sorry for the noise.
