### ISSUE TITLE
[koverVerify] Projects with no tests are skipped

### ISSUE THREAD

**Issue by alexandrefavre4** [Kotlin/kotlinx-kover#401]
Hi there,

I configured a 80% line coverage rule on some subprojects. Among these subprojects, some don't have any tests but `koverVerify` terminates successfully because Kover is skipping them: `Task 'koverVerify' will be skipped because no tests were executed`

As the 80% line coverage rule has not been met for these subprojects, I would have expected `koverVerify` to fail.

Did I miss an option that would make it fail in this situation? If not, is this a change you would consider making to Kover?

Cheers!

**Comment by shanshin** [comment]
Hi,
if no [dependency is specified](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#single-report-over-several-projects), then only those tests that are declared in the same project are used for calculating coverage.

When there is cross-testing between subprojects, it is recommended to use a combined report on several subprojects.

**Comment by alexandrefavre4** [comment]
@shanshin I'm not cross-testing between subprojects. I've configured the rule to be applied to each subproject individually. I get the same result if I run `koverVerify` on a single subproject (`./gradlew :mysubproject:koverVerify`). Kover is still skipping verification as `mysubproject` has no tests.

**Comment by shanshin** [comment]
> Kover is still skipping verification as mysubproject has no tests.

Kover uses only tests that are declared in the same project, and does not know in advance whether any other projects can test his classes.

To do this, add a dependency
```
dependency {
    kover(project(":projectTestingMyClasses"))
}
```
so that when executing reports, the results of running tests from specified projects are taken into account.

As a side effect, the report will take into account classes from the specified dependency. If there is such a possibility, then these classes can be filtered by package.

**Comment by shanshin** [comment]
Perhaps a design is needed on the question of what to do if there are no tests in the project.

**Comment by alexandrefavre4** [comment]
Yes, I think that would make sense.

**Comment by quanturium** [comment]
+1 to being able to configure what to do when tests are not there. In our use case, we want a report to show 0% coverage when nothing is there so that we can post-process and track those over time.

**Comment by shanshin** [comment]
Closing the issue as a duplicate, you can follow the progress of the https://github.com/Kotlin/kotlinx-kover/issues/409 task.
