### ISSUE TITLE
./gradlew koverReport does not work anymore after migrating to 0.7

### ISSUE THREAD

**Issue by imdatcandan** [Kotlin/kotlinx-kover#402]
**Describe the bug**
./gradlew koverReport does not work after migrating to 0.7, I can do this but this is not maintanable so do you have any idea how to fix it?

command: ./gradlew koverHtmlReportInternalDebug koverHtmlReportProductionDebug koverXmlReportInternalDebug koverXmlReportProductionDebug

**Errors**
* What went wrong:
Task 'koverReport' is ambiguous in root project 'Capmo' and its subprojects. Candidates are: 'koverHtmlReport', 'koverHtmlReportInternalDebug', 'koverHtmlReportInternalRelease', 'koverHtmlReportProductionDebug', 'koverHtmlReportProductionRelease', 'koverXmlReport', 'koverXmlReportInternalDebug', 'koverXmlReportInternalRelease', 'koverXmlReportProductionDebug', 'koverXmlReportProductionRelease'.

**Expected behavior**

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: [0.7.0]
 - Gradle version: [8.1.1]
 - Kotlin project type: [e.g. Kotlin/JVM, Kotlin/Multiplatform, Kotlin/Android,  Kotlin/Multiplatform + Android]
 - Coverage Toolset (if customized in build script): [e.g. Kover, JaCoCo, JaCoCo("0.8.10")]
 - Other context important for this bug: [e.g. OS version]

**Comment by shanshin** [comment]
Hi,
starting from version `0.7.0`, each build variant has its own report generation task.
Could you clarify, do you need to get a report separately for each build variant or would you like to generate a merged report for all variants?

**Comment by shanshin** [comment]
Try to merge all the build variants in the Kover default report
```
koverReport {
    defaults {
        mergeWith("internalDebug")
        mergeWith("productionDebug")
    }
}
```

If you will not face issue #362 then calling `koverHtmlReport` and `koverXmlReport` tasks will generate merged reports.

Also keep in mind that generating a report on several build variants can lead to errors if a class with the same name is declared in few variants.
