### ISSUE TITLE
Example of koverVerify usage with "Minimal line coverage rate in percents" rule in 0.7.1

### ISSUE THREAD

**Issue by alessandro-violante** [Kotlin/kotlinx-kover#404]
Hi,

I'm writing because I've searched on the whole library examples and I haven't been able to find an example of the usage of the "Minimal line coverage rate in percents" koverVerify rule in Kover 0.7.1 version.

In version 0.5.0 it was written in this way:

`koverVerify { rule { name = "Minimal line coverage rate in percents" bound { minValue = 33 } } }`

In 0.7.1 version, it generates an error during compilation.

How should it be written now?

Thanks a lot,

Kind regards

**Comment by shanshin** [comment]
Hi,
Please refer to [this example](https://github.com/Kotlin/kotlinx-kover/blob/v0.7.1/examples/jvm/defaults/build.gradle.kts) and [documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/configuring#configuring-default-reports).

To add validation rules, you now need to configure the `koverReport` project extension, e.g. for JVM projects
```
koverReport {
    defaults {
        verify {
            rule("Minimal line coverage rate in percents") {
                minBound(33)
            }
        }
    }
}
```

**Comment by alessandro-violante** [comment]
Hi,

Maybe I didn't understand everything.

Should I write the whole configuration you have linked me in my project or is it the default Kover configuration? 

Assuming I have to write that configuration, if I run the gradlew task, I get the error I attach you in Picture 1:

![Picture_1](https://github.com/Kotlin/kotlinx-kover/assets/25792930/950e20f1-0241-4d80-ab54-c370ce7872dc)

If that's the default configuration and I only eventually have to override the value of "minBound" as in the code you've written me in your comment, although my percentage coverage is less than 33%, my build is always successful.

That's the example of my code:

```

koverReport {
    defaults {
        verify {
            rule("Minimal line coverage rate in percents") {
                minBound(33)

                filters {
                    excludes {
                        classes(
                                '*.json'
                        )
                    }
                }
            }
        }
    }
    // filters for all report types of all build variants
    filters {
        excludes {
            classes(
                    '*.json'
            )
        }
    }
}

```

I exexute the following tasks:

`gradlew testDevFlavorNameDebugUnitTest koverVerifyDevFlavorNameDebug`

In testDevFlavorNameDebugUnitTest I execute the Unit Tests.

Kind regards

**Comment by alessandro-violante** [comment]
Hi, 

The name of the variant is correct, but the build keeps on being successful, although the percentage of coverage of my code is lower than that set in the rule. 

The build should fail, maybe I could be missing something?

**Comment by shanshin** [comment]
Can you call `koverHtmlReportDevFlavorNameDebug`, what is the total coverage value in the report?

**Comment by alessandro-violante** [comment]
Hi,

It's 0%.

![kover-html-report](https://github.com/Kotlin/kotlinx-kover/assets/25792930/73be6d4d-0df3-463b-a0e8-42394b19edcf)

**Comment by shanshin** [comment]
Could you show how the kover and the android plugins are applied?

Perhaps the problem is related to #362

**Comment by shanshin** [comment]
Great!
In the next version, we will definitely add a build variant name check.
