### ISSUE TITLE
Migration to 0.7.1 for multiple projects repo

### ISSUE THREAD

**Issue by alinaeftn** [Kotlin/kotlinx-kover#407]
Hello,

I am trying to upgrade from 0.6.1 to 0.7.1 and I get an error for the Kover Report when adding projects as dependencies.

Kover version: 0.7.1
Gradle version: 7.6.1

Config from build.gradle.kts in root:

```
plugins {
    ...
    id("org.jetbrains.kotlinx.kover")
   ...
}


kover {
    useJacoco("0.8.8")
}

dependencies {
    kover(project(":runtime"))
    kover(project(":commons"))
}

// Aggregated code coverage report
koverReport {
    filters {
        excludes {
            classes(
                "jdk.internal.*"
            )
        }
    }
    defaults {
        xml {
            setReportFile(layout.buildDirectory.file("$buildDir/reports/kover/xml/report.xml"))
        }
        html {
        }
    }
}
```

I have no other Kover setting in the other projects.

The error is:

```
Execution failed for task ':koverXmlReport'.
> Unable to read execution data file /Users/eftenoiu/Documents/git/<project_name>/commons/build/kover/raw-reports/test.ic
```

Can someone help me understand if this is a bug or I am doing something wrong?

Thanks!

**Comment by shanshin** [comment]
Hi,
if you change coverage tool, then it should be changed in all projects.

That is, you should to specify in `runtime` and `commons`:
```
kover {
    useJacoco("0.8.8")
}
```

**Comment by alinaeftn** [comment]
@shanshin , that worked, thank you!

**Comment by shanshin** [comment]
Closing as answered.
Feel free to open new issue if you have any additional questions.
