### ISSUE TITLE
How to produce a kover report for modules that don't contain any tests

### ISSUE THREAD

**Issue by quanturium** [Kotlin/kotlinx-kover#408]
Hello,

We have a project composed of many JVM, android, kmp modules and we are post-processing the XML report into a DB to track progress on code coverage. When running koverXmlReport on a module that doesn't contain any test, I'd get the following message:

```
> Task :x:koverXmlReport SKIPPED
Task 'koverXmlReport' will be skipped because no tests were executed
```

We'd like to get coverage reports even for modules with no tests since they essentially mean no coverage yet. We want to be able to generate the XML report from those modules lacking tests. Essentially a report showing 0% coverage but containing all classes / number of lines that are not covered. 

With 0.6.x, I was able to do that by adding a srcDir (containing an empty placeholder kotlin file) to the test sourceSet of each module so that it would generate an empty report containing all the info we need. 

```
private fun configureProjectTestSourceSets(project: Project) = with(project) {
        withJavaPlugin {
            extensions.configure<SourceSetContainer> {
                maybeCreate("test").java.srcDir(
                    project.gradle.rootProject.file(placeholderTestSourceSetPath)
                )
            }
        }

        withAndroidPlugin {
            extensions.configure<BaseExtension> {
                sourceSets.maybeCreate("testDebug").java.srcDir(
                    project.gradle.rootProject.file(placeholderTestSourceSetPath)
                )
            }
        }

        withKmpPlugin {
            extensions.configure<KotlinMultiplatformExtension> {
                sourceSets.maybeCreate("commonTest").kotlin.srcDir(
                    project.gradle.rootProject.file(placeholderTestSourceSetPath)
                )
            }
        }
    }
```

With 0.7.x, this no longer works. The .ic file is only generated if my test sourceset contains at least one test. I can modify the above to add a test dependency on junit + modify the placeholder kotlin test file to contain a single empty test, but this is becoming quite hacky. 

I'm looking for suggestions on how else I could achieve the above and as a result generate a xml report of a specific module containing no tests.

**Comment by shanshin** [comment]
This task will be closed, you can follow the progress of the #409 task.
