### ISSUE TITLE
Cannot specify which android flavor to use?

### ISSUE THREAD

**Issue by tordjon** [Kotlin/kotlinx-kover#41]
With 0.3.0 I was able to generate coverage only for a specific flavor eg. PaidDebug, I don't quite remember, but I believe it was by something like testPaidDebugUnitTest..

However with the latest version I must run koverXmlReport, which builds and runs on all my flavor combinations?

What am I missing here?

**Comment by proto-mvp** [comment]
Same here, I am trying to run the tool coverage but keeps running all the available flavours which fail, the project is not configured to do so, and I can't see any report published.

**Comment by gerardoepitacio** [comment]
Testing in 0.4.1, and is not be able to reach resources in a specific build type.
**Unresolved reference: <resource_in_an_specific_build_type>**

**Comment by shanshin** [comment]
Hi,
> However with the latest version I must run koverXmlReport, which builds and runs on all my flavor combinations?

Yes, now the API for working with Android flavors is under development (#18), so all instrumented tests are being run.
You can exclude any test from running when executing `koverXmlReport` if you disable its instrumentation (`build.gradle` example):
```
android {
    // other Android declarations

    testOptions {
        unitTests.all {
            if (name == "testDebugUnitTest") {
                kover {
                    enabled = false
                }
            }
        }
    }
}
```

**Comment by shanshin** [comment]
> Testing in 0.4.1, and is not be able to reach resources in a specific build type.

May you clarify your build script and which resources cannot be reached?

**Comment by gerardoepitacio** [comment]
while writing a minimal reproducible scenario I reached, #69 , waiting for the fix to try again.

**Comment by shanshin** [comment]
Duplicates #18

**Comment by gerardoepitacio** [comment]
How can apply ignoring flavor specific tests in the root/project build.gradle file?

**Comment by Gerardoeg** [comment]
Related to #187
