### ISSUE TITLE
Add markdown summary report

### ISSUE THREAD

**Issue by efenderbosch-atg** [Kotlin/kotlinx-kover#419]
**What is your use-case and why do you need this feature?**
I'd like a `kover/report.md` that would be appropriate for use as a PR comment via github actions, just the "Overall Coverage Summary" from the HTML report would be great.

Maybe I can grab the HTML? Git hub will format it like this:

<table class="coverageStats">
  <tr>
    <th class="name">Package</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Branch, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
<th class="coverageStat 
">
  Instruction, %
</th>
  </tr>
  <tr>
    <td class="name">all classes</td>
<td class="coverageStat">
  <span class="percent">
    97.5%
  </span>
  <span class="absValue">
    (79/81)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    94.3%
  </span>
  <span class="absValue">
    (181/192)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    89.4%
  </span>
  <span class="absValue">
    (93/104)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    98.4%
  </span>
  <span class="absValue">
    (569/578)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    98.4%
  </span>
  <span class="absValue">
    (3388/3443)
  </span>
</td>
  </tr>
</table>

**Comment by efenderbosch-atg** [comment]
As markdown it could look like

foo-project: Overall Coverage Summary
====================================================

| Package | Class, % | Method, % | Branch, % | Line, % | Instruction, % |
| --- | --- | --- | --- | --- | --- |
| all classes | 97.6% (80/82) | 94.1% (176/187) | 88.8% (87/98) | 98.5% (543/551) | 97.2% (3258/3351) |

**Comment by efenderbosch-atg** [comment]
For now, I'm grabbing the summary w/ `sed` then formatting it as markdown w/ `pandoc` as a workaround:

```bash
sed -n '/<h1>foo-bar-service: Overall Coverage Summary <\/h1>/,/<br\/>/p' build/reports/kover/html/index.html | pandoc -f html -t gfm >> $GITHUB_STEP_SUMMARY
```

**Comment by shanshin** [comment]
Closed in favor of https://github.com/Kotlin/kotlinx-kover/issues/605
