### ISSUE TITLE
Create git tags for all releases

### ISSUE THREAD

**Issue by jonasfa** [Kotlin/kotlinx-kover#42]
Right now it's difficult to browse releases' source code, compare releases (changes), etc on GitHub because the repository is lacking [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging). Downloading sources.jar from Maven Central is not convenient.

**Comment by shanshin** [comment]
Tags added for releases in Maven Central.

**Comment by jonasfa** [comment]
Thank you!
