### ISSUE TITLE
Make a path for the resulting .ic report configurable

### ISSUE THREAD

**Issue by hybloid** [Kotlin/kotlinx-kover#423]
**What is your use-case and why do you need this feature?**
In order to configure Qodana Code Coverage, we need to store ic report in the particular folder (probably having some particular name).

**Describe the solution you'd like**
Being able to configure the output path like we have it for XML reports now.
Having a separate task to generate such a file.

**Comment by shanshin** [comment]
Implemented in `0.7.3`
