### ISSUE TITLE
Is it possible to merge a kover report for multi-module multiplatform project?

### ISSUE THREAD

**Issue by stantronic** [Kotlin/kotlinx-kover#428]
**Describe what you would like to clarify about Kover**

Hi. Thanks for all your hard work Kover is great 👍🏻 

However I am currently working on a project that consists of multiple gradle modules, which each use the kotlin multi-platform plugin.

I would like to generate some merged coverage reports,

however when I add the kover function, it seems to not be recognised...
e.g.
```kotlin
sourceSets {
  val commonMain by getting {
    dependencies {
        kover(project(":other:project")) // kover function not recognised
       //...
    }
  }
 //....
}

```

Is what I want possible at the moment? 

Many thanks :)

**Comment by shanshin** [comment]
Hi, thanks! :)

To use coverage from another project, you need to add a kover dependency to the `dependencies` block, which is located in the root of the script, for example
```
dependencies {
  kover(project(":other:project")) 
}

sourceSets {
  val commonMain by getting {
    // ...
  }
 //....
}
```

Also keep in mind that if there is an Android target in the project, then for each build variant, its own Kover report generation tasks are created, see [docs](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-multiplatform-project)

**Comment by stantronic** [comment]
Aha. great! thanks for quick reply. works great :)
