### ISSUE TITLE
Add a combined report for a multi-module build

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx-kover#43]
It would be useful to have a single combined result dashboard for the whole project consisting of multiple subprojects.

**Comment by shanshin** [comment]
Cross-module reports design is in process (#20).
It would be great if you write use cases from your project.

**Comment by altavir** [comment]
Our test coverage is not very good right now and it would be a good task to gradually improve it. But we have a lot of modules and it would be good to understand where to focus first. Looking into a dashboard for all modules, we can decide if we want to focus on some modules first or if we need to raise coverage gradually in all modules. 

Also one needs to take into account #16 or any other shield-generating tool. It usually provides a single number for the project.

**Comment by mustafaozhan** [comment]
So the use case for me, I have multimodule project also, it is KMP project but for the android side it shouldn't really matter, I would like to have a single report.xml file combined with all the modules in app.

**Comment by shanshin** [comment]
Implemented in `0.5.0-RC`.
