### ISSUE TITLE
0.7.2 does not support multiplatform

### ISSUE THREAD

**Issue by hxxyyangyong** [Kotlin/kotlinx-kover#434]
i update 0.6.1 to 0.7.2
 
![image](https://github.com/Kotlin/kotlinx-kover/assets/1219331/9934332e-fe12-4adc-86ba-1ea853817916)

There were android and common before, but now there is nothing

But it informs that 0.7.0 is already supported

![image](https://github.com/Kotlin/kotlinx-kover/assets/1219331/30a21373-f28d-4dc9-a311-0558ab446a42)

What separate configuration is required?

**Comment by shanshin** [comment]
Hi
please migrate your project from 0.6.x to 0.7.x, see [migration guide](https://kotlin.github.io/kotlinx-kover/gradle-plugin/migrations/migration-to-0.7.0) for more info.

The answers to these tasks can also help you: #422, #402, #393. 

Example of [multiproject build](https://github.com/Kotlin/kotlinx-kover/tree/main/kover-gradle-plugin/examples/android/multiplatform) will be useful.

**Comment by shanshin** [comment]
>  but I didn't find the data under ios Main

Unfortunately, at the moment only JVM and Android targets are supported. The iOS code will not be included in the report.

**Comment by hxxyyangyong** [comment]
That said, it should not be multiplatform，iOSMain is also part of it, and I can also pass the test. It also has its own test function. It can pass and generate test products. Do you just need to add this part of the test?

**Comment by shanshin** [comment]
> Do you just need to add this part of the test?

In the future, it is necessary to add instrumentation of native iOS code so that it is possible to collect coverage with tests run on iOS devices.

Adding instrumentation for native targets are in long-term plans #293.

**Comment by shanshin** [comment]
Closing as answered.
Feel free to open new issue if you have any additional questions.
