### ISSUE TITLE
excluding by annotation does not work

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx-kover#448]
**Describe the bug**

I tried to use the `annotatedBy` method in `excludes`, but it did not work as expected.

**Expected behavior**

I should be able to exclude the problematic functions or files with annotations.

**Reproducer**

See https://github.com/Kotlin/kotlinx-kover/issues/447

**Environment**
 - Kover Gradle Plugin version: 0.7.3
 - Gradle version: 8.2.1
 - Kotlin project type: Kotlin/Jvm with a dependency on the Gradle API (basically a gradle plugin)
 - Coverage Toolset: Kover
 - OS: MacOS

**Comment by shanshin** [comment]
Hi, sorry for the delayed answer.
Could you clarify exactly how you check whether the `register` function has been excluded or not?
In an HTML report, or are you visualizing an XML report through extarnal tools?

**Comment by shanshin** [comment]
When using `annotatedBy`, the function disappeared from the report, only an error was printed in the logs?

**Comment by zuevmaxim** [comment]
@mgroth0 Could you please show how `withType(Class<?>)` function implementation looks like? Is it inline?

**Comment by shanshin** [comment]
@mgroth0, is this bug reproduced in the latest version `0.7.6`? 
If so, could you provide a small reproducer project with the latest Kover version?

**Comment by shanshin** [comment]
Thanks!
