### ISSUE TITLE
No versions published to maven central since 0.6.1

### ISSUE THREAD

**Issue by unredundant** [Kotlin/kotlinx-kover#457]
**Describe the bug**
Hi, it seems like none of the 0.7.x versions have been published to maven central https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kover

**Errors**
N/A

**Expected behavior**
Publish latest versions 

**Reproducer**
N/A

**Reports**
N/A

**Environment**
N/A

**Comment by shanshin** [comment]
Hi,
Kover artifact name [has been changed](https://github.com/Kotlin/kotlinx-kover/blob/main/docs/gradle-plugin/migrations/migration-to-0.7.0.md#rename-dependency-in-buildsrc).

accordingly, the latest versions are located at 
https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kover-gradle-plugin.

If you would like to keep track all version of the plugin versions with ID `org.jetbrains.kotlinx.kover`, you may use the following link
https://mvnrepository.com/artifact/org.jetbrains.kotlinx.kover/org.jetbrains.kotlinx.kover.gradle.plugin

Duplicates #397

**Comment by unredundant** [comment]
ah cool, thanks
