### ISSUE TITLE
Auto generated method coverage doesn't filled 

### ISSUE THREAD

**Issue by lntuition** [Kotlin/kotlinx-kover#467]
**Describe the bug**
Auto generated method doesn't filled coverage.

**Expected behavior**
filled coverage or do not check auto generated method

**Reports**

- Coverage summary
<img width="580" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/34061042/b2be0254-a7be-4da6-b88d-d75e1ace3206">

- Source code report
<img width="486" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/34061042/a0116603-75e6-4076-b11e-d8543443f052">

**Environment**
 - Kover Gradle Plugin version: : 0.7.3
 - Gradle version: 7.5.1
 - Kotlin project type: Kotlin
 - Coverage Toolset (if customized in build script): Kover
 - Other context important for this bug: mac OS m1

**Comment by lntuition** [comment]
It's okay not to check for auto-generated methods using a workaround 😄

**Comment by shanshin** [comment]
As far as I understand, by auto generated method you meant synthetic class-files like `...$merchants$1`.
The fact that they are displayed to the user separately is a disadvantage of the Kover HTML report.

**Comment by shanshin** [comment]
Closed in favor of https://github.com/Kotlin/kotlinx-kover/issues/498
