### ISSUE TITLE
Configuring kotlinx-kover in a multimodule Android project where only the app module has defined flavors

### ISSUE THREAD

**Issue by dawidhyzy** [Kotlin/kotlinx-kover#468]
I’m having trouble configuring [kotlinx-kover](https://github.com/Kotlin/kotlinx-kover) in a multimodule Android project where only the app module has defined flavors.

`./gradlew koverHtmlReport` fails with
```
Could not determine the dependencies of task ':app:koverHtmlReport'.
> Could not resolve all task dependencies for configuration ':app:koverExternalArtifacts'.
   > Could not resolve project :core:designsystem:common.
     Required by:
         project :app
      > The consumer was configured to find attribute 'kotlinx.kover.variant.name' with value ''. However we cannot choose between the following variants of project :core:designsystem:common:
          - debugRuntimeElements
          - releaseRuntimeElements
```
how should I configure it?

**Comment by shanshin** [comment]
Hi,
could you clarify, did you apply the Kover plugin in the `:core:designsystem:common` subproject?

**Comment by dawidhyzy** [comment]
No, I didn't. Should I do it?

**Comment by shanshin** [comment]
Yes, according [docs](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#multiproject-build): 
> it is necessary to [apply Kover plugin](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#quickstart) in each subproject for which coverage needs to be measured.
