### ISSUE TITLE
Coverage tied to dependency isn't functioning properly.

### ISSUE THREAD

**Issue by CharlesMoreira1** [Kotlin/kotlinx-kover#472]
I work on an app Android where I'm conducting snapshot tests using Paparazzi. However, due to some compatibility issues with company plugins and Robolectric, we had to create a separate module to house all the snapshot tests. In this case, we imported the feature modules into it and were able to achieve the expected results.

However, since the features are in a different module, the code coverage is showing as zero, and it can't locate the paths to the original files. I'm unsure if this is a genuine bug or if it's just not possible. My knowledge in this area is quite limited.

Example:

`implementation(project(":feature"))`

**Comment by shanshin** [comment]
Hi,
could you clarify, `:feature` is a dynamic feature submodule?

**Comment by shanshin** [comment]
Support for the dynamic feature modules was added in version `0.7.4`, please reopen the issue if the problem also repeats in `0.7.4`.
