### ISSUE TITLE
Const of an interface is included to a report

### ISSUE THREAD

**Issue by BulatInDrive** [Kotlin/kotlinx-kover#473]
**Describe the bug**
When an interface has a companion object with a const and no methods then this const is included into the report.
For a class it works as expected.

**Expected behavior**
Consts shouldn't be included into the report.

**Reports**
<img width="1624" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/127848635/ff35cd3d-ae35-4c88-8e14-24002f3f4878">

**Environment**
 - Kover Gradle Plugin version: 0.7.3
 - Gradle version: 7.3.1
 - Kotlin project type: Kotlin/Android
 - Coverage Toolset (if customized in build script): Kover

**Comment by shanshin** [comment]
Duplicates #451
