### ISSUE TITLE
Using the plugin in java project

### ISSUE THREAD

**Issue by SurpSG** [Kotlin/kotlinx-kover#504]
I've tried to apply the plugin to my java only project, but got no coverage.
After investigation of the plugin's source code I found out that the plugin is completely configured if kotlin plugin is applied to a project.
I've tried to apply kotlin plugin and finally got code coverage.

Kover can use JaCoCo or intellij-coverage engines that both support java. 

Is there any reason why kover doesn't support projects with only java sources?

**Comment by shanshin** [comment]
Hi, 
at the moment, Kover is a tool for projects written in Kotlin. Java code support has been added for projects migrating to Kotlin.
There are no short-term plans to add full support for Java-only projects, but it may be added in the future in a limited form.
