### ISSUE TITLE
Kover 0.7.4: this and base files have different roots

### ISSUE THREAD

**Issue by hoc081098** [Kotlin/kotlinx-kover#505]
**Describe the bug**

- This is project is a Android multiple modules. I applied kover plugin to each module, and in `:app` module, I used `dependencies { kover(project(":other-module")) ... }`

- When using version 0.7.3, it works as expected

### Failed when changing from 0.7.3 to 0.7.4

- PR: https://github.com/Kotlin-Android-Open-Source/MVI-Coroutines-Flow/pull/205

 - Full log at https://github.com/Kotlin-Android-Open-Source/MVI-Coroutines-Flow/actions/runs/6841635365/job/18602208693?pr=205
```
* What went wrong:
Execution failed for task ':app:koverGenerateArtifact'.
> this and base files have different roots: [+�~<K}�8�竭����=��x���v-�(dF�@�p�����k��M��ε	v�R�T}�����&n[Q8�: and /home/runner/work/MVI-Coroutines-Flow/MVI-Coroutines-Flow.
```

 - I have tried, but it does not work 🥺
```kotlin
allprojects {
  extensions.findByType<kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension>()?.run {
    useJacoco("0.8.11")
  }
}
```

**Comment by shanshin** [comment]
Hi, thanks for the report!

This is a known issue: #478

**Comment by shanshin** [comment]
Closed as duplicate
