### ISSUE TITLE
Have a public base class for custom plugins to use

### ISSUE THREAD

**Issue by cldfzn** [Kotlin/kotlinx-kover#507]
I maintain a gradle plugin which sets the default configuration used by a large number of projects. In prior versions I had used the `AbstractKoverReportTask` to hook up some tasks that depended on the reports. Now that they are internal classes, I can no longer reference them. In addition, task names are generated by the variant type, so I would need to go through the same logic the plugin does to generate the correct task names. Is there any possibility of adding a class that could still be reference for usage by custom plugins?

**Comment by shanshin** [comment]
Duplicates of https://github.com/Kotlin/kotlinx-kover/issues/338
