### ISSUE TITLE
Html report creation hangs 

### ISSUE THREAD

**Issue by ben-gooding-sky** [Kotlin/kotlinx-kover#509]
**Describe the bug**
In a multi-module kotlin-only, kotlin-android project the coverage report job hangs forever
The tests all pass correctly, but once it gets to the `kover` portion it hangs

**Errors**
```
> Task :kover:koverHtmlReport
Kover: HTML report for ':kover' file:///${path-to-project}/kover/build/reports/kover/html/index.html
[2023.11.20 11:53:34] (Coverage): Failed to check raw report file: java.io.FileNotFoundException: ${HOME}/.gradle/daemon/8.4 (Is a directory)
[2023.11.20 11:53:34] (Coverage): Failed to load coverage data from file: ${HOME}/.gradle/daemon/8.4: java.io.FileNotFoundException: ${HOME}/.gradle/daemon/8.4 (Is a directory)
... 30+ mins
```

**Expected behavior**
It should pass almost straight away after the file not found bug occurs

**Reproducer**
Can't reproduce this currently on a fresh project, but occurs with
`./gradlew :kover:koverHtmlReport`

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version:  0.7.3
 - Gradle version: 8.4
 - Kotlin project type: Kotlin/JVM/Android
 - Coverage Toolset (if customized in build script): Kover
 - Other context important for this bug: MacOS apple chip + linux pipeline

**Comment by shanshin** [comment]
Hi,
could you clarify, is this problem reproducing stably?

**Comment by shanshin** [comment]
It seems that this is due to https://github.com/Kotlin/kotlinx-kover/issues/478 (problem with file names), for sure we will be able to verify after the release of [this](https://github.com/Kotlin/kotlinx-kover/pull/506) change.

**Comment by ben-gooding-sky** [comment]
I've narrowed down the issue I was having, all works fine normally, but by including just this

`implementation(libs.ktor)` 

Is causing the hanging, which is in a Kotlin JVM module

(note I've not added any code changes)

**Comment by shanshin** [comment]
@ben-gooding-sky , please, try `0.7.5`, is the bug still reproduced?

**Comment by ben-gooding-sky** [comment]
Sadly getting a different error on `0.7.5`, it's not resolving the first `jvm` submodule (working on `0.7.3`) with the error
```
* What went wrong:
Configuration cache state could not be cached: field `provider` of `org.gradle.configurationcache.serialization.codecs.ProviderBackedFileCollectionSpec` bean found in field `__additionalArtifacts__` of task `:kover:koverGenerateArtifact` of type `kotlinx.kover.gradle.plugin.tasks.services.KoverArtifactGenerationTask`: error writing value of type 'org.gradle.api.internal.AbstractNamedDomainObjectContainer$NamedDomainObjectCreatingProvider'
> Failed to notify dependency resolution listener.
```
Then this x20+ times: (all exactly the same error)
```
Kover android variant 'customDebug' was not matched with any variant from dependency ':first-jvm-module' of project ':kover'. Check that the Kover plugin is applied in the ':first-jvm-module' project and there is a variant compatible with 'customDebug' in it.
```

From my understanding for multi-platform projects it should be enough to have these 2 configs in my `kover` module to run the tests - as described [here](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#using-kover-tasks:~:text=A%20special%20case%20is%20when%20JVM%20and%20Android%20targets)
```
koverReport {
    defaults {
        mergeWith("customDebug")
    }
}
```
and
```
dependencies {
    rootProject.subprojects.forEach { project ->
         kover(project(project.path))
    }
}
```

**Comment by shanshin** [comment]
> Kover android variant 'customDebug' was not matched with any variant from dependency ':first-jvm-module' of project ':kover'. Check that the Kover plugin is applied in the ':first-jvm-module' project and there is a variant compatible with 'customDebug' in it.

As far as I understand, this error occurs to you if you call the `:koverHtmlReportCustomDebug` command?

**Comment by ben-gooding-sky** [comment]
both `kover:koverHtmlReportCustomDebug` and `kover:koverHtmlReport`

**Comment by ben-gooding-sky** [comment]
and both of those have the same error

**Comment by ben-gooding-sky** [comment]
It's closed, but I've created a similar project here that has the same issue that is open 😄 

https://github.com/ben-gooding-sky/kover-bug-example

If you change the version back down to `0.7.3` it'll work, but with `.4`, and `.5` it fails

(note this example project doesn't show the initial hanging error I was having on `0.7.3` 🤷  but it will fail without hanging even on `0.7.3` if you uncomment the line `implementation(libs.ktor)`)

**Comment by shanshin** [comment]
Thanks for the example.

In the case of complex cases, it is necessary to adhere to the following rules:
1. For independent Android projects, must be specified `mergeWith()` in each of them
in your case, specify 
```
koverReport {
    defaults {
        mergeWith("debug")
    }
}
```
in projects `:app` and `:kover`

2. Create a combined report in a project that does not apply any of the Android plugins
in your case
```
dependencies {
    subprojects.forEach { project ->
        kover(project)
    }
}
```
for example, in the root project (let's call it a merging project)

3.  Specify report filters only in the merging project
in your case for root project specify
```
        koverReport {
            filters {
                excludes {
                    classes(
                        "*.BuildConfig",
                        "*.extensions.*"
                    )
                    packages("*.di", "*.ext")
                    annotatedBy("androidx.compose.ui.tooling.preview.Preview")
                    annotatedBy("androidx.compose.runtime.Composable")
                }
            }
        }
```

**Comment by ben-gooding-sky** [comment]
Perfect thank you! - yes this got it all working (+ ktor no longer causes it to hang)

added this to my `root` `build.gradle`
```
subprojects {
    val subProject = this
    fun variantResolution(project: Project): String {
        return when (project.name) {
            "someModule" -> "customDebug1"
            "anotherModule" -> "customDebug2"
            else -> "debug"
        }
    }
    pluginManager.withPlugin(rootProject.libs.plugins.kover.get().pluginId) {
        pluginManager.withPlugin(rootProject.libs.plugins.android.library.get().pluginId) {
            koverReport {
                defaults {
                    mergeWith(variantResolution(subProject))
                }
            }
        }
    }
}
```
and stripped out everything from my `kover` module relating to `android`  as you mentioned and just applied projects from there with
```
dependencies {
    rootProject.subprojects.forEach { project ->
        if (project.name !in excludes) {
            kover(project(project.path))
        }
    }
}
```

**Comment by shanshin** [comment]
I think we also should specify these recommendations in Kover docs

**Comment by ben-gooding-sky** [comment]
@florianflmeyer The configuration I used does work for for both Android/Jvm targets in one report using `koverHtmlReport` which must also be run from a module that doesn't contain any Android dependencies

- Specifically the line `mergeWith(variantResolution(subProject))` is what makes it possible to merge the reports into 1

Mentioned [here](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#using-kover-tasks:~:text=A%20special%20case%20is%20when%20JVM%20and%20Android%20targets) in their docs
