### ISSUE TITLE
Implement Kover Maven plugin

### ISSUE THREAD

**Issue by binkley** [Kotlin/kotlinx-kover#51]
Kover looks _very exciting_!  Thank you for the Gradle plugin.

Request: an equivalent Maven plugin.  Projects I work on are around 50/50 Gradle/Maven for builds (these are for backend, not mobile).

**Comment by IgorSidorov** [comment]
+1
working with server side banking project.
Look forward to the maven equivalent.

**Comment by shanshin** [comment]
Hi,
at the moment, the development of the Maven plugin is not included in the short-term plans.

We will be happy to listen to your use cases, it will help to develop an API for the Maven plugin.

**Comment by KyongSik-Yoon** [comment]
+1
working with server side apm project.
Look forward to the maven equivalent

**Comment by marcoebbinghaus** [comment]
+1

Building maven based kotlin backend (REST API) application. I would like maven to create reports with kover during my CI.

**Comment by RustamKuramshin** [comment]
+1

**Comment by Filipe3xF** [comment]
+1

**Comment by prajain12** [comment]
+1 Very much interested in Kover Maven Plugin. JaCoCo still does not fully serve the purpose. For example JaCoCo does not exclude getters and setters from the code coverage of data classes.

**Comment by revseev** [comment]
+1
Server-side enterprise development

**Comment by Guruth** [comment]
+1
Server-side enterprise development

**Comment by khekrn** [comment]
+1
Server Side enterprise dev

**Comment by binkley** [comment]
A big reason I'm looking at Kover rather than JaCoCo is `inline` function coverage.  See https://github.com/jacoco/jacoco/issues/654.

@shanshin As to "use cases", I assume you mean why Maven?  I don't want to have a religious debate of Gradle _vs_ Maven ;-) I'm a consultant, and make recommendations to client teams and organizations on tech choices. For me, I often (but not always) prefer Maven, especially for certain types of client, because of stability and reproducibility of builds.  And I encourage them to move to Kotlin from Java when feasible, and coach developer teams in that transition.

**Comment by BerMuc** [comment]
+1

**Comment by stylismo** [comment]
+1

**Comment by ArtSaidanov** [comment]
+1

**Comment by raissa-machado** [comment]
+1

**Comment by NoxFr** [comment]
+ 1!

**Comment by JulI0-concerto** [comment]
+1

**Comment by joao-soares-amaro** [comment]
+1

**Comment by oldratlee** [comment]
+1

from the issue https://github.com/jacoco/jacoco/issues/654

**Comment by qwwdfsad** [comment]
Our long-term plan is the following: polish and stabilize Gradle API (so it's complete, future-proof and supports both Android and merged reports in a concise manner). As soon as it's done, we'll release it and start transferring this API shape into Maven plugin (which, alas, will be much less configurable and probably won't support merged reports as well).

No specific timeframes for this tho, it's just an outline of our overall direction

**Comment by pacdouglas** [comment]
+1

**Comment by SNandecha1** [comment]
+1

**Comment by hiteshgrover06** [comment]
+1

**Comment by acbeljaars** [comment]
+1

**Comment by emrearslan** [comment]
+1

**Comment by aloisgeith** [comment]
+1

**Comment by santosr2-ppb** [comment]
+1

**Comment by simon-void** [comment]
+1

**Comment by oldratlee** [comment]
+1

**Comment by kolesar-andras** [comment]
+1

**Comment by shanshin** [comment]
Implemented in `0.8.3`
