### ISSUE TITLE
Kover 0.7.5 breaks configuration cache

### ISSUE THREAD

**Issue by kenyee** [Kotlin/kotlinx-kover#513]
**Describe the bug**
Upgraded from 0.7.0 to 0.7.5 and now I need to run Kover with --no-configuration-cache

**Errors**
Gradle fails with this warning:

10:53:42  3 problems were found storing the configuration cache, 1 of which seems unique.
10:53:42  - Plugin 'org.jetbrains.kotlinx.kover': registration of listener on 'Gradle.addListener' is unsupported

**Expected behavior**
Kover should work with Gradle's configuration cache

**Reproducer**
Add to multi-module project.  Enable gradle configuration cache.  Try running koverHtmlReport.
Also found out that Kover 0.7.4 does not have problems w/ the configuration cache so we'll be sticking w/ this version for now.

**Environment**
 - Kover Gradle Plugin version: 0.7.5
 - Gradle version: 8.0.2
 - Kotlin project type: Kotlin/JVM
 - Coverage Toolset (if customized in build script): Kover

**Comment by shanshin** [comment]
Thank you, you can use the version `0.7.4` for now, while we find a replacement listener for checking dependencies.

**Comment by shanshin** [comment]
Fixed in `0.7.6`
