### ISSUE TITLE
Exclude DefaultImpls from a report

### ISSUE THREAD

**Issue by BulatInDrive** [Kotlin/kotlinx-kover#517]
**Describe the bug**
For interface with function with default params Kover generates 0% coverage report.

**Expected behavior**
Default params shouldn't be in a report.

**Reports**
<img width="1575" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/127848635/dfb634af-f493-42c9-9bbc-59dcd0fddce2">

**Environment**
 - Kover Gradle Plugin version: 0.7.4
 - Gradle version: 7.3.1
 - Kotlin project type: Kotlin/Android
 - Coverage Toolset (if customized in build script): Kover

**Comment by zuevmaxim** [comment]
@BulatInDrive I confirm that line 5 should not be marked as red as it contains no executable code -- this is a bug
Lines 6 and 7 contain the values of the default arguments, so kover treats them as uncovered, when the value is not used in tests. Consider adding tests with calls like `makeCoffee()`

**Comment by zuevmaxim** [comment]
The fix for line 5 is available in the agent version 1.0.745

**Comment by shanshin** [comment]
Fixed in `0.7.6`
