### ISSUE TITLE
Android JUnit tests are skipped

### ISSUE THREAD

**Issue by pdb-stripe** [Kotlin/kotlinx-kover#518]
I am having trouble getting android junit tests to run on a multi-module project. The project looks something like this:

```
rootProject
 |---directory1
 |-----app1
 |-----lib1
 |---directory2
 |-----app2
 |-----lib2
 |---directory3
 |-----javalib
```

When I configure the plugin, running `koverXmlReportDebug` / `koverXmlReport` (running both currently) does not cause any junit tests to execute on Android modules (in `src/test`). It does execute the pure-java module however. 

Is this a bug or a configuration error? How can I get this working? Do I need to both use `androidReports` and `mergeReports`?

**Comment by shanshin** [comment]
Hi,
could you show me how Kover is configured?
For which module (project) are you calling the report generation?

**Comment by shanshin** [comment]
Hi,
please read this [comment](https://github.com/Kotlin/kotlinx-kover/issues/509#issuecomment-1830635724) with recommendations for creating a merged report for Android + JVM projects.

If the configuration still fails, then reopen the issue and link the reproducer of your problem

**Comment by shanshin** [comment]
Closed as answered.
Feel free to create new issue if you have any additional questions.
