### ISSUE TITLE
The Gradle `check` task depends on `koverVerify` one after migration to 0.7.0

### ISSUE THREAD

**Issue by vitaly-ivanov** [Kotlin/kotlinx-kover#523]
**Describe the bug**
Following the recent upgrade of the Gradle plugin to version 0.7.0 and above, we've observed an unexpected behaviour in the `verify` task. It now triggers the `koverVerify` task, causing the execution of all test tasks, even when the `verify` task does not explicitly depend on them.

This behaviour is undesirable for our workflow, as it introduces unnecessary overhead and leads to the execution of integration test tasks that are originally unrelated to the `verify` task.

**Errors**
The `integrationTest` is triggered by calling `gradle verify` due to kover tasks.

Actual task dependency tree (0.7.0+):
```
:shared:check
+--- :shared:koverVerify
|    \--- :shared:koverGenerateArtifact
|         +--- :shared:compileJava
|         +--- :shared:compileKotlin *
|         +--- :shared:integrationTest <--------------- undesired
|         \--- :shared:test
+--- :shared:ktlintKotlinScriptCheck
+--- :shared:ktlintMainSourceSetCheck
+--- :shared:ktlintTestSourceSetCheck
\--- :shared:test *
```

**Expected behavior**

The `integrationTest` should not be triggered by calling `gradle verify`.

Expected dependency tree (0.6.1)
```
:shared:check
+--- :shared:ktlintKotlinScriptCheck
+--- :shared:ktlintMainSourceSetCheck
+--- :shared:ktlintTestSourceSetCheck
\--- :shared:test
```

**Reproducer**

Register the new Test task in the root `build.gradle.kts` of multi-project Gradle project. The check 

```
allprojects {
    plugins.withId("java") {
        tasks {
            register<Test>(name = "integrationTest") {
                useJUnitPlatform {
                    includeTags("integration")
                }
            }
        }
    }
```

**Environment**
 - Kover Gradle Plugin version: 0.7.0+
 - Gradle version: 8.5
 - Kotlin project type:  Kotlin/JVM, Gradle Multiproject
 - Coverage Toolset (if customized in build script): Kover
 - Other context important for this bug: Junit Platform

**Comment by shanshin** [comment]
Hi,
to prevent the launch of undesirable text tasks, it is necessary to add the following code to the build script of the project where these tasks are declared:

```
kover {
    excludeTests {
        // `integrationTest` will not be triggered by any Kover task and the coverage from it will not be taken into account in the Kover reports
        tasks("integrationTest")
    }
}
```

**Comment by vitaly-ivanov** [comment]
Hi @shanshin, thanks for your fast reply. I'm not sure we can use this configuration because the "integrationTest" task is essential for coverage calculations, but it's not intended to run with the `verify` task. This is mainly because it consumes a significant amount of time and demands substantial computational resources.

Is it possible to exclusively invoke the `koverVerify` task following the execution of the `koverReport` task without any implicit dependencies on the `verify` task?

**Comment by shanshin** [comment]
If you don't need to check coverage when running the `check` task, then you may explicitly disable this dependency in this way:
```
koverReport {
    defaults {
        verify {
            onCheck = false
        }
    }
}
```

**Comment by vitaly-ivanov** [comment]
@shanshin Thank you, this is exactly what I was looking for!
