### ISSUE TITLE
Not found on Maven Central

### ISSUE THREAD

**Issue by mayardb** [Kotlin/kotlinx-kover#526]
**Describe the bug**
Plugin is not available on Maven Central since 0.6.1

**Expected behavior**
Plugin latest available version on Maven Central should be 0.7.4

https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kover
https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kover

Also, I was able to find it here:
https://mvnrepository.com/artifact/org.jetbrains.kotlinx.kover/org.jetbrains.kotlinx.kover.gradle.plugin/0.7.5

However, as you can read, this is not `org.jetbrains.kotlinx:kover` but `org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin`.

So or the readme is wrong, or it is uploaded to the wrong place.

I hope this helps.

**Comment by shanshin** [comment]
Hi,
version `0.7.5` already published to Maven Central, however, the artifact name [has been changed](https://github.com/Kotlin/kotlinx-kover/blob/main/docs/gradle-plugin/migrations/migration-to-0.7.0.md#rename-dependency-in-buildsrc).

You may find the latest versions by the corresponding name https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kover-gradle-plugin

Please note that if you are using the legacy plugin application, then in apply [you should specify](https://github.com/Kotlin/kotlinx-kover?tab=readme-ov-file#legacy-plugin-application) `org.jetbrains.kotlinx.kover`

**Comment by mayardb** [comment]
Thank you for the update.

Finally, I did not find the good settings.
Don't know what I copy-pasted. It is working now.

Once again, thank you.
