### ISSUE TITLE
Coverage is not collected in gradle plugin test

### ISSUE THREAD

**Issue by SurpSG** [Kotlin/kotlinx-kover#529]
**Describe the bug**
If I apply kotlin gradle plugin then coverage collecting is failed:

```kotlin
    @Test
    fun `apply plugin test`() {
        val project: Project = ProjectBuilder.builder().build()
        project.pluginManager.apply("org.jetbrains.kotlin.jvm") // <------- applying of the plugin fails coverage collection
        project.pluginManager.apply("org.example.plugin-with-cover")
    }
```
If I run this test without the kotlin plugin then the coverage is collected properly.

**Errors**
`coverage-error.log` is generated in `build/kover/bin-reports`:
[coverage-error.log](https://github.com/Kotlin/kotlinx-kover/files/14043437/coverage-error.log)

**Expected behavior**
The coverage is collected successfully

**Reproducer**
There is an [example](https://github.com/SurpSG/plugin-with-kover) where the issue could be reproduced.

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 1.9.21
 - Gradle version: 8.4
 - Kotlin project type: Kotlin/JVM
 - Coverage Toolset: Kover
 - Other context important for this bug: -

**Comment by shanshin** [comment]
Hi, thanks for the reproducer!

In the `build.gradle.kts` file, replace the Kover configuration 
```
kover {
    excludeInstrumentation {
        classes("*CompileOptions*")
        packages("com.android")
        packages("*.android.*")
    }
}
```

with the following CCC
```
kover {
    excludeInstrumentation {
        classes("org.jetbrains.kotlin.gradle.*")
    }
}
```

**Comment by SurpSG** [comment]
@shanshin 
It works, thank you!

Closing the issue.
