### ISSUE TITLE
Clarify that `koverCollectReports` does not only collect (existing) reports

### ISSUE THREAD

**Issue by sschuberth** [Kotlin/kotlinx-kover#53]
The docs / task description of `koverCollectReports` reads to me as if only *existing* reports should get collected, whereas executing that task actually *does* also execute the tests (if not up-to-date).

Please clarify whether the current behavior or the docs are correct, and adjust one to the other accordingly.

**Comment by shanshin** [comment]
Fixed in `0.4.2`
