### ISSUE TITLE
Kover doesn't reflect my test changes

### ISSUE THREAD

**Issue by ashaluwalakazeem** [Kotlin/kotlinx-kover#532]
**Describe the bug**
Kover doesn't reflect my test changes whenever I use [kotlinFixtures](https://github.com/appmattus/kotlinfixture) in my test class to generate fakes.

**Errors**
No stack traces detected

**Expected behavior**
Kover should reflect the test cases for test classes using the mentioned library

**Reproducer**
The codebase is private but it can be easily reproducible by simply using kotlinFixture for generating fakes in a test class.

``` kotlin
    class ProfileViewModelTest {
        private val fixture = kotlinFixture()
        private val fakeDesc = fixture<Desc>() // Desc can be any data class
        
        
        @Test
        fun testDesc() {
             assertNotNull(fakeDesc.name)
        }
    }
```

**Reports**
Kover tests passed 100%

**Environment**
 - Kover Gradle Plugin version: [1.9.21]
 - Gradle version: [e.g. 8.3]
 - Kotlin project type: [Kotlin/Android]
 - Coverage Toolset [Kover]

**Comment by shanshin** [comment]
Hi,
kotlinFixtures, currently not supported

**Comment by shanshin** [comment]
Thanks for the report!

Closing in favor of #533
