### ISSUE TITLE
Add an example how to limit coverage to a specific custom test source set / test suite

### ISSUE THREAD

**Issue by sschuberth** [Kotlin/kotlinx-kover#54]
Many projects have custom tests and belonging source sets defined, like `integTests` (integration tests) or `funTests` (functional tests).

Please provide an example on how to limit determining coverage / running tests to only those tests from a specific source set / [test suite](https://docs.gradle.org/7.3/userguide/jvm_test_suite_plugin.html).

**Comment by shanshin** [comment]
Hi,
at the moment, there is no stable way to limit the set of classes used for verification (source sets, directories, etc.).

The design of the API for verification is currently in progress (#19), so it would be helpful if you described the complex use cases of verification for your application.

**Comment by alexburlton** [comment]
I want exactly the same as this basically - my project has the following tasks alongside the default `test` one, for a mixture of convenience and speed (in CI, the `unitTest` and `integrationAndE2E` tasks get run in parallel by different runners):

```
task unitTest(type: Test) {
    useJUnitPlatform {
        excludeTags "integration", "e2e"
    }
}

task updateScreenshots(type: Test) {
    jvmArgs '-DupdateSnapshots=true'
    useJUnitPlatform {
        includeTags "screenshot"
    }
}

task integrationAndE2E(type: Test) {
    useJUnitPlatform {
        includeTags "integration", "e2e"
    }
}
```

Currently, though, this means that running `koverReport` will run my whole test suite twice as it kicks off all the test tasks! Would be great to have a way to tell it to only run a specified test task. This could be done either way around, e.g:

```
./gradlew koverReport --tasks unitTest
```

or

```
./gradlew unitTest --generateKoverReport
```

**Comment by alexburlton** [comment]
FWIW, I've found a way of doing this which is a little hacky but does the job:

```
tasks.koverReport {
    updateScreenshots.onlyIf { false }
    integrationAndE2E.onlyIf { false }
    unitTest.onlyIf { false }
}
```

This tells gradle to skip the test tasks I don't want to run coverage for, leaving it to just run the default `test` task (i.e. everything) :grin:

**Comment by shanshin** [comment]
Duplicates #19
