### ISSUE TITLE
annotatedBy doesn't exclude classes from coverage

### ISSUE THREAD

**Issue by nuhkoca** [Kotlin/kotlinx-kover#555]
**Describe the bug**
Hello, I created a custom annotation but classes annotated with it are still included in code coverage.

**Expected behavior**
Classes/functions annotated by `KoverIgnore` should be excluded from coverage.

**Reproducer**

```kotlin
internal val annotationExclusions = listOf(
    "<project_path>.common.utils.KoverIgnore",
    "androidx.compose.runtime.Composable",
    "androidx.compose.ui.tooling.preview.Preview",
    "<project_path>.snapshot.PreviewTest",
    "*Generated",
)

configure<KoverReportExtension> {
        filters {
            excludes {
                classes(coverageExclusions)
                packages(packageExclusions)
                annotatedBy(annotationExclusions.joinToString())
            }
        }
    }
```

**Reports**
If applicable, report files or screenshots.

<img width="806" alt="Screenshot 2024-02-29 at 16 00 50" src="https://github.com/Kotlin/kotlinx-kover/assets/5719389/22850386-807f-4520-b6e5-fd293d6ccf60">

**Environment**
 - Kover Gradle Plugin version: 0.7.6
 - Gradle version: 8.2.2
 - Kotlin project type: Kotlin/Android
 - Coverage Toolset: Kover

**Comment by shanshin** [comment]
Hi,
your configuration uses joining all annotations into one String `annotationExclusions.joinToString()`, however, only one annotation should be written in each string.

you should write like this
```
annotatedBy("annotation1", "annotation2")
```
or if you have a list with annotations, like this
```
annotatedBy(*annotationExclusions.toTypedArray())
```

**Comment by nuhkoca** [comment]
Thank you, it's fixed!
