### ISSUE TITLE
Could you elaborate more on how to create a Provider in order to lazily provide exclusions?

### ISSUE THREAD

**Issue by nuhkoca** [Kotlin/kotlinx-kover#556]
Hello,

I came across the new migration guide for the version `0.8.0` and [Lazy configuration section](https://github.com/Kotlin/kotlinx-kover/blob/main/kover-gradle-plugin/docs/migrations/migration-to-0.8.0.md#added-the-ability-of-lazy-configuration) caught my attention as I use conventional plugins in our project and would like to more about how to create a `Provider` for exclusions e.g. how to create `classProvider` for a comma separated string exclusion?

```kotlin
kover {
  reports {
    filters {
      exludes {
         classes(classProvider) 
      }
    }
  }
}
```

**Comment by shanshin** [comment]
Hi,
according to [Gradle's recommendations](https://docs.gradle.org/current/userguide/lazy_configuration.html#creating_property_provider), you should avoid explicitly creating Provider instance.

if you use convention plugin, then you need to declare the extension in it with property of type `Propety<String>`, like
```
interface MyExtension {
    //  comma separated string exclusion
    val exclusions: Property<String>
}
```

below, when configuring Kover from a comma-separated single string, you need to get Provider of a collection of strings, like
```
kover {
    reports {
        filters {
            exludes {
                classes(myExtension.exclusions.map { it.split(",") }) 
            }
        }
    }
}
```

**Comment by shanshin** [comment]
Closed as answered.
Feel free to create new issue if you have any additional questions.
