### ISSUE TITLE
Kover reports not coverage code with robolectric and hilt

### ISSUE THREAD

**Issue by fpitpit** [Kotlin/kotlinx-kover#56]
I launched unit test android (not instrumented test) with robolectric and hilt (test passed OK) but not appears in coverage report (it indicates 0%)

Could you put a complete example with android with robolectric example ?

**Comment by cheskos** [comment]
Is this related to #96 as well?

**Comment by shanshin** [comment]
@cheskos, yes they are related

**Comment by shanshin** [comment]
Duplicates #96
