### ISSUE TITLE
Out of memory error when running either kover:koverHtmlReport or kover:koverVerify

### ISSUE THREAD

**Issue by Chrisjc28** [Kotlin/kotlinx-kover#566]
**Describe the bug**
When running our unit tests if we run them with kover:koverHtmlReport or kover:koverVerify we are getting an out of memory error ```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "/127.0.0.1:51537 to /127.0.0.1:51536 workers Thread 2"
```
This is causing the job to fail but if we run the Unit tests with these commands they all pass with flying colours.
```
**Errors**

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "/127.0.0.1:51537 to /127.0.0.1:51536 workers Thread 2"
```

**Expected behavior**
We can run the Unit tests with the kover commands without suffering from an out of memory error.

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: [0.7.6]
 - Gradle version: [8.3.0]
 - Kotlin project type: [Kotlin/Android]
 - Coverage Toolset (if customized in build script): [Kover]
 - Other context important for this bug: [N/A]

**Comment by imcmib** [comment]
@Chrisjc28 I faced same issue. Did you manage to fix it?
