### ISSUE TITLE
Can't find Freemarker

### ISSUE THREAD

**Issue by droidmatic34** [Kotlin/kotlinx-kover#57]
basic plugin integration within Android Studio (latest stable)

Execution failed for task ':analytics:testReleaseUnitTest'.
> Could not resolve all files for configuration ':IntellijKoverConfig'.
   > Could not find org.freemarker:freemarker:2.3.30.
     Searched in the following locations:
       - https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/org/freemarker/freemarker/2.3.30/freemarker-2.3.30.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > org.jetbrains.intellij.deps:intellij-coverage-reporter:1.0.614 > org.jetbrains.intellij.deps:coverage-report:1.0.8

**Comment by lars-reimann** [comment]
I could resolve this issue by adding the following to the `build.gradle` file:
```kt
repositories {
    mavenCentral()
}
```
Maybe that works for you, too.

**Comment by droidmatic34** [comment]
added but doesn't work

**Comment by nefilim** [comment]
same problem

**Comment by stiost** [comment]
Same issue in a multiproject build using convention plugins (kover is the only thing in the root build.gradle file). Adding mavenCentral() worked

**Comment by shanshin** [comment]
@droidmatic34, please check in version `0.4.3`.

**Comment by droidmatic34** [comment]
looks good on my end
