### ISSUE TITLE
Pass list of projects via all projects filter 

### ISSUE THREAD

**Issue by igorromcy** [Kotlin/kotlinx-kover#575]
I'm trying to use all projects with a filter 

` allProjects(filter: Spec<Project>) `

but I didn't understand via the documentation how I should achieve that, so far I have a list of strings with all projects (i.e: ":feature:login", ":feature:signup", etc..)

**Comment by shanshin** [comment]
Hi, to merge all projects you shouldn't specify filter, like this
```
            kover {
                merge {
                    // merge with all projects
                    allProjects()

                   // other configs
                }
            }
```

**Comment by igorromcy** [comment]
sorry I wasn't clear, I need to use that filter, so I'm trying to convert the list of strings (modules) to that Spec<Project>

I just found out that we have `projects(vararg projectNameOrPath: String)` available to use as a filter as well, let me try that.

**Comment by shanshin** [comment]
Yes, `projects(...)` is intended for cases when there is only a list with the names of projects that should be merged.

But you can also use `allProjects` if you specify a predicate in the form of a lambda expression:
```
kover {
    merge {
        allProjects {
            it.path in setOf(":feature:login", ":feature:signup") // or for Groovy  [":feature:login", ":feature:signup"]
        }
    }
}
```

**Comment by igorromcy** [comment]
Perfect! Thank you
