### ISSUE TITLE
Merge unit and instrumented test report in single file or directory of a multi-module Android project?

### ISSUE THREAD

**Issue by ArcherEmiya05** [Kotlin/kotlinx-kover#592]
Hi, can someone help me how to merge unit and instrumented test across module/subproject for Android? Most solution I see in the internet is using JaCoCo. Which Kover Gradle task I should trigger and do I need extra configuration to achieve this? Thanks!

Sample structure
- app [unitTest, androidTest]
  - libs
    - module1 [unitTest, androidTest]
    - module2 [unitTest]

**Comment by shanshin** [comment]
Hi, 
at the moment, running tests on the device is not supported yet. Work is in progress now.
