### ISSUE TITLE
Adding kotlinx-kover compiler plugin make intellij debugger step in class loader

### ISSUE THREAD

**Issue by e5l** [Kotlin/kotlinx-kover#616]
**Describe the bug**
Stepping in on the function may result in the debugger entering the class loading phase if the Kover Gradle plugin is added.

**Environment**
 - Kover Gradle Plugin version: 0.7.6
 - Gradle version: 8.7
 - Kotlin project type: Ktor, kotlin 1.9.22
- Idea Ultimate 2024.1.2

**Comment by zuevmaxim** [comment]
@e5l Could you please elaborate? Where the debugger stops for you? 
Do you have this stepping filter enabled?
<img width="742" alt="Screenshot 2024-06-03 at 16 12 48" src="https://github.com/Kotlin/kotlinx-kover/assets/31644752/e5b11594-f332-455f-9821-97b9ecaf0fb4">

**Comment by e5l** [comment]
Hey, @zuevmaxim! Sorry for the delay. I no longer have this workload around. I will try to get back when I see it next time

**Comment by shanshin** [comment]
Closed as unreproducible locally.

Feel free to create new issue if problem happens again.
