### ISSUE TITLE
Merged coverage report not generated

### ISSUE THREAD

**Issue by WildOrangutan** [Kotlin/kotlinx-kover#619]
**Describe the bug**
Running e.g. `koverXmlReportRelease` doesn't generate merged xml report, like `koverXmlReport` does.

**Expected behavior**
I expect that `koverXmlReportRelease` and `koverXmlReportDebug` would generate `report.xml`.

**Reproducer**
My setup is pretty basic. I have a few android submodules, let's say `:A1`, `:A2`, ...
- All of them have basic configuration, with no flavors. Meaning, they only have variants `Debug` and `Release`. 
- All of them have kover plugin applied, with no special additional configuration

```kotlin
// Convention gradle script for submodules
plugins {
     id("com.android.library")
     id("kotlin-android")
     id("org.jetbrains.kotlinx.kover") version "0.8.0"
}

configure<KoverProjectExtension> {
    reports {
        total {
            verify {
                rule {
                    minBound(80)
                }
            }
        }
        filters {
            excludes {
                classes("*.BuildConfig")
            }
        }
    }
}
```

And my root gradle script is:

```kotlin
plugins {
     id("org.jetbrains.kotlinx.kover") version "0.8.0"
}

dependencies {
    kover(project(":library-a1"))
    kover(project(":library-a2"))
}

kover {
    reports {
        filters {
            excludes {
                classes("*.BuildConfig")
            }
        }
    }
}
```

**Environment**
 - Kover Gradle Plugin version: [0.8.0]
 - Gradle version: [8.2.2]
 - Kotlin version: [1.9.23]
 - Kotlin project type: [Kotlin/Android]

**Comment by shanshin** [comment]
Hi,
could you clarify that you have only one `app` module and several library modules, while in all these modules the set of build variants is the same (`debug` and `release`)?

If so, add kover dependencies to all library modules in the app module configuration
```kotlin
dependencies {
    kover(project(":library1")) 
    kover(project(":library2")) 
    ...
}
```

 and generate a report using the `:app:koverXmlReportDebug` or `:app:koverXmlReportRelease` commands

**Comment by shanshin** [comment]
Also, in this case, the setting
```kotlin
    reports {
        // reports configurations
    }
```

 should be specified only in the app module, it is not necessary to configure it in all other modules

**Comment by pm-nchain** [comment]
Ah, sorry for not making it more clear.

There is no `:app` module. The whole project is a library project, that produces multiple artifacts (one per module). We use it to share logic between multiple Android projects in other repositories.

Atm all modules are Android modules and they all have `release` and `debug` variant.

I presumed I can merge reports, by adding kover configuration on the root build gradle file.

**Comment by WildOrangutan** [comment]
Yes, no debug/release defined on root project, only on sub-modules. Do you think this is the issue?

**Comment by shanshin** [comment]
> Do you think this is the issue?

No, in this case you need to act as described in the [documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-multi-module-android-project).

- create a custom version in the root project
```kotlin
kover {
    currentProject {
        createVariant("main") {
            // no sources and tests
        }  
    }
}
```
- add kover dependencies to all subprojects
```kotlin
dependencies {
    kover(project(":moduleA"))
    kover(project(":moduleB"))
    // all subprojects
}
```

- in all subprojects, create a custom variant and add the necessary Android build variants to it
```kotlin
kover {
    currentProject {
        createVariant("main") {
            add("debug") // or `release`
        }  
    }
}
```
- add report filters **only** in the root project
```kotlin
kover {
    reports {
        // other report settings
        filters {
            // filters
        }
    }
}
```

- generate report by calling Gradle task `:koverXmlReportMain`

**Comment by WildOrangutan** [comment]
Ah, I see. That solves my issue, thank you.

One more question. Is there a way to have report filters per submodule, while still having a merged report?

**Comment by shanshin** [comment]
@WildOrangutan,
 
> Is there a way to have report filters per submodule, while still having a merged report?

Yes, you can specify the code from which modules will be included in the report:
```kotlin
kover {
    reports {
        variant("main") {
            filters {
                includes {
                    projects.add(":submodule1")
                }
            }
        }
    }
}
```


If you need to generate reports on different modules at the same time, then you should wait for the release of [improvements on copying variants](https://github.com/Kotlin/kotlinx-kover/pull/620#discussion_r1629735225) that are convenient just for such cases.
