### ISSUE TITLE
Incorrect enum coverage issue in Kotlin 2.0

### ISSUE THREAD

**Issue by dungsil** [Kotlin/kotlinx-kover#621]
**Describe the bug**

Coverage of enum classes is incorrectly calculated when using kover in Kotlin 2.0.

**Errors**
If present, stacktraces or files from `build/kover/errors` directory

N/A

**Expected behavior**

Incorrect display of the last ‘}’ string in the Enum class

| Kotlin 1.9.23 | Kotlin 2.0.0 |
| ------------ | ------------ |
| ![image](https://github.com/Kotlin/kotlinx-kover/assets/39783731/a1508f46-fd78-40d8-8143-620e23c48786) |  ![image](https://github.com/Kotlin/kotlinx-kover/assets/39783731/c80ee858-ec6c-4dbb-abae-501a8f47a58d) |

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

| Kotlin 1.9.23 | Kotlin 2.0.0 |
| ------------ | ------------ |
| ![image](https://github.com/Kotlin/kotlinx-kover/assets/39783731/a1508f46-fd78-40d8-8143-620e23c48786) |  ![image](https://github.com/Kotlin/kotlinx-kover/assets/39783731/c80ee858-ec6c-4dbb-abae-501a8f47a58d) |

**Environment**
 - Kover Gradle Plugin version: 0.8.0
 - Gradle version: 8.7
 - Kotlin project type: Kotlin/JVM (Spring boot)
 - Coverage Toolset (if customized in build script): Kover
 - Other context important for this bug: Windows 11

**Comment by shanshin** [comment]
Fixed in `0.8.2`
