### ISSUE TITLE
XML report for the tests results

### ISSUE THREAD

**Issue by RomanMichailov** [Kotlin/kotlinx-kover#641]
Can I get an XML report for the tests with this plugin? 
When I run the koverXmlReport and some of my tests fail I'm getting the test results in HTML format and there is no generated coverage report.

**Comment by shanshin** [comment]
Hi, the coverage report is created only when the test task is successfully completed.

**Comment by RomanMichailov** [comment]
Hi, Thanks for the quick response. yes, I understand that all the tests must be passed for the coverage report to be generated. 
But my question is if it is possible to get the test results in XML format? eg the output that shows which test failed and why.

**Comment by shanshin** [comment]
> But my question is if it is possible to get the test results in XML format? eg the output that shows which test failed and why.

Sorry, but I don't quite understand the question. 
If you mean the report `build/tests/<taskname>/index.html` - then this report has nothing to do with Kover Gradle Plugin, it is generated by Gradle itself and we do not read or write its contents.

`koverXmlReport` - it's JaCoCo compatible coverage XML report, it does not contain information about the tests being run, only about class coverage

**Comment by shanshin** [comment]
@RomanMichailov, you may use XML files from dir `build/test-results/<taskname>/...`. 
There are a set of XML files that are called something like this `TEST-<TestClassName>.xml` (depends on the settings of the test-suites).
