### ISSUE TITLE
Does this aggregate unit test report in HTML for Android?

### ISSUE THREAD

**Issue by ArcherEmiya05** [Kotlin/kotlinx-kover#642]
If I run `./gradlew test` in a multi module Android project and wanted to aggregate all test results in single HTML page, which gradle task of Kover should I run? Such feature was implemented in this [plugin](https://github.com/gmazzo/gradle-android-test-aggregation-plugin).

**Comment by shanshin** [comment]
Hi,
unfortunately, there is no such task. 
The Kover plugin does not process the results of running tests, it is only responsible for measuring coverage.

**Comment by shanshin** [comment]
If you need an aggregated coverage report, please refer to [the documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-multi-module-android-project).

**Comment by ArcherEmiya05** [comment]
Thanks, by the way is there any plan to support such feature?

**Comment by shanshin** [comment]
> Thanks, by the way is there any plan to support such feature?

Could you please clarify which feature is meant?
Generation of aggregated coverage reports has already been implemented (see documentation).

**Comment by ArcherEmiya05** [comment]
> > Thanks, by the way is there any plan to support such feature?
> 
> Could you please clarify which feature is meant? Generation of aggregated coverage reports has already been implemented (see documentation).

Sorry I mean the aggregation of unit test, or Kover's entirely usage is for code coverage and its aggregation?

**Comment by shanshin** [comment]
> Sorry I mean the aggregation of unit test, or Kover's entirely usage is for code coverage and its aggregation thus no plan of supporting the latter?

Yes, Kover - is Kotlin Code Coverage toolset, it is not intended for tracking tests.
