### ISSUE TITLE
Example full projects that show how to configure exludes and other features

### ISSUE THREAD

**Issue by tgkprog** [Kotlin/kotlinx-kover#643]
**Configure Kover to not add some packages or classes to the coverage report**

**Examples **
A working example with Java 21 or higher, Graadle as build tool, Junit test framework from https://micronaut.io/launch/ like this one : https://github.com/tgkprog/kotlinIgnoreDataClassPropsDefaultValJson

Took a look at existing issues/ posts and tried to make config https://github.com/tgkprog/kotlinIgnoreDataClassPropsDefaultValJson/blob/main/build.gradle#L76 to exclude a class:

```
 kover {
        filters {
            classes {
                excludes += listOf("com.sel2in.kotlinDefaultsJson.app.App")
            }
        }
```

even to exclude a package
                `excludes += listOf("com.sel2in.kotlinDefaultsJson.app.*")`

tried with` /` instead of periods but no cigar

Please copy code from this repo or others and give us full working example repos to download, try and copy from.

End result I should be able to clone or download your example repo, configure Java version per read me and then in a terminal give command : 
`./gradlew koverHtmlReport`

and see a report that deoes not include App.class in the report or percentages of coverage.
Also if I run gradlew koverHtmlReport once the make changes to the code and again run gradlew koverHtmlReport it does not update the report time, does not write the report again. Would expect it to generate a report everytime its called, maybe not generate css/ js again but the report figures and date-time stamp should be re-written to file? Else tell us that we need to call

`gradlew clean koverHtmlReport` on the front page of https://github.com/Kotlin/kotlinx-kover

Thank you

**Comment by tgkprog** [comment]
This is an image the report I get now
![image](https://github.com/Kotlin/kotlinx-kover/assets/4226677/fec1bfe5-f084-4aa9-abc5-f049f91fe5b8)

Inspite of my build.gradle file having:

```

subprojects {
    apply(plugin = "org.jetbrains.kotlinx.kover")
    kover {

        filters {
            classes {
                excludes = listOf("*di.*", "*Factory*")
                 excludes += listOf("com.sel2in.kotlinDefaultsJson.app.App")
            }
            annotations {
                excludes += listOf("*Generated", "*CustomAnnotationToExclude")
            }
        }
        htmlReport {
            onCheck.set(true)
        }
        verify {
            rule {
                isEnabled = true
                name = "Line Coverage of Tests must be more than 80%"
                bound {
                    minValue = 1
                }
            }
        }
    }

}

```

**Comment by shanshin** [comment]
Hi,
to set up single-module projects, please refer to [the documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#single-module-kotlin-jvm-project), as well as to [the examples](https://github.com/Kotlin/kotlinx-kover/tree/main/kover-gradle-plugin/examples/jvm/single).

For a more convenient way to write build scripts and get hints from your IDE, I recommend using [`kts`](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html) instead of Groovy.

In your case, to exclude the specified files, you need instead of 
```kotlin
subprojects {
    apply(plugin = "org.jetbrains.kotlinx.kover")
    kover {
        filters {
            classes {
                excludes = listOf("*di.*", "*Factory*")
                 excludes += listOf("com.sel2in.kotlinDefaultsJson.app.App")
            }
            annotations {
                excludes += listOf("*Generated", "*CustomAnnotationToExclude")
            }
        }
        htmlReport {
            onCheck.set(true)
        }
        verify {
            rule {
                isEnabled = true
                name = "Line Coverage of Tests must be more than 80%"
                bound {
                    minValue = 1
                }
            }
        }
    }
        filters {
            classes {
                excludes = listOf("*di.*", "*Factory*")
                 excludes += listOf("com.sel2in.kotlinDefaultsJson.app.App")
            }
            annotations {
                excludes += listOf("*Generated", "*CustomAnnotationToExclude")
            }
        }
        htmlReport {
            onCheck.set(true)
        }
        verify {
            rule {
                isEnabled = true
                name = "Line Coverage of Tests must be more than 80%"
                bound {
                    minValue = 1
                }
            }
        }
    }

}
```

 write

```kotlin
kover {
    reports {
        filters {
            excludes {
                classes.addAll("*di.*", "*Factory*", "com.sel2in.kotlinDefaultsJson.app.App")
                annotatedBy.addAll("*Generated", "*CustomAnnotationToExclude")
            }
        }

        verify {
            rule("Line Coverage of Tests must be more than 80%") {
                bound {
                    minValue = 80
                }
            }
        }

        total {
            html {
                onCheck = true
            }
        }
    }
}
```

**Comment by shanshin** [comment]
I would also strongly recommend not using the JaCoCo and Kover plugins at the same time, because they alternately instrumented classes and this may lead to unstable operation of one of the tools.

**Comment by shanshin** [comment]
Closed as answered.
Feel free to create new issue if you have any additional questions.

**Comment by tgkprog** [comment]
It was also a suggestion for a better example and in non kts way as unfortunately I don't have control over that. But thank you for replying.

**Comment by shanshin** [comment]
> It was also a suggestion for a better example and in non kts way as unfortunately I don't have control over that. But thank you for replying.

The above example works the same way in Groovy (`build.gradle` files).
