### ISSUE TITLE
Reports for subprojects when running report on subproject

### ISSUE THREAD

**Issue by juliocbcotta** [Kotlin/kotlinx-kover#647]
**Describe the bug**
I don't know if it is a bug, but when I run 
```
./gradlew koverXmlReportSample
```
I get reports in all my gradle modules

if I run
```
./gradlew list:koverXmlReportSample
```
the report is generated only in the **:list** module

**Expected behavior**
I would expect all subprojects of **:list** module to contain their reports

**Reproducer**
https://github.com/juliocbcotta/Sample-Movie-App
It is a bit troublesome to setup in your local machine, but I can reproduce it there.

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 0.8.1
 - Gradle version: 8.6
 - Kotlin project type: Android

**Comment by shanshin** [comment]
This is a [feature](https://docs.gradle.org/current/userguide/command_line_interface.html#executing_tasks_in_multi_project_builds) of selecting tasks in Gradle.

If you specify the path to the task (for example, `: koverXmlReportSample `, `list:koverXmlReportSample` or `:list:koverXmlReportSample`) - this will cause the task to be executed in only one project.

If you specify only the name of the task (`koverXmlReportSample`), this will cause the task with this name to be executed in all projects in which it is present.

**Comment by juliocbcotta** [comment]
ahh, ok, thanks I will have to make the task depend on the others myself then.
