### ISSUE TITLE
Exclude pattern matching update doesn't work after a first run

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx-kover#65]
Happens on a basic android project. 

Top level build.gradle file : 
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        ...
        classpath("org.jetbrains.kotlinx:kover:0.4.2")
    }
}

apply plugin: 'kover'
```

Module level build.gradle file : 
```groovy
...
android {
    ...
    testOptions {
        unitTests.all {
            if (name == "testDebugUnitTest" || name == "testReleaseUnitTest") {
                kover {
                    //excludes = [".*_.*"]
                }
            }
        }
    }
}
```

Reproduction : 
run `./gradlew koverHtmlReport`
uncomment the excludes line
run again `./gradlew koverHtmlReport`

Result : 
![image](https://user-images.githubusercontent.com/11870220/142393977-f0710f8b-767d-4ee1-81e9-2079b1a17584.png)

Expected : 
![image](https://user-images.githubusercontent.com/11870220/142394043-0ca3450d-4960-4dfb-847f-cfd6a8116a5a.png)

Branch with the full code : 
https://github.com/NinoDLC/Kotlin_Flow_To_The_View/tree/kover_integration

Comments : 
It seems a change to the gradle file on the "exclude" line won't "update" the tasks correctly (the "sync" on Android Studio is way too fast for exemple)

**Comment by shanshin** [comment]
Hi,
at the moment, filtering is not implemented when generating reports (#17).
The exclusions that you changed affect the test run, so in order for them to have an effect on report, you need to regenerate the binary report file.
To do this, try clearing the build directory, e.g. `./gradlew clean koverHtmlReport`.

**Comment by shanshin** [comment]
Duplicate #17

**Comment by shanshin** [comment]
@NinoDLC, please, check in version `0.4.2`

**Comment by shanshin** [comment]
Feel free to reopen if the problem is not gone on `0.5.0`+
