### ISSUE TITLE
Getting No coverage information was found with Kover 0.7.6

### ISSUE THREAD

**Issue by jigarpandyadev** [Kotlin/kotlinx-kover#652]
I am using Kover 0.7.6 for a multi-module android app.  
in project's build.gradle, have added plugin 
`id("org.jetbrains.kotlinx.kover") version "0.7.6" apply false`

Also based on an open issue, have added 

```
subprojects {
    project.tasks.whenTaskAdded { task ->
        if (task.name.toLowerCase().contains("koverhtmlreport")) {
            task.doNotTrackState("Don't support state tracking")
        }
    }
}
```

in app module's build.gradle,
`id("org.jetbrains.kotlinx.kover") `
```
 koverReport {
    androidReports("debug"){
        filters {
            excludes {
                classes(
                        "*Fragment",
                        "*Fragment\$*",
                        "*Activity",
                        "*Activity\$*",
                        "*.databinding.*",
                        "*.BuildConfig"
                )
            }
        }
    }

}

```
and also added depenedencies of other modules in app module
`kover project(":module")`

also added kover plugin to other modules. but I keep getting the error like in the attached screenshot. Any help is appreciated.

![Screenshot 2024-07-08 at 8 21 28 PM](https://github.com/Kotlin/kotlinx-kover/assets/170303016/72f8d570-9453-4f7f-ba1a-7d2afefa0a02)

**Comment by shanshin** [comment]
Hi,
could you please clarify, which task do you use to generate the report? 
And is the set of Android build variants the same in all modules?

**Comment by jigarpandyadev** [comment]
@shanshin I have only debug and release variants for all modules. I tried with  ./gradlew koverHtmlReport and  ./gradlew koverHtmlReportDebug commands. I also tried version 0.8.2

**Comment by shanshin** [comment]
Using `0.8.2`, try to call `./gradlew :app:koverHtmlReportDebug` and open the report in the build directory of the `app` module (if you specify `dependencies { kover(project("...")) }` in `app`).

**Comment by jigarpandyadev** [comment]
I tried as you suggested but still no help.
![Uploading Screenshot 2024-07-09 at 3.46.10 PM.png…]()

**Comment by shanshin** [comment]
In this case, a reproducer project is needed

**Comment by jigarpandyadev** [comment]
Can you check in this demo project, why modules **common2** and **library2** have **No coverage information was found problem**
[Sketchboard.zip](https://github.com/user-attachments/files/16142131/Sketchboard.zip)

**Comment by jigarpandyadev** [comment]
Hey @shanshin thanks for checking. pls see in the attached screenshot that you shared, it doesn't list packages from common2 and library2 modules. My concern is, I'm unable to generate coverage for all the modules.

**Comment by shanshin** [comment]
As far as I can see, there is not a single class in the `library2` or `common2` package in your project.
<img width="326" alt="Screenshot 2024-07-09 at 13 14 43" src="https://github.com/Kotlin/kotlinx-kover/assets/7123498/b12955e4-f427-4114-bd23-0e6e25d0a821">

If you add any class there, for example `CommonClass`, you will see it in the report
<img width="521" alt="Screenshot 2024-07-09 at 13 16 41" src="https://github.com/Kotlin/kotlinx-kover/assets/7123498/c4555d26-9e0d-4680-83ec-3b8a0f87a6a3">

**Comment by jigarpandyadev** [comment]
thanks for the help @shanshin.
