### ISSUE TITLE
Different behaviour between Kover & JaCoCo coverage tools

### ISSUE THREAD

**Issue by bilousovam** [Kotlin/kotlinx-kover#666]
When I use Kover without Jacoco I have information about line coverage:
`Task :app:koverPrintCoverageDevRelease
:app line coverage: 18.0846%`
But when I add: 
` kover {
        useJacoco()
    }`
I always get:
`Task :app:koverPrintCoverageDevRelease
:app line coverage: 0%
[ant:jacocoReport] Rule violated for bundle :app: lines covered ratio is 0.0000, but expected minimum is 1.0000`

I try to use filters but it wasn't help. It isn't work with filters and without one.

Environment:
Kover Gradle Plugin version: 0.7.6 and 0.8.3
Gradle version: 8.1
Kotlin project type: Kotlin/Android
Coverage Toolset: Kover, JaCoCo

**Comment by shanshin** [comment]
Hi,
it's known issue https://github.com/Kotlin/kotlinx-kover/issues/544. 

Until #630 is implemented, ignore this message for `koverPrintCoverage...` tasks

**Comment by shanshin** [comment]
Fixed in `0.9.0-RC`
