### ISSUE TITLE
summarization of .ic files in one

### ISSUE THREAD

**Issue by Mike-Wazovsky** [Kotlin/kotlinx-kover#677]
Recently we reported a bug: https://github.com/Kotlin/kotlinx-kover/issues/672
And during discussion you suggested to "combine all binary reports into one, but to save each of them and pass all .ic files to kover-cli.jar report".

We've came up with idea that it might be generally useful to have a command line that takes a bunch of .ic files and summarize them into one. Just like in our case it will help a lot with disk space and provide an ability to capaciously save execution results.

**Comment by shanshin** [comment]
Implemented in `0.9.0-RC`

CLI command `merge`: https://github.com/Kotlin/kotlinx-kover/blob/main/kover-cli/docs/index.md#merging-binary-reports
Also in Kover Features artifact, function `kotlinx.kover.features.jvm.KoverLegacyFeatures#mergeIc`
