### ISSUE TITLE
Kover report tasks not cacheable

### ISSUE THREAD

**Issue by alextu** [Kotlin/kotlinx-kover#68]
When running a simple project twice with build cache enabled, we can see that the Kover report task is skipped:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/736523/142626572-6513d0f6-c52a-4448-a714-3594a5bfc1af.png">

which leads to no report being generated nor taken from a cache.
The way I would expect it working would be:
- First run stores the report into the build cache
- Second run does not skip the report task, just takes the report from the cache

**Comment by shanshin** [comment]
Thanks for the report!
Since the binary report file is not currently added to the output of the test task, if the test has the FROM-CACHE status, the binary report file is not restored and report generation is skipped.

**Comment by alextu** [comment]
I quickly checked it locally, you already have attached an extension to the test tasks so now it's just a matter of adding proper input/output annotations on `KoverTaskExtension`. Also in `CoverageArgumentProvider` don't forget also to define `@Nested val taskExtension: KoverTaskExtension`. You can take a look at [the built-in jacoco plugin](https://github.com/gradle/gradle/blob/master/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java#L216) for a concrete example.

**Comment by shanshin** [comment]
Fixed in `0.4.3`
