### ISSUE TITLE
How do I configure correctly an android project?

### ISSUE THREAD

**Issue by gerardoepitacio** [Kotlin/kotlinx-kover#69]
Tried

build.gragle - project
buildscript {

    repositories {

        google()

        mavenCentral()

    }

    dependencies {

        classpath "com.android.tools.build:gradle:7.0.2"

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30-RC"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath("org.jetbrains.kotlinx:kover:0.4.2")

    }
}

build.gradle file :app module
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id "org.jetbrains.kotlinx.kover"
}

Also tried only in build.gradle in :app module

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'

    id "org.jetbrains.kotlinx.kover" version "0.4.2"
}

// ...

None of this works, when I run ./gradlew :app:koverHtmlReport I got
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> Could not resolve all files for configuration ':app:IntellijKoverConfig'.
   > Could not find org.jetbrains.intellij.deps:intellij-coverage-agent:1.0.622.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/intellij/deps/intellij-coverage-agent/1.0.622/intellij-coverage-agent-1.0.622.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/intellij-coverage-agent/1.0.622/intellij-coverage-agent-1.0.622.pom
       - https://jcenter.bintray.com/org/jetbrains/intellij/deps/intellij-coverage-agent/1.0.622/intellij-coverage-agent-1.0.622.pom
     Required by:
         project :app
   > Could not find org.jetbrains.intellij.deps:intellij-coverage-reporter:1.0.622.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/intellij/deps/intellij-coverage-reporter/1.0.622/intellij-coverage-reporter-1.0.622.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/intellij-coverage-reporter/1.0.622/intellij-coverage-reporter-1.0.622.pom
       - https://jcenter.bintray.com/org/jetbrains/intellij/deps/intellij-coverage-reporter/1.0.622/intellij-coverage-reporter-1.0.622.pom
     Required by:
         project :app

**Comment by gerardoepitacio** [comment]
Leaving my project.
https://github.com/gerardoepitacio/KoverTest

**Comment by shanshin** [comment]
Hi,
perhaps your project is configured so that the repositories added by the plugin are not taken into account (#9).
Please wait for the next release in which IntelliJ agent artifacts will be downloaded from `mavenCentral` (#34)

**Comment by shanshin** [comment]
Duplicate #34

**Comment by cristan** [comment]
The reason why it can't find intellij-coverage-reporter:1.0.622 is because this version isn't on maven central (anymore?). You can fix it by manually specifying another version, but I'd say it's a pretty poor experience to be greeted with when you start the app. I've created [this issue](https://github.com/Kotlin/kotlinx-kover/issues/76) for it.

**Comment by cristan** [comment]
If you fix the dependency to intellij-coverage-reporter, you'll run into a JSONObject issue #77 and if you use JACOCO instead, you'll run into issue #78.

I'd say close this issue: it's too broad now that we have detailed issues with all the things Android users run into. But I totally agree with the sentiment: it's way too hard to get working on Android projects at this moment.

**Comment by shanshin** [comment]
Fixed in `0.4.3`
