### ISSUE TITLE
Suspend functions break branches coverage 

### ISSUE THREAD

**Issue by zhkvdm** [Kotlin/kotlinx-kover#691]
**Describe the bug**
Branches coverage is wrong then call suspend functions.
Suspend function break coverage to half. But I check all posible branches.
Branches coverage is ok if I call the same non suspend function. Just delete suspend codeword.

**Expected behavior**
Branches coverage is not depends on function type (suspend/non suspend)

**Reports**
Coverage check with suspend function call:
<img width="331" alt="suspend" src="https://github.com/user-attachments/assets/46292e4e-b588-47fb-b2db-0ed93acd1a39">

Coverage check with non suspend function call:
<img width="294" alt="non suspend" src="https://github.com/user-attachments/assets/c69a397b-5845-4b6c-89d3-66ca57af99b8">

**Environment**
 - Kover Gradle Plugin version: 0.9.0-RC
 - Gradle version: 17.0.1
 - Kotlin project type: Kotlin/Multiplatform + Android
 - Coverage Toolset (if customized in build script): Kover

**Comment by zhkvdm** [comment]
@shanshin Hello! Any comments to this issue? Do you reproduce the bug?

**Comment by shanshin** [comment]
@zhkvdm,  unfortunately, it was not possible to reproduce it locally.
```kotlin
var testVar: Int = 0

suspend fun testFun() {
    testVar = getTestData()
}

private suspend fun getTestData() = 1
```
Generated report
<img width="303" alt="Screenshot 2024-10-17 at 16 43 44" src="https://github.com/user-attachments/assets/da250c7e-01e4-4a80-ac49-5432fdab6f11">

**Comment by zhkvdm** [comment]
> @zhkvdm, unfortunately, it was not possible to reproduce it locally.
> 
> ```kotlin
> var testVar: Int = 0
> 
> suspend fun testFun() {
>     testVar = getTestData()
> }
> 
> private suspend fun getTestData() = 1
> ```
> 
> Generated report <img alt="Screenshot 2024-10-17 at 16 43 44" width="303" src="https://private-user-images.githubusercontent.com/7123498/377515749-da250c7e-01e4-4a80-ac49-5432fdab6f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODU5MzQsIm5iZiI6MTcyOTE4NTYzNCwicGF0aCI6Ii83MTIzNDk4LzM3NzUxNTc0OS1kYTI1MGM3ZS0wMWU0LTRhODAtYWM0OS01NDMyZmRhYjZmMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTcyMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc0NGFlYzFmM2ZjNWI4Zjk3ZWVjNzliOTI3ZjczOGE5MTk0ODgyZjQ1OWY5OWZmNGMxMTQ5NGY5MWRlYTM2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tsAPFMD8mvqBEe8iAHMpkZLBwjWseYN5yeJvIcnuVOE">

How is your test look like?
Class to test:
```
class TestVm {

    var testVar: Int = 0

    suspend fun testFun() {
        testVar = getTestData()
    }

    private suspend fun getTestData() = 1
}
```
Test:
```
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class TestVmTest {

    private var vM: TestVm = TestVm()

    @Test
    fun `Check test fun`() = runTest {
        vM.testFun()

        assertEquals(1, vM.testVar)
    }
}
```
Is it the same?

**Comment by zhkvdm** [comment]
Okay, in new empty project it works well. Looks like it is project specific issue..

**Comment by zhkvdm** [comment]
Find the way how to reproduce this. Just add jacoco. Without jacoco everything is okay.
