### ISSUE TITLE
Excluded annotated methods not ignored in Sonar

### ISSUE THREAD

**Issue by lawfulpepper** [Kotlin/kotlinx-kover#703]
This is related to Issue https://github.com/Kotlin/kotlinx-kover/issues/576.

Applies to version 0.8.3 and 0.9.0-RC.

I have Kover XML reports setup with Sonar.

Unfortunately excluding `@Composable` functions are not excluded in the Sonar coverage report.

If ignored, the `@Composable` is not added to the Kover XML report.

However, adding a simple Data Class in the same file causes Sonar to understand that this function should be ignored. Adding the Data Class adds the file to the XML report because of the uncovered Data Class.

```kotlin
data class UIData(
    val someData: String
)

@Composable
fun MyComposable() {
    Text("some text")
}
```

In the other issue, you had asked them if the XML report is used with Sonar. For us, yes, we are using the xml report path with Sonar.

Thanks!

**Comment by shanshin** [comment]
> Unfortunately excluding @Composable functions are not excluded in the Sonar coverage report.
> 
> If ignored, the @Composable is not added to the Kover XML report.

Hi, do I understand correctly that the marked function is missing in the xml report, but it is still displayed in Sonar?

**Comment by lawfulpepper** [comment]
Hi @shanshin , thanks for looking into this. Could you point me to where the XML report generation tool is used in the Kover codebase? I'll close this comment and try to see if there's a way to override the behavior internally.

Thanks

**Comment by shanshin** [comment]
@lawfulpepper, https://github.com/JetBrains/coverage-report/tree/master/report-builder/src/jetbrains/coverage/report
