### ISSUE TITLE
Create separate report for each Gradle test task

### ISSUE THREAD

**Issue by aansari15** [Kotlin/kotlinx-kover#704]
**What is your use-case and why do you need this feature?**
We currently have two Gradle tasks - `test` and `integrationTest`. These test tasks run in separate steps in our CI workflow. My use case is to generate a Kover report for each of these CI steps and upload them to Codecov. It should basically look like so:
- `unit_tests` CI step:
  - Run unit tests and generate coverage report from unit tests only
  - Upload this coverage report to Codecov
- `integration_tests` CI step
  - Run integration tests and generate coverage report from integration tests only
  - Upload this coverage report to Codecov

**Describe the solution you'd like**
I know that `disabledForTestTasks.add("integrationTest")` exists, but what I would like is to conditionally enable/disable coverage from a test task. So disable `integrationTest` when running the `unit_tests` CI step, and similarly disable `test` when running the `integration_tests` CI step

**Comment by shanshin** [comment]
Hi,
for your case, you can make conditional inclusion of tests depending on the passed parameters.

e.g. if you add build script
```kotlin

kover {
    currentProject {
        instrumentation {

            if (hasProperty("unit_tests")) {
                disabledForTestTasks.add("integrationTest")
            }

            if (hasProperty("integration_tests")) {
                disabledForTestTasks.add("test")
            }
            
        }
    }
}

```

you may specify parameters in different CI builds: `-Punit_tests` or `-Pintegration_tests`

**Comment by aansari15** [comment]
@shanshin thanks for the suggestion, works just as expected!

It could be worthwhile to add this to the official documentation as well, to help out others who may not be very well-versed with Gradle
