### ISSUE TITLE
Suppress Coverage for only functions instead of the whole class

### ISSUE THREAD

**Issue by rallat** [Kotlin/kotlinx-kover#705]
**What is your use-case and why do you need this feature?**
We have classes that are mostly testable and we would like to suppress coverage only for certain functions.

**Describe the solution you'd like**
A way for us to suppress coverage at the function level. It could be via annotation at the top of the function.

**Comment by shanshin** [comment]
Hi, 
if you specify a special filter
```kotlin
kover {
    reports.filters.excludes.annotatedBy("*.KoverExclude")
}
```
this will exclude the function marked with an annotation from the report
```
class Example {
    @KoverExclude
    fun functionToExclude() {
        ...
    }
}
```

**Comment by lawfulpepper** [comment]
Hey rallat, you can use a custom annotation and exclude it in the reports.

```kotlin
kover {
    reports {
        filters {
            excludes {
                annotatedBy(
                        "com.abc.rallat.ExcludeCoverage",
                )
            }
        }
    }
}
```

And the `ExcludeCoverage` can look something like:

```kotlin
@Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION)
annotation class ExcludeCoverage()
```

More info here: https://kotlin.github.io/kotlinx-kover/gradle-plugin/#filtering-reports

Is that what you were looking for?

**Comment by rallat** [comment]
Thanks
