### ISSUE TITLE
How to output coverage rate to command line?

### ISSUE THREAD

**Issue by xiaoqian0408** [Kotlin/kotlinx-kover#72]
Now we run kover task CI/CD pipeline as a command in command line.
Is there any way to output the coverage rate to command line? 
I tried to parse the kover report and fetch the coverage rate, but the xml file doesn't seem to be well structured. So it's not easy to parse it by using commands.

Thanks

**Comment by shanshin** [comment]
Hi,
you can calculate the percentage of coverage by taking the values of the `INSTRUCTION` counter from the root of the XML structure:  to find the coverage, it is enough to calculate `covered / (missed + covered)`, where `covered` and  `missed` are the values of the corresponding attributes.

At the moment, the root `INSTRUCTION` counter is the most recent counter of this type in the file. **However, this is may be changed at any time, so it is better to analyze the structure of the XML file.**
[Example for `LINE` counter](https://github.com/Kotlin/kotlinx-kover/blob/4b74293b39f73fa853cec696fdec8aab0e14eaf2/src/main/kotlin/kotlinx/kover/engines/intellij/IntellijCoverage.kt#L133)

**Comment by webfrea-k** [comment]
Gitlab CI/CD has a field that automatically reads the coverage from the report by specifying a [regular expression](https://docs.gitlab.com/ee/ci/pipelines/settings.html#test-coverage-examples) for it. All you need to do is to echo the index.html file at the end of testing stage, and Gitlab will parse the coverage from the echoed file. I believe that is what @xiaoqian0408 (and me) wants.

**Comment by webfrea-k** [comment]
@xiaoqian0408 for the time being here is what I did:
Gitlab CI/CD Test coverage parsing field: `\d+\.\d+%`
Echoing the report after the test step in yml:     `- head -42 <projectDir>/build/reports/kover/html/index.html # echo only what is needed for coverage parsing`
