### ISSUE TITLE
bug: number of lines is wrong

### ISSUE THREAD

**Issue by DerYeger** [Kotlin/kotlinx-kover#79]
Kover reports incorrect coverage because the total line count is wrong (see attached image).

My configuration is:

```kotlin
kover {
  isEnabled = true
  coverageEngine.set(kotlinx.kover.api.CoverageEngine.INTELLIJ)
  generateReportOnCheck.set(true)
}
```

Running the `test` task with IntelliJ's coverage analysis, I get a coverage of 44% in this file.
While 44% is still wrong, it does correctly count the number of lines at 49.

![image](https://user-images.githubusercontent.com/7950094/143676549-8eaa0812-bb52-4321-b23f-79ba8b024c37.png)

**Comment by shanshin** [comment]
Relates https://youtrack.jetbrains.com/issue/IDEA-283587 and https://youtrack.jetbrains.com/issue/IDEA-283555

**Comment by shanshin** [comment]
@DerYeger, please test version `0.5.0-RC2`
