### ISSUE TITLE
Test fixtures are included in coverage

### ISSUE THREAD

**Issue by markslater** [Kotlin/kotlinx-kover#83]
Kover treats [test fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) as production code, including them in coverage reports.  Test fixtures *should* be treated as test code.

If I add the (misleadingly named) `java-test-fixtures` plugin, along with the `kotlin` and `kover` plugins, Gradle will look in `src/testFixtures/kotlin` for code "used to setup the code under test, or provide utilities aimed at facilitating the tests of a component":

```kotlin
plugins {
    kotlin("jvm") version "1.6.0"
    `java-test-fixtures`
    id("org.jetbrains.kotlinx.kover") version "0.4.4"
}
```

The `testFixtures` code is explicitly test code, but if I run `./gradlew koverHtmlReport`, the generated report includes any code in the `testFixtures` directory in addition to the code in `main`.

I've put together [a small example project illustrating the issue](https://github.com/markslater/kover-examples/tree/6ef2da3d3092a102f4266fde41a44f101289e5d0).

**Comment by shanshin** [comment]
To search for project classes, Kover uses all the source sets except `test`.
An API is currently being developed to exclude a source set by name, in your case it is `testFixtures` (see #19)

**Comment by markslater** [comment]
Great.

> To search for project classes, Kover uses all the source sets except test.

This doesn't sound quite right to me - [Gradle defines the test fixtures as test code](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures).  Although there are circumstances under which you might want to measure the test coverage of your test fixtures (you can optionally publish test fixtures), it's counterintuitive to combine this with the coverage of the `m̀ain` source set by default.

**Comment by shanshin** [comment]
> This doesn't sound quite right to me - Gradle defines the test fixtures as test code. 

Kover takes a list of project classes from all available source sets (except for `test`). The fact that the source set is a test is determined only by the `java-test-fixtures` plugin, Gradle itself does not know about its purpose. Therefore, there is no attribute in the Grade API by which Kover could exclude the fixtures classes.

**Comment by markslater** [comment]
Fair enough.

I *think* the built-in Jacoco plugin only takes the `main` source set by default, and is configurable to add more.  To me, this seems intuitive, but I accept opinions may vary.

**Comment by shanshin** [comment]
Duplcates #19 

*filtering of sourcesets
