### ISSUE TITLE
Make report tasks cache relocatable 

### ISSUE THREAD

**Issue by alextu** [Kotlin/kotlinx-kover#85]
Thanks for making the task cacheable as part of 0.4.4. Now I'm seeing that inputs are using absolute path, so I'm getting cache misses when running from different directories (see sshot below).
It can easily be fixed by specifying `PathSensitive(PathSensitivity.RELATIVE)` on relevant inputs.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/736523/144268187-5da5acc7-fb0a-4209-b6f8-b5f177500302.png">

**Comment by shanshin** [comment]
Implemented in `0.5.0-RC`.
