### ISSUE TITLE
Android tests generates 0% coverage

### ISSUE THREAD

**Issue by gerardoepitacio** [Kotlin/kotlinx-kover#87]
I Added test to have a 100% coverage as an Android instrumentation tests "androidTest" folder.

This is a pretty common way to tests classes in Android, some of them are tested as Unit tests and some of them as Android Instrumented Test, It would be great that:
1- be able to have coverage from Android Tests
2- have a merged report from unit test tests in "test" folder and Android tests, tests in "androidTest" folder.
3- if it's a multi module project, it would be great to have a unified report for both unit Tests and Android tests for all modules.

![image](https://user-images.githubusercontent.com/6610535/144761987-c52311c1-f9bb-4430-8d4f-95444ada923b.png)

Android project in (ignore module01 by now)
https://github.com/gerardoepitacio/KoverTest

running
./gradlew clean app:koverHtmlReport

generates a report in app/build/reports where
![Screen Shot 2021-12-05 at 14 06 59](https://user-images.githubusercontent.com/6610535/144762152-c3bbefbf-0478-45dd-b70a-d29b14cbb5e8.png)

But all methods in RemoteDataProviderImpl.kt are tested.
![Screen Shot 2021-12-05 at 14 07 32](https://user-images.githubusercontent.com/6610535/144762163-ccae9d07-dfe4-4b53-a6e4-88858f796180.png)

**Comment by shanshin** [comment]
Duplicates #96

**Comment by shanshin** [comment]
Relates #43

**Comment by shanshin** [comment]
Closed as duplicate

**Comment by nathanfallet** [comment]
I have the same issue on a backend startup test with one of my Koin modules. All of them are correctly working except this one.

<img width="1148" height="178" alt="Image" src="https://github.com/user-attachments/assets/54da175b-d249-437f-b3b0-e7005c712fdd" />

<img width="658" height="188" alt="Image" src="https://github.com/user-attachments/assets/fb134014-cfd0-42b9-968b-c1b73fcd484b" />

<img width="489" height="120" alt="Image" src="https://github.com/user-attachments/assets/d63153f8-25cf-4b9b-9ea7-bc39696ffdef" />

<img width="276" height="202" alt="Image" src="https://github.com/user-attachments/assets/d09b02d1-f062-4149-af5f-85fee9d28b54" />

I know it's not related to Android, but it's the only case I found of a 100% coverage that is ignored on a file, using Kover.
