### ISSUE TITLE
Implement IJ reporter args json format

### ISSUE THREAD

**Issue by zuevmaxim** [Kotlin/kotlinx-kover#91]
```
{
  reports: [{ic: "path", smap: "path"}, ...],
  modules: [{output: ["path1", "path2"], sources: ["source1", …]}, {…}],
  xml: "path" [OPTIONAL],
  html: "directory" [OPTIONAL],
  include: {
        classes: ["regex1", "regex2"] [OPTIONAL]
   } [OPTIONAL],
  exclude: {
        classes: ["regex1", "regex2"] [OPTIONAL]
   } [OPTIONAL],
}
```

* `reports` -- list of binary (ic format) reports generated by agent. Reports are not separated by modules, as it is not discoverable whether what module is covered by which report. All the binary reports information is merged.
* `modules` -- list of outputs and sources included into the report. Division into modules just simplifies the structure of the json. Classes in the output directories are the only classes that may be included into the report.
* `xml` -- path to an XML file to be generated
* `html` -- path to a directory to generate HTML
* `include`/`exclude` -- list of classes to be included/excluded into the report. Note that these filters may differ from the filters passed to the agent, so all the classes in all outputs are iterated and reloaded if new filters include it. List of supported filters will be extended to `methods` and `lines`.

**Comment by shanshin** [comment]
Implemented in `0.5.0-RC2`
