### ISSUE TITLE
Setting koverXmlReport as a dependency of koverCollectReports does not work.

### ISSUE THREAD

**Issue by HabeebAhmed1234** [Kotlin/kotlinx-kover#92]
I need to move all of my submodule reports to the root project directory so I'm trying to make sure koverCollectReports runs after koverXmlReport. I do this by adding 

tasks.koverCollectReports {
    dependsOn koverXmlReport
}

to the root build.gradle file. However this causes the koverXmlReport to always be up-to-date and thus skipped. I then try to force koverXmlReport to never be up-to-date by:

tasks.koverXmlReport {
    outputs.upToDateWhen { false }
}

koverXmlReport then runs as a task when running ./gradlew koverCollectReports but even so koverXmlReport is not actually doing anything (only takes less than a second to run).

Is there something I'm missing here? Or is it not possible to set koverXmlReport as a dependency  of koverCollectReports?

**Comment by shanshin** [comment]
Hi,
could you clarify if you are using Kover version `0.4.2` or `0.4.4`?

**Comment by shanshin** [comment]
Please try using version `0.5.0-RC2`
