### ISSUE TITLE
Allow `koverCollectReports` to aggregate into single report file 

### ISSUE THREAD

**Issue by unredundant** [Kotlin/kotlinx-kover#93]
Hey, very excited about this plugin!  I think there would be a nice addition to make to the `koverCollectReports` task that would allow all collected reports to be piped into a single discoverable file.  At the moment it seems to simply take the distinct reports from each module and move them all into a parent folder. 

<img width="285" alt="Screen Shot 2021-12-12 at 7 37 39 PM" src="https://user-images.githubusercontent.com/5607577/145736322-7464d889-133b-436e-ae69-cf114922ece1.png">

For HTML this may even be as simple as having the `koverCollectReports` task add an `index.html` file in the `html` directory here that provides hyperlinks to each child module results.  For XML I admit I'm just not sure how all that works haha, being lazy.  

The reason being, that for CI code coverage integration, often times you need to explicitly list the file or files that you wish to upload.  Previously for Jacoco, I had a very ugly hand rolled gradle task that would smush all jacoco reports into a single report, but it would be nice if Kover offered this functionality out of the box :)

**Comment by shanshin** [comment]
Hi,
this task already in progress #90.
Duplicates #43

**Comment by unredundant** [comment]
Perfect 👌 gonna close this
