### ISSUE TITLE
koverHtmlReport fails

### ISSUE THREAD

**Issue by felislynx-silae** [Kotlin/kotlinx-kover#94]
Using 0.4.4, adding just plugin to root project, running task koverHtmlReport fails after all tests with message:
Execution failed for task ':myapp:koverHtmlReport'.
> org.gradle.process.JavaExecSpec.getMainClass()Lorg/gradle/api/provider/Property;

**Comment by shanshin** [comment]
Hi,
could you clarify your version of the Gradle?

**Comment by felislynx-silae** [comment]
classpath 'com.android.tools.build:gradle:3.6.4'
        distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

This project is during library upgrade process which takes time ;)

**Comment by shanshin** [comment]
Minimal supported Gradle version is `6.4`.
For versions below, stability is not guaranteed.

**Comment by felislynx-silae** [comment]
@shanshin Thank you very much, i'll retry when everything will be updated and if issue will persist, i'll report new issue.
