### ISSUE TITLE
How to config Gradle DSL for multiplatform target(Android and iOS)

### ISSUE THREAD

**Issue by pddkhoa-fossil** [Kotlin/kotlinx-kover#97]

**Comment by shanshin** [comment]
Hi,
could you clarify which configuration you want to perform for the Android project?

At the moment, the plugin has limited options for configuring Android applications.

**Comment by pddkhoa-fossil** [comment]
@shanshin Currently, I build a Kotlin multiplatform project(Android and iOS) and use Kover in `shared` module.
My setup for Kover in `build.gradle.kts` (shared module)
```
tasks.koverHtmlReport {
    isEnabled = true                        // false to disable report generation
    htmlReportDir.set(layout.buildDirectory.dir("sdk-reports/html-sdk-result"))
}

kover {
    isEnabled = true                        // false to disable instrumentation of all test tasks in all modules
    coverageEngine.set(kotlinx.kover.api.CoverageEngine.INTELLIJ) // change instrumentation agent and reporter
    intellijEngineVersion.set("1.0.622")    // change version of IntelliJ agent and reporter
    jacocoEngineVersion.set("0.8.7")        // change version of JaCoCo agent and reporter
    generateReportOnCheck.set(true)         // false to do not execute `koverReport` task before `check` task
}
```
I run in terminal: `./gradlew :shared:koverHtmlReport`, everything work good but it's seem `Kover` library only build unit test for Android target without iOS target. Can i set up to build for both Android and iOS target.

I read recommand from [Kotlin 1.6.0 release](https://kotlinlang.org/docs/whatsnew16.html#kover-a-code-coverage-tool-for-kotlin) that the library work good for Kotlin multiplatform project.

**Comment by shanshin** [comment]
Currently, the IntelliJ Coverage Agent supports only instrumentation of tests executing in the JVM on the same machine on which the Gradle build is running. Native or JS targets are not supported yet.

We are considering the possibility of implementing such agents in the future.

**Comment by pddkhoa-fossil** [comment]
@shanshin Okay. Thank you very much <3

**Comment by shanshin** [comment]
Duplicates #96
